#!/usr/bin/env python3
"""Snapshot and launch a bounded local DC experiment in the existing EDA container."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[2]


def timestamp():
    return datetime.now(timezone.utc).isoformat()


def worker(out, container):
    manifest = json.loads((out / "manifest.json").read_text())
    limit = manifest["timeout_seconds"]
    status = {"state": "RUNNING", "started": timestamp(), "pid": os.getpid()}
    (out / "status.json").write_text(json.dumps(status, indent=2) + "\n")
    command = ["docker", "exec", "-u", f"{os.getuid()}:{os.getgid()}",
               "-e", f"HOME={Path.home()}",
               "-e", f"DC_ELAB_ONLY={int(manifest['elaborate_only'])}",
               "-e", f"DC_LOCAL_TOP={manifest['top']}",
               "-e", f"DC_COMPACT_READ={int(manifest.get('compact_read', False))}",
               "-e", f"DC_ELEMENT_WIDTH={manifest.get('element_width', 2)}",
               "-w", str(out), container, "bash", "-lc",
               f"exec timeout --signal=TERM --kill-after=30s {limit} dc_shell -f payload_dc.tcl"]
    try:
        with (out / "dc.log").open("w") as log:
            result = subprocess.run(command, stdout=log, stderr=subprocess.STDOUT)
        text = (out / "dc.log").read_text(errors="replace")
        errors = [line for line in text.splitlines() if line.startswith(("Error:", "Fatal:"))]
        marker = "PAYLOAD_DC_ELAB_COMPLETE" if manifest["elaborate_only"] else "PAYLOAD_DC_COMPLETE"
        passed = result.returncode == 0 and not errors and marker in text
        state = "TIMEOUT" if result.returncode == 124 else "PASS" if passed else "FAIL"
        status.update(state=state, exit_code=result.returncode,
                      errors=errors, finished=timestamp())
    except Exception as exc:
        status.update(state="FAIL", error=str(exc), finished=timestamp())
    (out / "status.json").write_text(json.dumps(status, indent=2) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--container", default="synopsys_workspace")
    parser.add_argument("--top", choices=("qbs_payload_buffer", "qbs_block_adapter",
                                         "qbs_ingress_timing", "simd_mul_timing",
                                         "simd_alu_timing", "qbs_decode_dot_timing",
                                         "vfdsu_round_timing", "ara_dispatcher_timing",
                                         "qbs_correction_select_timing", "qbs_address_timing"),
                        default="qbs_payload_buffer")
    parser.add_argument("--elaborate-only", action="store_true",
                        help="save and inspect GTECH without technology mapping")
    parser.add_argument("--compact-read", action="store_true",
                        help="elaborate NativeView=0, as used by the compute engine")
    parser.add_argument("--reference", help="snapshot QBS RTL from this Git revision")
    parser.add_argument("--source-overrides", type=Path,
                        help="directory with pre-edit payload/adapter or SIMD multiplier RTL")
    parser.add_argument("--cone-dir", type=Path,
                        help="pre/post cones generated by generate_feedback_checks.py")
    parser.add_argument("--element-width", type=int, choices=(0, 1, 2, 3), default=2,
                        help="SIMD multiplier SEW encoding: 0/1/2/3 = 8/16/32/64")
    parser.add_argument("--timeout-seconds", type=int, default=3600)
    parser.add_argument("--worker", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args()
    out = args.output.resolve()
    if args.worker:
        worker(out, args.container)
        return
    if args.timeout_seconds <= 0:
        parser.error("--timeout-seconds must be positive")
    if args.reference and args.source_overrides:
        parser.error("--reference and --source-overrides are mutually exclusive")
    if args.reference and args.top in ("simd_mul_timing", "simd_alu_timing", "vfdsu_round_timing"):
        parser.error("SIMD dependencies are external; use --source-overrides for pre-edit RTL")
    if args.source_overrides and not args.source_overrides.is_dir():
        parser.error("--source-overrides must be a directory")
    is_feedback_cone = args.top in ("qbs_correction_select_timing", "qbs_address_timing")
    if is_feedback_cone and (args.cone_dir is None or
                            not (args.cone_dir / (args.top + ".sv")).is_file()):
        parser.error("feedback cone tops require --cone-dir containing the generated source")
    if is_feedback_cone and (args.reference or args.source_overrides):
        parser.error("feedback cones use --cone-dir, not --reference/--source-overrides")
    reference = None
    if args.reference:
        reference = subprocess.check_output(
            ["git", "-C", str(ROOT), "rev-parse", "--verify", args.reference + "^{commit}"],
            text=True).strip()
    out.mkdir(parents=True, exist_ok=False)
    (out / "src").mkdir()
    sources = [ROOT / "hardware/include/qbs_pkg.sv"] + [
        ROOT / "hardware/src/vlsu/qbs" / name
        for name in ("qbs_payload_sram.sv", "qbs_payload_buffer.sv")]
    if args.top in ("qbs_block_adapter", "qbs_ingress_timing"):
        sources.append(ROOT / "hardware/src/vlsu/qbs/qbs_block_adapter.sv")
    if args.top == "qbs_decode_dot_timing":
        sources = [ROOT / "hardware/include/qbs_pkg.sv"] + [
            ROOT / "hardware/src/vlsu/qbs" / name
            for name in ("qbs_profile_decoder.sv", "qbs_dot_array.sv")]
    if args.top == "vfdsu_round_timing":
        sources = [ROOT / path for path in (
            "hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v",
            "hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v")]
    if args.top in ("simd_mul_timing", "simd_alu_timing", "ara_dispatcher_timing"):
        sources = [ROOT / path for path in (
            "hardware/deps/common_cells/src/cf_math_pkg.sv",
            "hardware/deps/axi/src/axi_pkg.sv",
            "hardware/deps/fpnew/src/fpnew_pkg.sv",
            "hardware/deps/cva6/core/include/config_pkg.sv",
            "hardware/deps/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv",
            "hardware/deps/cva6/core/include/riscv_pkg.sv",
            "hardware/include/rvv_pkg.sv", "hardware/include/ara_pkg.sv")]
        if args.top == "ara_dispatcher_timing":
            sources += [ROOT / path for path in (
                "hardware/deps/cva6/core/include/build_config_pkg.sv",
                "hardware/include/qbs_pkg.sv", "hardware/include/akv_pkg.sv",
                "hardware/deps/common_cells/src/popcount.sv",
                "hardware/deps/common_cells/src/delta_counter.sv",
                "hardware/deps/common_cells/src/counter.sv",
                "hardware/src/segment_sequencer.sv", "hardware/src/ara_dispatcher.sv")]
        else:
            sources += [ROOT / "hardware/src/lane" / name for name in (
                ("simd_mul.sv",) if args.top == "simd_mul_timing" else
                ("simd_alu.sv", "fixed_p_rounding.sv"))]
    if is_feedback_cone:
        sources = [ROOT / "hardware/deps/common_cells/src/cf_math_pkg.sv",
                   ROOT / "hardware/deps/common_cells/src/lzc.sv",
                   args.cone_dir.resolve() / (args.top + ".sv")]
    records = []
    for source in sources:
        target = out / "src" / source.name
        if reference:
            target.write_bytes(subprocess.check_output([
                "git", "-C", str(ROOT), "show", f"{reference}:{source.relative_to(ROOT)}"]))
        elif (args.source_overrides and source.name in
              ("qbs_payload_buffer.sv", "qbs_block_adapter.sv", "simd_mul.sv",
               "simd_alu.sv", "qbs_dot_array.sv", "ct_vfdsu_round.v", "ara_dispatcher.sv")):
            shutil.copy2(args.source_overrides / source.name, target)
        else:
            shutil.copy2(source, target)
        records.append({"path": str(source.relative_to(ROOT)) if source.is_relative_to(ROOT) else str(source),
                        "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
    if is_feedback_cone:
        for name in ("assertions.svh", "assertions_dummy.svh"):
            source = ROOT / "hardware/deps/common_cells/include/common_cells" / name
            if source.is_file():
                target = out / "src/common_cells" / name
                target.parent.mkdir(exist_ok=True)
                shutil.copy2(source, target)
                records.append({"path": str(source.relative_to(ROOT)),
                                "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
    if args.top == "vfdsu_round_timing":
        from generate_closure_checks import round_timing_module
        target = out / "src/vfdsu_round_timing.sv"
        target.write_text(round_timing_module((out / "src/ct_vfdsu_round.v").read_text()))
        records.append({"path": "generated:vfdsu_round_timing.sv",
                        "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
    if args.top in ("qbs_ingress_timing", "simd_mul_timing", "simd_alu_timing",
                    "qbs_decode_dot_timing", "ara_dispatcher_timing"):
        source = Path(__file__).with_name(args.top + ".sv")
        target = out / "src" / source.name
        shutil.copy2(source, target)
        records.append({"path": str(source.relative_to(ROOT)),
                        "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
    if args.top in ("simd_mul_timing", "simd_alu_timing", "ara_dispatcher_timing"):
        source = ROOT / "hardware/deps/common_cells/include/common_cells/registers.svh"
        target = out / "src/common_cells/registers.svh"
        target.parent.mkdir()
        shutil.copy2(source, target)
        records.append({"path": str(source.relative_to(ROOT)),
                        "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
    if args.top == "ara_dispatcher_timing":
        from generate_dispatcher_check import interface_package
        target = out / "src/dispatcher_check_pkg.sv"
        target.write_text(interface_package())
        records.append({"path": "generated:dispatcher_check_pkg.sv",
                        "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
        source = ROOT / "hardware/include/ara/intf_typedef.svh"
        target = out / "src/ara/intf_typedef.svh"
        target.parent.mkdir()
        shutil.copy2(source, target)
        records.append({"path": str(source.relative_to(ROOT)),
                        "sha256": hashlib.sha256(target.read_bytes()).hexdigest()})
    shutil.copy2(Path(__file__).with_name("payload_dc.tcl"), out / "payload_dc.tcl")
    shutil.copy2(ROOT / "backend/syn/ara_soc/v1-dc/global_scripts/synopsys_dc.setup.env",
                 out / "library_env.tcl")
    shutil.copy2(Path(__file__), out / "runner.py")
    commit = subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True).strip()
    diff = subprocess.check_output(["git", "-C", str(ROOT), "diff", "HEAD", "--",
                                   "hardware/src", "hardware/include"])
    (out / "rtl.patch").write_bytes(b"" if reference else diff)
    (out / "manifest.json").write_text(json.dumps({"commit": commit, "sources": records,
        "created": timestamp(), "scope": "local_timing_not_soc", "top": args.top,
        "period_ns": 1.0,
        "setup_uncertainty_ns": 0.15, "cores": 2, "reference": reference,
        "source_overrides": str(args.source_overrides.resolve()) if args.source_overrides else None,
        "clock_gating": args.top in ("qbs_ingress_timing", "simd_mul_timing",
                                     "simd_alu_timing", "qbs_decode_dot_timing", "vfdsu_round_timing",
                                     "ara_dispatcher_timing", "qbs_correction_select_timing",
                                     "qbs_address_timing"),
        "element_width": args.element_width,
        "elaborate_only": args.elaborate_only, "compact_read": args.compact_read,
        "timeout_seconds": args.timeout_seconds,
        "flow_sha256": {name: hashlib.sha256((out / name).read_bytes()).hexdigest()
                        for name in ("payload_dc.tcl", "library_env.tcl", "runner.py")}},
        indent=2) + "\n")
    with (out / "worker.log").open("w") as log:
        proc = subprocess.Popen([sys.executable, str(out / "runner.py"),
            "--worker", "--output", str(out), "--container", args.container],
            stdin=subprocess.DEVNULL, stdout=log, stderr=subprocess.STDOUT,
            start_new_session=True)
    print(f"started pid={proc.pid} output={out}")


if __name__ == "__main__":
    main()
