# Generated from manifest.json. All paths are package-relative.
set rtl_files [list {rtl/tech_cells_generic/src/fpga/pad_functional_xilinx.sv} \
    {rtl/tech_cells_generic/src/fpga/tc_clk_xilinx.sv} \
    {rtl/tech_cells_generic/src/fpga/tc_sram_xilinx.sv} \
    {rtl/tech_cells_generic/src/rtl/tc_sram_impl.sv} \
    {rtl/tech_cells_generic/src/deprecated/pulp_clock_gating_async.sv} \
    {rtl/tech_cells_generic/src/deprecated/cluster_clk_cells.sv} \
    {rtl/tech_cells_generic/src/deprecated/pulp_clk_cells.sv} \
    {rtl/common_cells/src/binary_to_gray.sv} \
    {rtl/common_cells/src/cb_filter_pkg.sv} \
    {rtl/common_cells/src/cc_onehot.sv} \
    {rtl/common_cells/src/cdc_reset_ctrlr_pkg.sv} \
    {rtl/common_cells/src/cf_math_pkg.sv} \
    {rtl/common_cells/src/clk_int_div.sv} \
    {rtl/common_cells/src/credit_counter.sv} \
    {rtl/common_cells/src/delta_counter.sv} \
    {rtl/common_cells/src/ecc_pkg.sv} \
    {rtl/common_cells/src/edge_propagator_tx.sv} \
    {rtl/common_cells/src/exp_backoff.sv} \
    {rtl/common_cells/src/fifo_v3.sv} \
    {rtl/common_cells/src/gray_to_binary.sv} \
    {rtl/common_cells/src/heaviside.sv} \
    {rtl/common_cells/src/isochronous_4phase_handshake.sv} \
    {rtl/common_cells/src/isochronous_spill_register.sv} \
    {rtl/common_cells/src/lfsr.sv} \
    {rtl/common_cells/src/lfsr_16bit.sv} \
    {rtl/common_cells/src/lfsr_8bit.sv} \
    {rtl/common_cells/src/lossy_valid_to_stream.sv} \
    {rtl/common_cells/src/mv_filter.sv} \
    {rtl/common_cells/src/onehot_to_bin.sv} \
    {rtl/common_cells/src/plru_tree.sv} \
    {rtl/common_cells/src/passthrough_stream_fifo.sv} \
    {rtl/common_cells/src/popcount.sv} \
    {rtl/common_cells/src/ring_buffer.sv} \
    {rtl/common_cells/src/rr_arb_tree.sv} \
    {rtl/common_cells/src/rstgen_bypass.sv} \
    {rtl/common_cells/src/serial_deglitch.sv} \
    {rtl/common_cells/src/shift_reg.sv} \
    {rtl/common_cells/src/shift_reg_gated.sv} \
    {rtl/common_cells/src/spill_register_flushable.sv} \
    {rtl/common_cells/src/stream_demux.sv} \
    {rtl/common_cells/src/stream_filter.sv} \
    {rtl/common_cells/src/stream_fork.sv} \
    {rtl/common_cells/src/stream_intf.sv} \
    {rtl/common_cells/src/stream_join_dynamic.sv} \
    {rtl/common_cells/src/stream_mux.sv} \
    {rtl/common_cells/src/stream_throttle.sv} \
    {rtl/common_cells/src/sub_per_hash.sv} \
    {rtl/common_cells/src/sync.sv} \
    {rtl/common_cells/src/sync_wedge.sv} \
    {rtl/common_cells/src/unread.sv} \
    {rtl/common_cells/src/read.sv} \
    {rtl/common_cells/src/addr_decode_dync.sv} \
    {rtl/common_cells/src/boxcar.sv} \
    {rtl/common_cells/src/cdc_2phase.sv} \
    {rtl/common_cells/src/cdc_4phase.sv} \
    {rtl/common_cells/src/clk_int_div_static.sv} \
    {rtl/common_cells/src/trip_counter.sv} \
    {rtl/common_cells/src/addr_decode.sv} \
    {rtl/common_cells/src/addr_decode_napot.sv} \
    {rtl/common_cells/src/multiaddr_decode.sv} \
    {rtl/common_cells/src/cb_filter.sv} \
    {rtl/common_cells/src/cdc_fifo_2phase.sv} \
    {rtl/common_cells/src/clk_mux_glitch_free.sv} \
    {rtl/common_cells/src/counter.sv} \
    {rtl/common_cells/src/ecc_decode.sv} \
    {rtl/common_cells/src/ecc_encode.sv} \
    {rtl/common_cells/src/edge_detect.sv} \
    {rtl/common_cells/src/lzc.sv} \
    {rtl/common_cells/src/max_counter.sv} \
    {rtl/common_cells/src/rstgen.sv} \
    {rtl/common_cells/src/spill_register.sv} \
    {rtl/common_cells/src/stream_delay.sv} \
    {rtl/common_cells/src/stream_fifo.sv} \
    {rtl/common_cells/src/stream_fork_dynamic.sv} \
    {rtl/common_cells/src/stream_join.sv} \
    {rtl/common_cells/src/cdc_reset_ctrlr.sv} \
    {rtl/common_cells/src/cdc_fifo_gray.sv} \
    {rtl/common_cells/src/fall_through_register.sv} \
    {rtl/common_cells/src/id_queue.sv} \
    {rtl/common_cells/src/stream_to_mem.sv} \
    {rtl/common_cells/src/stream_arbiter_flushable.sv} \
    {rtl/common_cells/src/stream_fifo_optimal_wrap.sv} \
    {rtl/common_cells/src/stream_register.sv} \
    {rtl/common_cells/src/stream_xbar.sv} \
    {rtl/common_cells/src/cdc_fifo_gray_clearable.sv} \
    {rtl/common_cells/src/cdc_2phase_clearable.sv} \
    {rtl/common_cells/src/mem_to_banks_detailed.sv} \
    {rtl/common_cells/src/stream_arbiter.sv} \
    {rtl/common_cells/src/stream_omega_net.sv} \
    {rtl/common_cells/src/mem_to_banks.sv} \
    {rtl/common_cells/src/deprecated/clock_divider_counter.sv} \
    {rtl/common_cells/src/deprecated/clk_div.sv} \
    {rtl/common_cells/src/deprecated/find_first_one.sv} \
    {rtl/common_cells/src/deprecated/generic_LFSR_8bit.sv} \
    {rtl/common_cells/src/deprecated/generic_fifo.sv} \
    {rtl/common_cells/src/deprecated/prioarbiter.sv} \
    {rtl/common_cells/src/deprecated/pulp_sync.sv} \
    {rtl/common_cells/src/deprecated/pulp_sync_wedge.sv} \
    {rtl/common_cells/src/deprecated/rrarbiter.sv} \
    {rtl/common_cells/src/deprecated/clock_divider.sv} \
    {rtl/common_cells/src/deprecated/fifo_v2.sv} \
    {rtl/common_cells/src/deprecated/fifo_v1.sv} \
    {rtl/common_cells/src/edge_propagator_ack.sv} \
    {rtl/common_cells/src/edge_propagator.sv} \
    {rtl/common_cells/src/edge_propagator_rx.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/control_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv} \
    {rtl/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv} \
    {rtl/apb/src/apb_pkg.sv} \
    {rtl/apb/src/apb_intf.sv} \
    {rtl/apb/src/apb_err_slv.sv} \
    {rtl/apb/src/apb_regs.sv} \
    {rtl/apb/src/apb_cdc.sv} \
    {rtl/apb/src/apb_demux.sv} \
    {rtl/axi/src/axi_pkg.sv} \
    {rtl/axi/src/axi_demux_id_counters.sv} \
    {rtl/axi/src/axi_intf.sv} \
    {rtl/axi/src/axi_atop_filter.sv} \
    {rtl/axi/src/axi_burst_splitter_gran.sv} \
    {rtl/axi/src/axi_burst_unwrap.sv} \
    {rtl/axi/src/axi_bus_compare.sv} \
    {rtl/axi/src/axi_cdc_dst.sv} \
    {rtl/axi/src/axi_cdc_src.sv} \
    {rtl/axi/src/axi_cut.sv} \
    {rtl/axi/src/axi_delayer.sv} \
    {rtl/axi/src/axi_demux_simple.sv} \
    {rtl/axi/src/axi_dw_downsizer.sv} \
    {rtl/axi/src/axi_dw_upsizer.sv} \
    {rtl/axi/src/axi_fifo.sv} \
    {rtl/axi/src/axi_fifo_delay_dyn.sv} \
    {rtl/axi/src/axi_id_remap.sv} \
    {rtl/axi/src/axi_id_prepend.sv} \
    {rtl/axi/src/axi_isolate.sv} \
    {rtl/axi/src/axi_join.sv} \
    {rtl/axi/src/axi_lite_demux.sv} \
    {rtl/axi/src/axi_lite_dw_converter.sv} \
    {rtl/axi/src/axi_lite_from_mem.sv} \
    {rtl/axi/src/axi_lite_join.sv} \
    {rtl/axi/src/axi_lite_lfsr.sv} \
    {rtl/axi/src/axi_lite_mailbox.sv} \
    {rtl/axi/src/axi_lite_mux.sv} \
    {rtl/axi/src/axi_lite_regs.sv} \
    {rtl/axi/src/axi_lite_to_apb.sv} \
    {rtl/axi/src/axi_lite_to_axi.sv} \
    {rtl/axi/src/axi_modify_address.sv} \
    {rtl/axi/src/axi_mux.sv} \
    {rtl/axi/src/axi_rw_join.sv} \
    {rtl/axi/src/axi_rw_split.sv} \
    {rtl/axi/src/axi_serializer.sv} \
    {rtl/axi/src/axi_slave_compare.sv} \
    {rtl/axi/src/axi_throttle.sv} \
    {rtl/axi/src/axi_to_detailed_mem.sv} \
    {rtl/axi/src/axi_burst_splitter.sv} \
    {rtl/axi/src/axi_cdc.sv} \
    {rtl/axi/src/axi_demux.sv} \
    {rtl/axi/src/axi_err_slv.sv} \
    {rtl/axi/src/axi_dw_converter.sv} \
    {rtl/axi/src/axi_from_mem.sv} \
    {rtl/axi/src/axi_id_serialize.sv} \
    {rtl/axi/src/axi_lfsr.sv} \
    {rtl/axi/src/axi_multicut.sv} \
    {rtl/axi/src/axi_to_axi_lite.sv} \
    {rtl/axi/src/axi_to_mem.sv} \
    {rtl/axi/src/axi_zero_mem.sv} \
    {rtl/axi/src/axi_interleaved_xbar.sv} \
    {rtl/axi/src/axi_iw_converter.sv} \
    {rtl/axi/src/axi_lite_xbar.sv} \
    {rtl/axi/src/axi_xbar_unmuxed.sv} \
    {rtl/axi/src/axi_to_mem_banked.sv} \
    {rtl/axi/src/axi_to_mem_interleaved.sv} \
    {rtl/axi/src/axi_to_mem_split.sv} \
    {rtl/axi/src/axi_xbar.sv} \
    {rtl/axi/src/axi_xp.sv} \
    {rtl/fpnew/src/fpnew_pkg.sv} \
    {rtl/fpnew/src/fpnew_cast_multi.sv} \
    {rtl/fpnew/src/fpnew_classifier.sv} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v} \
    {rtl/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v} \
    {rtl/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v} \
    {rtl/fpnew/src/fpnew_divsqrt_th_32.sv} \
    {rtl/fpnew/src/fpnew_divsqrt_th_64_multi.sv} \
    {rtl/fpnew/src/fpnew_divsqrt_multi.sv} \
    {rtl/fpnew/src/fpnew_fma.sv} \
    {rtl/fpnew/src/fpnew_fma_multi.sv} \
    {rtl/fpnew/src/fpnew_sdotp_multi.sv} \
    {rtl/fpnew/src/fpnew_sdotp_multi_wrapper.sv} \
    {rtl/fpnew/src/fpnew_noncomp.sv} \
    {rtl/fpnew/src/fpnew_opgroup_block.sv} \
    {rtl/fpnew/src/fpnew_opgroup_fmt_slice.sv} \
    {rtl/fpnew/src/fpnew_opgroup_multifmt_slice.sv} \
    {rtl/fpnew/src/fpnew_rounding.sv} \
    {rtl/fpnew/src/lfsr_sr.sv} \
    {rtl/fpnew/src/fpnew_top.sv} \
    {rtl/cva6/core/include/config_pkg.sv} \
    {rtl/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv} \
    {rtl/cva6/core/include/riscv_pkg.sv} \
    {rtl/cva6/core/include/ariane_pkg.sv} \
    {rtl/cva6/core/include/build_config_pkg.sv} \
    {rtl/cva6/core/cva6_mmu/cva6_tlb.sv} \
    {rtl/cva6/core/cva6_mmu/cva6_shared_tlb.sv} \
    {rtl/cva6/core/cva6_mmu/cva6_mmu.sv} \
    {rtl/cva6/core/cva6_mmu/cva6_ptw.sv} \
    {rtl/cva6/core/include/wt_cache_pkg.sv} \
    {rtl/cva6/core/include/std_cache_pkg.sv} \
    {rtl/cva6/core/cvxif_example/include/cvxif_instr_pkg.sv} \
    {rtl/cva6/core/cvxif_fu.sv} \
    {rtl/cva6/core/cvxif_issue_register_commit_if_driver.sv} \
    {rtl/cva6/core/cvxif_compressed_if_driver.sv} \
    {rtl/cva6/core/cvxif_example/cvxif_example_coprocessor.sv} \
    {rtl/cva6/core/cvxif_example/instr_decoder.sv} \
    {rtl/cva6/core/cva6_rvfi_probes.sv} \
    {rtl/cva6/core/cva6_fifo_v3.sv} \
    {rtl/cva6/core/cva6.sv} \
    {rtl/cva6/core/alu.sv} \
    {rtl/cva6/core/fpu_wrap.sv} \
    {rtl/cva6/core/branch_unit.sv} \
    {rtl/cva6/core/compressed_decoder.sv} \
    {rtl/cva6/core/controller.sv} \
    {rtl/cva6/core/csr_buffer.sv} \
    {rtl/cva6/core/csr_regfile.sv} \
    {rtl/cva6/core/decoder.sv} \
    {rtl/cva6/core/ex_stage.sv} \
    {rtl/cva6/core/acc_dispatcher.sv} \
    {rtl/cva6/core/instr_realign.sv} \
    {rtl/cva6/core/macro_decoder.sv} \
    {rtl/cva6/core/id_stage.sv} \
    {rtl/cva6/core/issue_read_operands.sv} \
    {rtl/cva6/core/issue_stage.sv} \
    {rtl/cva6/core/load_unit.sv} \
    {rtl/cva6/core/load_store_unit.sv} \
    {rtl/cva6/core/lsu_bypass.sv} \
    {rtl/cva6/core/mult.sv} \
    {rtl/cva6/core/multiplier.sv} \
    {rtl/cva6/core/serdiv.sv} \
    {rtl/cva6/core/perf_counters.sv} \
    {rtl/cva6/core/ariane_regfile_ff.sv} \
    {rtl/cva6/core/ariane_regfile_fpga.sv} \
    {rtl/cva6/core/scoreboard.sv} \
    {rtl/cva6/core/raw_checker.sv} \
    {rtl/cva6/core/store_buffer.sv} \
    {rtl/cva6/core/amo_buffer.sv} \
    {rtl/cva6/core/store_unit.sv} \
    {rtl/cva6/core/commit_stage.sv} \
    {rtl/cva6/core/axi_shim.sv} \
    {rtl/cva6/core/frontend/btb.sv} \
    {rtl/cva6/core/frontend/bht.sv} \
    {rtl/cva6/core/frontend/bht2lvl.sv} \
    {rtl/cva6/core/frontend/ras.sv} \
    {rtl/cva6/core/frontend/instr_scan.sv} \
    {rtl/cva6/core/frontend/instr_queue.sv} \
    {rtl/cva6/core/frontend/frontend.sv} \
    {rtl/cva6/core/cache_subsystem/wt_dcache_ctrl.sv} \
    {rtl/cva6/core/cache_subsystem/wt_dcache_mem.sv} \
    {rtl/cva6/core/cache_subsystem/wt_dcache_missunit.sv} \
    {rtl/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv} \
    {rtl/cva6/core/cache_subsystem/wt_dcache.sv} \
    {rtl/cva6/core/cache_subsystem/wt_cache_subsystem.sv} \
    {rtl/cva6/core/cache_subsystem/wt_axi_adapter.sv} \
    {rtl/cva6/core/cache_subsystem/cva6_icache.sv} \
    {rtl/cva6/core/cache_subsystem/tag_cmp.sv} \
    {rtl/cva6/core/cache_subsystem/cache_ctrl.sv} \
    {rtl/cva6/core/cache_subsystem/amo_alu.sv} \
    {rtl/cva6/core/cache_subsystem/axi_adapter.sv} \
    {rtl/cva6/core/cache_subsystem/miss_handler.sv} \
    {rtl/cva6/core/cache_subsystem/std_nbdcache.sv} \
    {rtl/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv} \
    {rtl/cva6/core/cache_subsystem/std_cache_subsystem.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg_initialized.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv} \
    {rtl/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv} \
    {rtl/cva6/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv} \
    {rtl/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv} \
    {rtl/cva6/core/cache_subsystem/cva6_hpdcache_wrapper.sv} \
    {rtl/cva6/core/cache_subsystem/hpdcache_tc_sram.sv} \
    {rtl/cva6/core/pmp/src/pmp.sv} \
    {rtl/cva6/core/pmp/src/pmp_entry.sv} \
    {rtl/cva6/core/pmp/src/pmp_data_if.sv} \
    {rtl/cva6/vendor/pulp-platform/fpga-support/fpga-support-stubs.sv} \
    {rtl/cva6/common/local/util/tc_sram_wrapper.sv} \
    {rtl/cva6/common/local/util/tc_sram_wrapper_cache_techno.sv} \
    {rtl/cva6/common/local/util/sram_cache.sv} \
    {rtl/cva6/common/local/util/sram_pulp.sv} \
    {rtl/register_interface/src/reg_intf.sv} \
    {rtl/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv} \
    {rtl/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv} \
    {rtl/register_interface/src/apb_to_reg.sv} \
    {rtl/register_interface/src/axi_lite_to_reg.sv} \
    {rtl/register_interface/src/axi_to_reg_v2.sv} \
    {rtl/register_interface/src/periph_to_reg.sv} \
    {rtl/register_interface/src/reg_cdc.sv} \
    {rtl/register_interface/src/reg_cut.sv} \
    {rtl/register_interface/src/reg_demux.sv} \
    {rtl/register_interface/src/reg_err_slv.sv} \
    {rtl/register_interface/src/reg_filter_empty_writes.sv} \
    {rtl/register_interface/src/reg_mux.sv} \
    {rtl/register_interface/src/reg_to_apb.sv} \
    {rtl/register_interface/src/reg_to_mem.sv} \
    {rtl/register_interface/src/reg_to_tlul.sv} \
    {rtl/register_interface/src/reg_to_axi.sv} \
    {rtl/register_interface/src/reg_uniform.sv} \
    {rtl/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_shadow.sv} \
    {rtl/register_interface/vendor/lowrisc_opentitan/src/prim_subreg.sv} \
    {rtl/register_interface/src/deprecated/axi_to_reg.sv} \
    {rtl/apb_uart/src/slib_clock_div.sv} \
    {rtl/apb_uart/src/slib_counter.sv} \
    {rtl/apb_uart/src/slib_edge_detect.sv} \
    {rtl/apb_uart/src/slib_fifo.sv} \
    {rtl/apb_uart/src/slib_input_filter.sv} \
    {rtl/apb_uart/src/slib_input_sync.sv} \
    {rtl/apb_uart/src/slib_mv_filter.sv} \
    {rtl/apb_uart/src/uart_baudgen.sv} \
    {rtl/apb_uart/src/uart_interrupt.sv} \
    {rtl/apb_uart/src/uart_receiver.sv} \
    {rtl/apb_uart/src/uart_transmitter.sv} \
    {rtl/apb_uart/src/apb_uart.sv} \
    {rtl/apb_uart/src/apb_uart_wrap.sv} \
    {rtl/apb_uart/src/reg_uart_wrap.sv} \
    {rtl/ara/hardware/include/rvv_pkg.sv} \
    {rtl/ara/hardware/include/qbs_pkg.sv} \
    {rtl/ara/hardware/include/akv_pkg.sv} \
    {rtl/ara/hardware/include/ara_pkg.sv} \
    {rtl/ara/hardware/src/common_cells_compat/fall_through_register_v1.sv} \
    {rtl/ara/hardware/src/segment_sequencer.sv} \
    {rtl/ara/hardware/src/ctrl_registers.sv} \
    {rtl/ara/hardware/src/cva6_accel_first_pass_decoder.sv} \
    {rtl/ara/hardware/src/ara_dispatcher.sv} \
    {rtl/ara/hardware/src/ara_sequencer.sv} \
    {rtl/ara/hardware/src/axi_inval_filter.sv} \
    {rtl/ara/hardware/src/lane/lane_sequencer.sv} \
    {rtl/ara/hardware/src/lane/operand_queue.sv} \
    {rtl/ara/hardware/src/lane/operand_requester.sv} \
    {rtl/ara/hardware/src/lane/simd_alu.sv} \
    {rtl/ara/hardware/src/lane/simd_div.sv} \
    {rtl/ara/hardware/src/lane/simd_mul.sv} \
    {rtl/ara/hardware/src/lane/vector_regfile.sv} \
    {rtl/ara/hardware/src/lane/power_gating_generic.sv} \
    {rtl/ara/hardware/src/masku/masku_operands.sv} \
    {rtl/ara/hardware/src/sldu/p2_stride_gen.sv} \
    {rtl/ara/hardware/src/sldu/sldu_op_dp.sv} \
    {rtl/ara/hardware/src/sldu/sldu.sv} \
    {rtl/ara/hardware/src/vlsu/addrgen.sv} \
    {rtl/ara/hardware/src/vlsu/vldu.sv} \
    {rtl/ara/hardware/src/vlsu/vstu.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_profile_decoder.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_dot_array.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_descriptor_decoder.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_read_engine.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_activation_context.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_payload_sram.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_payload_buffer.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_block_adapter.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_profile_engine_int.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_fp_accumulator.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_compute_engine.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_commit.sv} \
    {rtl/ara/hardware/src/vlsu/qbs/qbs_engine.sv} \
    {rtl/ara/hardware/src/vlsu/akv/akv_context.sv} \
    {rtl/ara/hardware/src/vlsu/akv/akv_v2_context.sv} \
    {rtl/ara/hardware/src/vlsu/akv/akv_engine.sv} \
    {rtl/ara/hardware/src/lane/operand_queues_stage.sv} \
    {rtl/ara/hardware/src/lane/valu.sv} \
    {rtl/ara/hardware/src/lane/vmfpu.sv} \
    {rtl/ara/hardware/src/lane/fixed_p_rounding.sv} \
    {rtl/ara/hardware/src/vlsu/vlsu.sv} \
    {rtl/ara/hardware/src/masku/masku.sv} \
    {rtl/ara/hardware/src/lane/vector_fus_stage.sv} \
    {rtl/ara/hardware/src/lane/lane.sv} \
    {rtl/ara/hardware/src/ara.sv} \
    {rtl/axi_llc/src/axi_llc_pkg.sv} \
    {rtl/axi_llc/src/axi_llc_burst_cutter.sv} \
    {rtl/axi_llc/src/axi_llc_data_way.sv} \
    {rtl/axi_llc/src/axi_llc_merge_unit.sv} \
    {rtl/axi_llc/src/axi_llc_read_unit.sv} \
    {rtl/axi_llc/src/axi_llc_reg_pkg.sv} \
    {rtl/axi_llc/src/axi_llc_reg_top.sv} \
    {rtl/axi_llc/src/axi_llc_write_unit.sv} \
    {rtl/axi_llc/src/eviction_refill/axi_llc_ax_master.sv} \
    {rtl/axi_llc/src/eviction_refill/axi_llc_r_master.sv} \
    {rtl/axi_llc/src/eviction_refill/axi_llc_w_master.sv} \
    {rtl/axi_llc/src/hit_miss_detect/axi_llc_evict_box.sv} \
    {rtl/axi_llc/src/hit_miss_detect/axi_llc_lock_box_bloom.sv} \
    {rtl/axi_llc/src/hit_miss_detect/axi_llc_miss_counters.sv} \
    {rtl/axi_llc/src/hit_miss_detect/axi_llc_tag_pattern_gen.sv} \
    {rtl/axi_llc/src/axi_llc_chan_splitter.sv} \
    {rtl/axi_llc/src/axi_llc_evict_unit.sv} \
    {rtl/axi_llc/src/axi_llc_refill_unit.sv} \
    {rtl/axi_llc/src/axi_llc_ways.sv} \
    {rtl/axi_llc/src/hit_miss_detect/axi_llc_tag_store.sv} \
    {rtl/axi_llc/src/axi_llc_config.sv} \
    {rtl/axi_llc/src/axi_llc_hit_miss.sv} \
    {rtl/axi_llc/src/axi_llc_top.sv} \
    {rtl/axi_llc/src/axi_llc_reg_wrap.sv} \
    {rtl/axi_riscv_atomics/src/axi_res_tbl.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_amos_alu.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_amos.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_lrsc.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_atomics.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_lrsc_wrap.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_amos_wrap.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv} \
    {rtl/axi_riscv_atomics/src/axi_riscv_atomics_structs.sv} \
    {rtl/axi_rt/src/regs/axi_rt_reg_pkg.sv} \
    {rtl/axi_rt/src/axi_gran_burst_splitter_counters.sv} \
    {rtl/axi_rt/src/axi_rt_unit_counter.sv} \
    {rtl/axi_rt/src/axi_rt_err_slv.sv} \
    {rtl/axi_rt/src/axi_rt_regbus_guard.sv} \
    {rtl/axi_rt/src/regs/axi_rt_reg_top.sv} \
    {rtl/axi_rt/src/axi_gran_burst_splitter_ax_chan.sv} \
    {rtl/axi_rt/src/axi_gran_burst_splitter.sv} \
    {rtl/axi_rt/src/axi_write_buffer.sv} \
    {rtl/axi_rt/src/axi_rt_unit.sv} \
    {rtl/axi_rt/src/axi_rt_unit_top.sv} \
    {rtl/axi_rt/src/axi_rt_unit_top_synth.sv} \
    {rtl/axi_rt/target/xilinx/src/axi_rt_unit_top_xilinx.sv} \
    {rtl/axi_rt/target/xilinx/src/axi_rt_unit_top_xilinx_ip.v} \
    {rtl/axi_vga/src/axi_vga_reg_pkg.sv} \
    {rtl/axi_vga/src/axi_vga_reg_top.sv} \
    {rtl/axi_vga/src/axi_vga_timing_fsm.sv} \
    {rtl/axi_vga/src/axi_vga_fetcher.sv} \
    {rtl/axi_vga/src/axi_vga.sv} \
    {rtl/clic/src/clicint_reg_pkg.sv} \
    {rtl/clic/src/clicint_reg_top.sv} \
    {rtl/clic/src/mclic_reg_pkg.sv} \
    {rtl/clic/src/mclic_reg_top.sv} \
    {rtl/clic/src/clic_reg_adapter.sv} \
    {rtl/clic/src/clic_gateway.sv} \
    {rtl/clic/src/clic_target.sv} \
    {rtl/clic/src/clic_apb.sv} \
    {rtl/clic/src/clic.sv} \
    {rtl/clint/src/clint_reg_pkg.sv} \
    {rtl/clint/src/clint_reg_top.sv} \
    {rtl/clint/src/clint.sv} \
    {rtl/idma/src/frontends/idma_transfer_id_gen.sv} \
    {rtl/idma/src/idma_pkg.sv} \
    {rtl/idma/src/idma_stream_fifo.sv} \
    {rtl/idma/src/idma_buffer.sv} \
    {rtl/idma/src/idma_error_handler.sv} \
    {rtl/idma/src/idma_channel_coupler.sv} \
    {rtl/idma/src/idma_axi_transport_layer.sv} \
    {rtl/idma/src/idma_axi_lite_transport_layer.sv} \
    {rtl/idma/src/idma_obi_transport_layer.sv} \
    {rtl/idma/src/idma_legalizer.sv} \
    {rtl/idma/src/idma_backend.sv} \
    {rtl/idma/src/legacy/axi_dma_backend.sv} \
    {rtl/idma/src/legacy/midends/idma_2D_midend.sv} \
    {rtl/idma/src/midends/idma_nd_midend.sv} \
    {rtl/idma/src/frontends/register_32bit_2d/idma_reg32_2d_frontend_reg_pkg.sv} \
    {rtl/idma/src/frontends/register_32bit_2d/idma_reg32_2d_frontend_reg_top.sv} \
    {rtl/idma/src/frontends/register_32bit_2d/idma_reg32_2d_frontend.sv} \
    {rtl/idma/src/frontends/register_64bit/idma_reg64_frontend_reg_pkg.sv} \
    {rtl/idma/src/frontends/register_64bit/idma_reg64_frontend_reg_top.sv} \
    {rtl/idma/src/frontends/register_64bit/idma_reg64_frontend.sv} \
    {rtl/idma/src/frontends/register_64bit_2d/idma_reg64_2d_frontend_reg_pkg.sv} \
    {rtl/idma/src/frontends/register_64bit_2d/idma_reg64_2d_frontend_reg_top.sv} \
    {rtl/idma/src/frontends/register_64bit_2d/idma_reg64_2d_frontend.sv} \
    {rtl/idma/src/frontends/desc64/idma_desc64_reg_pkg.sv} \
    {rtl/idma/src/frontends/desc64/idma_desc64_reg_top.sv} \
    {rtl/idma/src/frontends/desc64/idma_desc64_shared_counter.sv} \
    {rtl/idma/src/frontends/desc64/idma_desc64_reg_wrapper.sv} \
    {rtl/idma/src/frontends/desc64/idma_desc64_top.sv} \
    {rtl/idma/src/synth_wrapper/idma_backend_synth.sv} \
    {rtl/idma/src/synth_wrapper/idma_lite_backend_synth.sv} \
    {rtl/idma/src/synth_wrapper/idma_obi_backend_synth.sv} \
    {rtl/idma/src/synth_wrapper/idma_nd_backend_synth.sv} \
    {rtl/irq_router/rtl/irq_router_reg_pkg.sv} \
    {rtl/irq_router/rtl/irq_router_reg_top.sv} \
    {rtl/irq_router/rtl/irq_router.sv} \
    {rtl/opentitan_peripherals/src/prim/prim_pulp_platform/prim_flop_2sync.sv} \
    {rtl/opentitan_peripherals/src/prim/prim_pulp_platform/prim_flop_en.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_fifo_sync_cnt.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_util_pkg.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_max_tree.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_sync_reqack.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_sync_reqack_data.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_pulse_sync.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_packer_fifo.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_fifo_sync.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_filter_ctr.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_intr_hw.sv} \
    {rtl/opentitan_peripherals/src/prim/rtl/prim_fifo_async.sv} \
    {rtl/opentitan_peripherals/src/gpio/rtl/gpio_reg_pkg.sv} \
    {rtl/opentitan_peripherals/src/i2c/rtl/i2c_reg_pkg.sv} \
    {rtl/opentitan_peripherals/src/rv_plic/rtl/rv_plic_reg_pkg.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_reg_pkg.sv} \
    {rtl/opentitan_peripherals/src/gpio/rtl/gpio_reg_top.sv} \
    {rtl/opentitan_peripherals/src/i2c/rtl/i2c_reg_top.sv} \
    {rtl/opentitan_peripherals/src/rv_plic/rtl/rv_plic_reg_top.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_reg_top.sv} \
    {rtl/opentitan_peripherals/src/i2c/rtl/i2c_pkg.sv} \
    {rtl/opentitan_peripherals/src/i2c/rtl/i2c_fsm.sv} \
    {rtl/opentitan_peripherals/src/rv_plic/rtl/rv_plic_gateway.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_byte_merge.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_byte_select.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_cmd_pkg.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_command_queue.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_fsm.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_window.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_data_fifos.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_shift_register.sv} \
    {rtl/opentitan_peripherals/src/i2c/rtl/i2c_core.sv} \
    {rtl/opentitan_peripherals/src/rv_plic/rtl/rv_plic_target.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host_core.sv} \
    {rtl/opentitan_peripherals/src/gpio/rtl/gpio.sv} \
    {rtl/opentitan_peripherals/src/i2c/rtl/i2c.sv} \
    {rtl/opentitan_peripherals/src/spi_host/rtl/spi_host.sv} \
    {rtl/opentitan_peripherals/src/rv_plic/rtl/rv_plic.sv} \
    {rtl/riscv-dbg/src/dm_pkg.sv} \
    {rtl/riscv-dbg/debug_rom/debug_rom.sv} \
    {rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv} \
    {rtl/riscv-dbg/src/dm_csrs.sv} \
    {rtl/riscv-dbg/src/dm_mem.sv} \
    {rtl/riscv-dbg/src/dmi_cdc.sv} \
    {rtl/riscv-dbg/src/dmi_jtag_tap.sv} \
    {rtl/riscv-dbg/src/dm_sba.sv} \
    {rtl/riscv-dbg/src/dm_top.sv} \
    {rtl/riscv-dbg/src/dmi_jtag.sv} \
    {rtl/riscv-dbg/src/dm_obi_top.sv} \
    {rtl/serial_link/src/regs/serial_link_reg_pkg.sv} \
    {rtl/serial_link/src/regs/serial_link_reg_top.sv} \
    {rtl/serial_link/src/regs/serial_link_single_channel_reg_pkg.sv} \
    {rtl/serial_link/src/regs/serial_link_single_channel_reg_top.sv} \
    {rtl/serial_link/src/serial_link_pkg.sv} \
    {rtl/serial_link/src/channel_allocator/stream_chopper.sv} \
    {rtl/serial_link/src/channel_allocator/stream_dechopper.sv} \
    {rtl/serial_link/src/channel_allocator/channel_despread_sfr.sv} \
    {rtl/serial_link/src/channel_allocator/channel_spread_sfr.sv} \
    {rtl/serial_link/src/channel_allocator/serial_link_channel_allocator.sv} \
    {rtl/serial_link/src/serial_link_network.sv} \
    {rtl/serial_link/src/serial_link_data_link.sv} \
    {rtl/serial_link/src/serial_link_physical.sv} \
    {rtl/serial_link/src/serial_link.sv} \
    {rtl/serial_link/src/serial_link_occamy_wrapper.sv} \
    {rtl/serial_link/src/serial_link_synth_wrapper.sv} \
    {rtl/unbent/src/bus_err_unit_bare.sv} \
    {rtl/unbent/src/bus_err_unit_reg_pkg.sv} \
    {rtl/unbent/src/bus_err_unit_reg_top.sv} \
    {rtl/unbent/src/bus_err_unit.sv} \
    {rtl/unbent/src/axi_err_unit_wrap.sv} \
    {rtl/unbent/src/obi_err_unit_wrap.sv} \
    {rtl/cheshire/hw/future/UsbOhciAxi4.v} \
    {rtl/cheshire/hw/future/spinal_usb_ohci.sv} \
    {rtl/cheshire/hw/bootrom/cheshire_bootrom.sv} \
    {rtl/cheshire/hw/regs/cheshire_reg_pkg.sv} \
    {rtl/cheshire/hw/regs/cheshire_reg_top.sv} \
    {rtl/cheshire/hw/cheshire_pkg.sv} \
    {rtl/cheshire/hw/cheshire_soc.sv} \
    {rtl/board/dram_wrapper_xilinx.sv} \
    {rtl/board/ara_dsa_vcu118.sv} \
    {rtl/board/ara_axi_observer.sv} \
    {rtl/board/ara_ddr_router.sv} \
    {rtl/board/ara_fpga_debug.sv} \
    {rtl/board/ara_host_bridge.sv}]
set rtl_include_dirs [list {rtl/common_cells/include} \
    {rtl/apb/include} \
    {rtl/axi/include} \
    {rtl/cva6/core/include} \
    {rtl/cva6/common/local/util} \
    {rtl/cva6/core/cache_subsystem/hpdcache/rtl/include} \
    {rtl/register_interface/include} \
    {rtl/ara/hardware/include} \
    {rtl/axi_llc/include} \
    {rtl/axi_rt/include} \
    {rtl/idma/src/include} \
    {rtl/serial_link/src/axis/include} \
    {rtl/cheshire/hw/include} \
    {rtl/board}]
set rtl_defines [list {TARGET_CV64A6_IMAFDCV_SV39} \
    {TARGET_EXCLUDE_FIRST_PASS_DECODER} \
    {TARGET_FPGA} \
    {TARGET_RTL} \
    {TARGET_SYNTHESIS} \
    {TARGET_VCU118} \
    {TARGET_VIVADO} \
    {TARGET_XILINX} \
    {ARA} \
    {NR_LANES=4} \
    {VLEN=1024} \
    {ARA_QBS_ENABLE=1} \
    {ARA_AKV_ENABLE=1} \
    {ARA_AKV_V2_ENABLE=1}]
