#!/usr/bin/env bash
# ============================================================================
# Unified HDV kernel sweep.
#
#   ./kernel_sweep.sh [--skip-long] [all|onepoint|point|1d|kernel|blas|blas_dim|blas_pf|blas_groups|vsgemm|fixed|long] [args]
#
# Options:
#   --skip-long     skip sweep points historically taking more than 10 minutes
#   --append        preserve existing kernel_sweep_out files before running
#
# Ablation:
#   HDV_ABLATION=full|base|vdu|ovlp|pf|pf_only|haz|pf_haz
#
# Everything is implemented here.  The old split sweep scripts are no longer
# called by this top-level flow.  All generated CSVs and logs go under:
#
#   hardware/kernel_sweep_out/
#
# Output files:
#   summary.txt          terminal transcript of this sweep run
#   kernel_all.csv       log-derived CSV generated by kernel_sweep_sum.sh
#   <kernel>.csv         per-kernel/per-variant CSVs
#   *.log                build/simulation logs
#
# fdotp and vspf are excluded from active testing.
# ============================================================================
set -uo pipefail
cd "$(dirname "$0")"

APPS=../apps
WD=400000
HDV_ABLATION="${HDV_ABLATION:-full}"
case "$HDV_ABLATION" in
  full|base|vdu|ovlp|pf|pf_only|haz|pf_haz) ;;
  *)
    echo "ERROR: invalid HDV_ABLATION=$HDV_ABLATION (use full|base|vdu|ovlp|pf|pf_only|haz|pf_haz)" >&2
    exit 2
    ;;
esac
export hdv_ablation="$HDV_ABLATION"

if [ -n "${KERNEL_SWEEP_OUT:-}" ]; then
  OUT="$KERNEL_SWEEP_OUT"
elif [ "$HDV_ABLATION" = "full" ]; then
  OUT=kernel_sweep_out
else
  OUT="kernel_sweep_out_${HDV_ABLATION}"
fi

usage() {
  echo "usage: $0 [--skip-long] [--append] {all|onepoint|point|1d|kernel|blas|blas_dim|blas_pf|blas_groups|vsgemm|fixed|long} [args]"
  echo "       HDV_ABLATION=base|vdu|ovlp|pf|full $0 --skip-long all"
  echo "       HDV_ABLATION=pf_only|haz|pf_haz $0 point vsaxpy_hdv 1024"
  echo "       KERNEL_SWEEP_OUT=my_out HDV_ABLATION=base $0 point vsaxpy_hdv 4096"
  echo "       KERNEL_SWEEP_SKIP_LONG=1 $0 all"
  echo "       $0 point vvaddint32_hdv 2048"
  echo "       $0 point lavamd_fix"
  echo "       $0 point vsgemm_m4_1r 128"
  echo "       $0 point vssyrk_hdv 128"
  echo "       $0 point vstrsm_hdv_m8 64"
  echo "       $0 point vsgemv_hdv_m4 128 8"
  echo "       $0 point vssymv_hdv_m4 128 8"
  echo "       $0 blas_groups \"128\" \"2 4 8\" \"4\""
  echo "       $0 long"
}

SKIP_LONG="${KERNEL_SWEEP_SKIP_LONG:-0}"
APPEND_OUT=0
POSITIONAL=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --skip-long|--fast)
      SKIP_LONG=1
      shift
      ;;
    --no-skip-long)
      SKIP_LONG=0
      shift
      ;;
    --append|--keep-out)
      APPEND_OUT=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done
set -- "${POSITIONAL[@]}"

MODE="${1:-all}"
ARG1="${2:-}"
ARG2="${3:-}"
ARG3="${4:-}"
ARG4="${5:-}"
if [ "$MODE" = "long" ] || [ "$MODE" = "point" ]; then
  APPEND_OUT=1
fi

mkdir -p "$OUT"
if [ "${KERNEL_SWEEP_LOCK_HELD:-0}" != "1" ]; then
  LOCK_NAME="${PWD//\//_}_${OUT//\//_}"
  exec 9>"/tmp/ara_hdv_kernel_sweep_${LOCK_NAME}.lock"
  if ! flock -n 9; then
    echo "[lock] another kernel sweep/sum is using $OUT; waiting..."
    flock 9
  fi
  export KERNEL_SWEEP_LOCK_HELD=1
fi
SUMMARY="$OUT/summary.txt"
if [ "$APPEND_OUT" = "1" ]; then
  touch "$SUMMARY"
else
  : > "$SUMMARY"
fi

# Keep summary.txt identical to the sweep's terminal transcript from this point
# onward.  Build and simulation details remain in their dedicated *.log files
# because those commands are explicitly redirected below.
exec > >(tee -a "$SUMMARY") 2>&1

if [ "$SKIP_LONG" = "1" ]; then
  echo "[skip-long] enabled: known >10min sweep points will be skipped"
fi
if [ "$HDV_ABLATION" != "full" ]; then
  echo "[ablation] mode=$HDV_ABLATION out=$OUT"
fi
if [ "$MODE" = "long" ]; then
  echo "[long] enabled: only known >10min sweep points will be run; existing output is preserved"
fi

log=""
kv() { grep -hE "$1" "$log" 2>/dev/null | grep -oE "$2[[:space:]]*=[[:space:]]*[0-9]+" | head -1 | grep -oE '[0-9]+$'; }
d()  { grep -hE "$1" "$log" 2>/dev/null | grep -oE "$2=[0-9]+" | head -1 | grep -oE '[0-9]+'; }

addr_of() {
  local hex
  hex=$(grep -E "[0-9a-f]+ [A-Za-z] $2\$" "$APPS/$1/$1.dump" 2>/dev/null | head -1 | awk '{print $1}')
  [ -z "$hex" ] && { echo ""; return 1; }
  printf '%d' "0x$hex"
}

one_d_ptr_plusargs() {
  local k=$1 s1 s2

  case "$k" in
    vstencil3_hdv)
      s1=$(addr_of "$k" src1)
      s2=$(addr_of "$k" src2)
      [ -n "$s1" ] && [ -n "$s2" ] && printf '+HDV_A1=%d +HDV_A2=%d ' "$((s1 + 4))" "$s2"
      ;;
    vfir5_hdv)
      s1=$(addr_of "$k" src1)
      s2=$(addr_of "$k" src2)
      [ -n "$s1" ] && [ -n "$s2" ] && printf '+HDV_A1=%d +HDV_A2=%d ' "$s1" "$s2"
      ;;
  esac
}

note() {
  echo "$*"
}

skip_long_note() {
  note "[skip-long] $*"
}

KERNEL_H_ID="group,kernel,tag,avl,size,rows,n,result,task_cycles,cyc_per_elem,cyc_per_macc,wall_cycles,eps,vec_busy,imem_outstanding"
KERNEL_H_HDV="ep_ack,ep_vset_ack,vq_push,vq_pop,vq_max_occ,vq_bypass,vq_full_stall,dispatch_slots,dispatch_cycles,fsm_could_bypass,operand_wait_cycles_raw,ara_backpressure_cycles,real_wait_stall,resp_meta_stall,resp_meta_max"
KERNEL_H_HEU_EP="ep_count,packed_inst_count,packed_scalar_inst_count,packed_vector_inst_count,ep_width_sum,ep_width_gt1_count,ep_scalar_vector_count,used_issue_slots,available_issue_slots,heu_to_current,heu_to_buffer,heu_scalar_only,heu_vector_only,heu_pf_hint_ep,heu_pf_disable_ep,heu_pf_mode_1x,heu_pf_mode_2x,heu_pf_mode_4x,heu_pf_mode_8x"
KERNEL_H_HEU_FE="heu_valid_cyc,heu_ready_block_cyc,heu_block_buffer_cyc,heu_block_branch_cyc,heu_current_busy_cyc,heu_buffer_valid_cyc,heu_scalar_out_cyc,heu_vector_out_cyc"
KERNEL_H_HEU_OVLP="early_issue_attempts,early_issue_grants,early_issue_blocked_by_dispatch,early_issue_blocked_by_queue,early_issue_blocked_by_branch,early_issue_blocked_by_scalar_mem,early_issue_blocked_by_dependency,early_issue_blocked_by_gpr_dependency,early_issue_blocked_by_fpr_dependency,early_issue_blocked_by_vector_dependency,cross_ep_inflight_cycles,overlap_cycles"
KERNEL_H_VDU_CMD="vector_cmd_valid_cycles,vector_cmd_fire_count,vector_cmd_blocked_cycles,cmd_window_avg_occ,cmd_window_sum_occ,cmd_window_sample_cycles,cmd_window_max_occ,cmd_window_full_cycles,cmd_window_empty_cycles,vq_avg_occ,vq_empty_cycles,vq_full_cycles,resp_meta_sum_occ,resp_meta_sample_cycles"
KERNEL_H_VDU_OPERAND="scalar_operand_capture_count,scalar_operand_bypass_hit,scalar_operand_wait_cycles,vset_visible_wait_cycles,scalar_operand_bypass,scalar_operand_lookahead_req,scalar_operand_lookahead_hit,scalar_operand_port_busy,vector_ep_enqueue,vector_ep_pending_enqueue,vector_ep_ready_block"
KERNEL_H_IPU="ipu_ready_cyc,ipu_ready_stall,ipu_sram_stall,ipu_serve_cyc,packets,bypass_hits,demand_reads,avg_cyc_per_pkt"
KERNEL_H_AG="demand_ar,pf_ar,pf_hit,loads,pf_en_cyc,demand_aw,demand_B,pf_B"
KERNEL_H_AGPF="pf_ar_rob_full,pf_ar_lkup_full,pf_ar_pending,pf_ar_dis,pf_2nd,dem_rob_block,pf_disabled,pf_page_cross,pf_queue_full,pf_avl_low"
KERNEL_H_AGPF2="pf_throttled_cycles,pf_late,pf_unused,pf_wait_match_cyc,pf_wait_match_evt,pf_queue_valid_cyc,pf_queue_block_cyc,pf_lkup_full_cyc,pf_rob_full_cyc,pf_pending_cyc,pf_stream_break,pf_future_keep,pf_queue_match_cyc,pf_rob_match_cyc,pf_page_wait_cyc"
KERNEL_H_SEQ="seq_issue,seq_blocked_cycles,seq_raw_cycles,seq_war_cycles,seq_waw_cycles,seq_waw_block,seq_ep_bypass,seq_full"
KERNEL_H_SEQHDV="hazard_check_count,same_ep_hazard_candidate,hazard_pruned_by_ep,seq_true_hazard_stall,seq_false_hazard_stall,seq_queue_full_stall,seq_lane_desync_stall,seq_operand_req_stall,seq_wait_state_cyc,seq_mem_wait_cyc"
KERNEL_H_DERIV="pf_hit_rate"
KERNEL_ROWHDR="$KERNEL_H_ID,$KERNEL_H_HDV,$KERNEL_H_HEU_EP,$KERNEL_H_HEU_FE,$KERNEL_H_HEU_OVLP,$KERNEL_H_VDU_CMD,$KERNEL_H_VDU_OPERAND,$KERNEL_H_IPU,$KERNEL_H_AG,$KERNEL_H_AGPF,$KERNEL_H_AGPF2,$KERNEL_H_SEQ,$KERNEL_H_SEQHDV,$KERNEL_H_DERIV"

write_kernel_csv_row() {
  local group=$1 kernel=$2 tag=$3 avl=$4 size=$5 rows=$6 n=$7 elem_work=$8 macc_work=$9 csv=${10}

  local r tc wc eps vbusy imem cpe cpm
  r=$(grep -E 'mock host' "$log" | head -1 | grep -oE 'PASSED|FAILED'); [ -z "$r" ] && r="ERR"
  tc=$(kv 'mock host' 'total_task_cycles')
  wc=$(d 'HDV-CSR.*DONE' 'wall_cycle')
  eps=$(d 'HDV-CSR.*DONE' 'accepted'); [ -z "$eps" ] && eps=$(grep -E 'mock host' "$log" | grep -oE 'got [0-9]+' | grep -oE '[0-9]+')
  vbusy=$(d 'HDV-CSR.*DONE' 'vec_busy')
  imem=$(d 'HDV-CSR.*DONE' 'imem_outstanding')
  cpe=""; [ -n "$tc" ] && [ "${elem_work:-0}" -gt 0 ] 2>/dev/null && cpe=$(echo "scale=3; $tc/$elem_work" | bc)
  cpm=""; [ -n "$tc" ] && [ "${macc_work:-0}" -gt 0 ] 2>/dev/null && cpm=$(echo "scale=4; $tc/$macc_work" | bc)

  local ep_ack ep_vack vqpush vqpop vqmax vqbyp vqfs dslots dcyc fbyp owc abp rwfs rmfs rmmax
  ep_ack=$(kv 'HDV-PERF' 'ep_acknowledged'); ep_vack=$(kv 'HDV-PERF' 'ep_vset_acknowledged')
  vqpush=$(kv 'HDV-PERF' 'vq_push'); vqpop=$(kv 'HDV-PERF' 'vq_pop')
  vqmax=$(kv 'HDV-PERF' 'vq_max_occupancy'); vqbyp=$(kv 'HDV-PERF' 'vq_bypass')
  vqfs=$(kv 'HDV-PERF' 'vq_full_stall')
  dslots=$(kv 'HDV-PERF' 'dispatch_slots'); dcyc=$(kv 'HDV-PERF' 'dispatch_total_cycles')
  fbyp=$(kv 'HDV-PERF' 'fsm_could_bypass'); owc=$(kv 'HDV-PERF' 'operand_wait_cycles')
  abp=$(kv 'HDV-PERF' 'ara_backpressure'); rwfs=$(kv 'HDV-PERF' 'real_wait_full_stall')
  rmfs=$(kv 'HDV-PERF' 'resp_meta_full_stall'); rmmax=$(kv 'HDV-PERF' 'resp_meta_max')

  local hacc hcur hbuf hws hsc hvc hwgt hm hso hvo his hpfh hpfd hpf1 hpf2 hpf4 hpf8
  hacc=$(kv 'PERF-HEU-EP' 'accept'); hcur=$(kv 'PERF-HEU-EP' 'to_current')
  hbuf=$(kv 'PERF-HEU-EP' 'to_buffer'); hws=$(kv 'PERF-HEU-EP' 'width_sum')
  hsc=$(kv 'PERF-HEU-EP' 'scalar_inst'); hvc=$(kv 'PERF-HEU-EP' 'vector_inst')
  hwgt=$(kv 'PERF-HEU-EP' 'width_gt1'); hm=$(kv 'PERF-HEU-EP' 'mixed')
  hso=$(kv 'PERF-HEU-EP' 'scalar_only'); hvo=$(kv 'PERF-HEU-EP' 'vector_only')
  his=$(kv 'PERF-HEU-EP' 'issue_slots'); hpfh=$(kv 'PERF-HEU-EP' 'pf_hint_ep')
  hpfd=$(kv 'PERF-HEU-EP' 'pf_disable_ep'); hpf1=$(kv 'PERF-HEU-EP' 'pf_mode_1x')
  hpf2=$(kv 'PERF-HEU-EP' 'pf_mode_2x'); hpf4=$(kv 'PERF-HEU-EP' 'pf_mode_4x')
  hpf8=$(kv 'PERF-HEU-EP' 'pf_mode_8x')

  local hfv hfb hbb hbr hcb hbv hso_c hvo_c
  hfv=$(kv 'PERF-HEU-FE' 'valid_cyc'); hfb=$(kv 'PERF-HEU-FE' 'ready_block_cyc')
  hbb=$(kv 'PERF-HEU-FE' 'block_buffer_cyc'); hbr=$(kv 'PERF-HEU-FE' 'block_branch_cyc')
  hcb=$(kv 'PERF-HEU-FE' 'current_busy_cyc'); hbv=$(kv 'PERF-HEU-FE' 'buffer_valid_cyc')
  hso_c=$(kv 'PERF-HEU-FE' 'scalar_out_cyc'); hvo_c=$(kv 'PERF-HEU-FE' 'vector_out_cyc')

  local hea heg hebd hebq hebb hebm hegd hefd hevd hcross hover
  hea=$(kv 'PERF-HEU-OVLP' 'early_attempt'); heg=$(kv 'PERF-HEU-OVLP' 'early_grant')
  hebd=$(kv 'PERF-HEU-OVLP' 'early_blk_dispatch'); hebq=$(kv 'PERF-HEU-OVLP' 'early_blk_queue')
  hebb=$(kv 'PERF-HEU-OVLP' 'early_blk_branch')
  hebm=$(kv 'PERF-HEU-OVLP' 'early_blk_scalar_mem'); hegd=$(kv 'PERF-HEU-OVLP' 'early_blk_gpr_dep')
  hefd=$(kv 'PERF-HEU-OVLP' 'early_blk_fpr_dep'); hevd=$(kv 'PERF-HEU-OVLP' 'early_blk_vec_dep')
  hcross=$(kv 'PERF-HEU-OVLP' 'cross_ep_cyc'); hover=$(kv 'PERF-HEU-OVLP' 'overlap_cyc')

  local vcv vcf vcb vcso vcsc vcfc vcec vrso vrsc
  vcv=$(kv 'PERF-VDU-CMD' 'vector_cmd_valid'); vcf=$(kv 'PERF-VDU-CMD' 'vector_cmd_fire')
  vcb=$(kv 'PERF-VDU-CMD' 'vector_cmd_blocked'); vcso=$(kv 'PERF-VDU-CMD' 'cmd_window_sum_occ')
  vcsc=$(kv 'PERF-VDU-CMD' 'cmd_window_sample_cyc'); vcfc=$(kv 'PERF-VDU-CMD' 'cmd_window_full_cyc')
  vcec=$(kv 'PERF-VDU-CMD' 'cmd_window_empty_cyc'); vrso=$(kv 'PERF-VDU-CMD' 'resp_meta_sum_occ')
  vrsc=$(kv 'PERF-VDU-CMD' 'resp_meta_sample_cyc')

  local soc sob solr solh sopb vep vep_p vep_b vsetw
  soc=$(kv 'PERF-VDU-OPERAND' 'scalar_operand_capture')
  sob=$(kv 'PERF-VDU-OPERAND' 'scalar_operand_bypass')
  solr=$(kv 'PERF-VDU-OPERAND' 'scalar_operand_lookahead_req')
  solh=$(kv 'PERF-VDU-OPERAND' 'scalar_operand_lookahead_hit')
  sopb=$(kv 'PERF-VDU-OPERAND' 'scalar_operand_port_busy')
  vep=$(kv 'PERF-VDU-OPERAND' 'vector_ep_enqueue')
  vep_p=$(kv 'PERF-VDU-OPERAND' 'vector_ep_pending_enqueue')
  vep_b=$(kv 'PERF-VDU-OPERAND' 'vector_ep_ready_block')
  vsetw=$(kv 'PERF-VDU-OPERAND' 'vset_visible_wait_cycles')

  local irc irs isr isc pk byh dmr acp
  irc=$(kv 'IPU-PERF' 'ready_cyc'); irs=$(kv 'IPU-PERF' 'ready_stall')
  isr=$(kv 'IPU-PERF' 'stall_due_to_sram'); isc=$(kv 'IPU-PERF' 'serve_cycles')
  pk=$(kv 'IPU-PERF' 'packets'); byh=$(kv 'IPU-PERF' 'bypass_hits')
  dmr=$(kv 'IPU-PERF' 'demand_reads'); acp=$(kv 'IPU-PERF' 'avg_cycles_per_pkt')

  local dar pfa pfh lds pfen daw dB pfB
  dar=$(kv 'PERF-ADDRGEN\]' 'demand_ar'); pfa=$(kv 'PERF-ADDRGEN\]' 'pf_ar')
  pfh=$(kv 'PERF-ADDRGEN\]' 'pf_hit'); lds=$(kv 'PERF-ADDRGEN\]' 'loads')
  pfen=$(kv 'PERF-ADDRGEN\]' 'pf_en_cyc'); daw=$(kv 'PERF-ADDRGEN\]' 'demand_aw')
  dB=$(kv 'PERF-ADDRGEN\]' 'demand_B'); pfB=$(kv 'PERF-ADDRGEN\]' 'pf_B')

  local parf palf pap pad p2nd drb pdis ppc pqf pal
  parf=$(kv 'PERF-ADDRGEN-PF' 'pf_ar_rob_full'); palf=$(kv 'PERF-ADDRGEN-PF' 'pf_ar_lkup_full')
  pap=$(kv 'PERF-ADDRGEN-PF' 'pf_ar_pending'); pad=$(kv 'PERF-ADDRGEN-PF' 'pf_ar_dis')
  p2nd=$(kv 'PERF-ADDRGEN-PF' 'pf_2nd'); drb=$(kv 'PERF-ADDRGEN-PF' 'dem_rob_block')
  pdis=$(kv 'PERF-ADDRGEN-PF' 'pf_disabled'); ppc=$(kv 'PERF-ADDRGEN-PF' 'pf_page_cross')
  pqf=$(kv 'PERF-ADDRGEN-PF' 'pf_queue_full'); pal=$(kv 'PERF-ADDRGEN-PF' 'pf_avl_low')

  local pth plt pun pwm pwe pqvc pqbc plfc prfc ppc2 psb pfk pqmc prmc ppwc
  pth=$(kv 'PERF-ADDRGEN-PF2' 'pf_throttle_cyc'); plt=$(kv 'PERF-ADDRGEN-PF2' 'pf_late')
  pun=$(kv 'PERF-ADDRGEN-PF2' 'pf_unused'); pwm=$(kv 'PERF-ADDRGEN-PF2' 'pf_wait_match_cyc')
  pwe=$(kv 'PERF-ADDRGEN-PF2' 'pf_wait_match_evt'); pqvc=$(kv 'PERF-ADDRGEN-PF2' 'pf_queue_valid_cyc')
  pqbc=$(kv 'PERF-ADDRGEN-PF2' 'pf_queue_block_cyc'); plfc=$(kv 'PERF-ADDRGEN-PF2' 'pf_lkup_full_cyc')
  prfc=$(kv 'PERF-ADDRGEN-PF2' 'pf_rob_full_cyc'); ppc2=$(kv 'PERF-ADDRGEN-PF2' 'pf_pending_cyc')
  psb=$(kv 'PERF-ADDRGEN-PF2' 'pf_stream_break'); pfk=$(kv 'PERF-ADDRGEN-PF2' 'pf_future_keep')
  pqmc=$(kv 'PERF-ADDRGEN-PF2' 'pf_queue_match_cyc'); prmc=$(kv 'PERF-ADDRGEN-PF2' 'pf_rob_match_cyc')
  ppwc=$(kv 'PERF-ADDRGEN-PF2' 'pf_page_wait_cyc')

  local sissue sblk sraw swar swaw swawb sepb sfull
  sissue=$(kv 'PERF-SEQ' 'issue'); sblk=$(kv 'PERF-SEQ' 'blocked')
  sraw=$(kv 'PERF-SEQ' 'raw'); swar=$(kv 'PERF-SEQ' 'war'); swaw=$(kv 'PERF-SEQ' 'waw')
  swawb=$(kv 'PERF-SEQ' 'waw_block'); sepb=$(kv 'PERF-SEQ' 'ep_bypass'); sfull=$(kv 'PERF-SEQ' 'full')

  local shc ssec shpr sth sfh sqfs slds sors swsc smwc
  shc=$(kv 'PERF-SEQ-HDV' 'hazard_check'); ssec=$(kv 'PERF-SEQ-HDV' 'same_ep_candidate')
  shpr=$(kv 'PERF-SEQ-HDV' 'hazard_pruned'); sth=$(kv 'PERF-SEQ-HDV' 'true_hazard_stall')
  sfh=$(kv 'PERF-SEQ-HDV' 'false_hazard_stall'); sqfs=$(kv 'PERF-SEQ-HDV' 'queue_full_stall')
  slds=$(kv 'PERF-SEQ-HDV' 'lane_desync_stall'); sors=$(kv 'PERF-SEQ-HDV' 'operand_req_stall')
  swsc=$(kv 'PERF-SEQ-HDV' 'wait_state_cyc'); smwc=$(kv 'PERF-SEQ-HDV' 'mem_wait_cyc')

  local pfhr=""
  if [ -n "$pfa" ] && [ "$pfa" -gt 0 ] 2>/dev/null; then
    pfhr=$(echo "scale=3; ${pfh:-0}/$pfa" | bc)
  fi
  local depblk="" sbph="" cmdavg="" vqavg=""
  if [ -n "$hegd" ] || [ -n "$hefd" ] || [ -n "$hevd" ]; then
    depblk=$(( ${hegd:-0} + ${hefd:-0} + ${hevd:-0} ))
  fi
  if [ -n "$sob" ] || [ -n "$solh" ]; then
    sbph=$(( ${sob:-0} + ${solh:-0} ))
  fi
  if [ -n "$vcso" ] && [ -n "$vcsc" ] && [ "$vcsc" -gt 0 ] 2>/dev/null; then
    cmdavg=$(echo "scale=3; $vcso/$vcsc" | bc)
    vqavg="$cmdavg"
  fi

  local row="$group,$kernel,$tag,$avl,$size,$rows,$n,$r,${tc:-},$cpe,$cpm,${wc:-},${eps:-},${vbusy:-},${imem:-}"
  row="$row,${ep_ack:-},${ep_vack:-},${vqpush:-},${vqpop:-},${vqmax:-},${vqbyp:-},${vqfs:-},${dslots:-},${dcyc:-},${fbyp:-},${owc:-},${abp:-},${rwfs:-},${rmfs:-},${rmmax:-}"
  row="$row,${hacc:-},${hws:-},${hsc:-},${hvc:-},${hws:-},${hwgt:-},${hm:-},${hws:-},${his:-},${hcur:-},${hbuf:-},${hso:-},${hvo:-},${hpfh:-},${hpfd:-},${hpf1:-},${hpf2:-},${hpf4:-},${hpf8:-}"
  row="$row,${hfv:-},${hfb:-},${hbb:-},${hbr:-},${hcb:-},${hbv:-},${hso_c:-},${hvo_c:-}"
  row="$row,${hea:-},${heg:-},${hebd:-},${hebq:-},${hebb:-},${hebm:-},${depblk:-},${hegd:-},${hefd:-},${hevd:-},${hcross:-},${hover:-}"
  row="$row,${vcv:-},${vcf:-},${vcb:-},${cmdavg:-},${vcso:-},${vcsc:-},${vqmax:-},${vcfc:-},${vcec:-},${vqavg:-},${vcec:-},${vcfc:-},${vrso:-},${vrsc:-}"
  row="$row,${soc:-},${sbph:-},${owc:-},${vsetw:-},${sob:-},${solr:-},${solh:-},${sopb:-},${vep:-},${vep_p:-},${vep_b:-}"
  row="$row,${irc:-},${irs:-},${isr:-},${isc:-},${pk:-},${byh:-},${dmr:-},${acp:-}"
  row="$row,${dar:-},${pfa:-},${pfh:-},${lds:-},${pfen:-},${daw:-},${dB:-},${pfB:-}"
  row="$row,${parf:-},${palf:-},${pap:-},${pad:-},${p2nd:-},${drb:-},${pdis:-},${ppc:-},${pqf:-},${pal:-}"
  row="$row,${pth:-},${plt:-},${pun:-},${pwm:-},${pwe:-},${pqvc:-},${pqbc:-},${plfc:-},${prfc:-},${ppc2:-},${psb:-},${pfk:-},${pqmc:-},${prmc:-},${ppwc:-}"
  row="$row,${sissue:-},${sblk:-},${sraw:-},${swar:-},${swaw:-},${swawb:-},${sepb:-},${sfull:-}"
  row="$row,${shc:-},${ssec:-},${shpr:-},${sth:-},${sfh:-},${sqfs:-},${slds:-},${sors:-},${swsc:-},${smwc:-},$pfhr"

  echo "$row" >> "$csv"
}

# ---------------------------------------------------------------------------
# Active 1D AVL sweep
# ---------------------------------------------------------------------------
AVL_ROWHDR="$KERNEL_ROWHDR"

run_1d_sweep() {
  local avls="${1:-32 64 128 256 512 1024 2048 4096}"
  local kernels="${2:-vsaxpy_hdv vvaddint32_hdv vscopy_hdv vsswap_hdv vsdot_hdv vsscal_hdv vmc_hdv dropout_hdv vsdwt_hdv vstencil3_hdv vfir5_hdv}"

  declare -A maxavl=(
    [vsaxpy_hdv]=4096   [vscopy_hdv]=1024   [vsscal_hdv]=1024
    [vsswap_hdv]=4096   [vsdot_hdv]=4096    [vvaddint32_hdv]=4096
    [vmc_hdv]=1024      [dropout_hdv]=1024  [vsdwt_hdv]=4096
    [vstencil3_hdv]=4096 [vfir5_hdv]=4096
  )
  declare -A avlreg=( [vsdot_hdv]=A2 [vsdwt_hdv]=A2 )
  declare -A extra_plusargs=()
  extra_plusargs[vstencil3_hdv]="+HDV_PACKET_WATCHDOG=20000"
  extra_plusargs[vfir5_hdv]="+HDV_PACKET_WATCHDOG=20000"

  note "########## Group 1: active 1D streaming kernels ##########"

  local k n csv max reg row ptr_pa
  for k in $kernels; do
    case "$k" in
      fdotp_hdv|vspf_*_hdv)
        echo "ERROR: $k is excluded from active sweep." >&2
        exit 2
        ;;
    esac
    max=${maxavl[$k]:-1024}
    csv="$OUT/${k}.csv"
    echo "$AVL_ROWHDR" > "$csv"
    echo "==================== $k  (max AVL=$max) ===================="
    printf "%-7s %-7s %-8s %-7s %-6s %-7s %-7s %-9s %s\n" \
           "AVL" "result" "cycles" "cyc/el" "EPs" "pkts" "avg/pk" "pf_ar->hit" "seq_blk"

    rm -f "$APPS/$k/main.c.o" "$APPS/bin/$k"
    if ! ( cd "$APPS" && timeout 600 make "bin/$k" ) > "$OUT/build_avl_${k}.log" 2>&1; then
      echo "  $k: BUILD FAIL (see $OUT/build_avl_${k}.log)"
      continue
    fi

    ptr_pa=$(one_d_ptr_plusargs "$k")
    for n in $avls; do
      if [ "$n" -gt "$max" ]; then continue; fi
      log="$OUT/log_avl_${k}_${n}.log"
      reg=${avlreg[$k]:-A0}
      timeout 3600 make sim app="$k" \
        hdv_plusargs="+HDV_${reg}=${n} $ptr_pa${extra_plusargs[$k]:-} +HDV_EXPECTED_EP=8000000" \
        > "$log" 2>&1

      write_kernel_csv_row "avl" "$k" "" "$n" "" "" "" "$n" 0 "$csv"

      local r tc eps cpe pk acp pfa pfh sblk
      r=$(grep -E 'mock host' "$log" | head -1 | grep -oE 'PASSED|FAILED'); [ -z "$r" ] && r="ERR"
      tc=$(kv 'mock host' 'total_task_cycles')
      eps=$(d 'HDV-CSR.*DONE' 'accepted'); [ -z "$eps" ] && eps=$(grep -E 'mock host' "$log" | grep -oE 'got [0-9]+' | grep -oE '[0-9]+')
      cpe="-"; [ -n "$tc" ] && cpe=$(echo "scale=3; $tc/$n" | bc)
      pk=$(kv 'IPU-PERF' 'packets'); acp=$(kv 'IPU-PERF' 'avg_cycles_per_pkt')
      pfa=$(kv 'PERF-ADDRGEN\]' 'pf_ar')
      pfh=$(kv 'PERF-ADDRGEN\]' 'pf_hit')
      sblk=$(kv 'PERF-SEQ' 'blocked')
      printf "%-7s %-7s %-8s %-7s %-6s %-7s %-7s %-9s %s\n" \
             "$n" "$r" "${tc:--}" "$cpe" "${eps:--}" "${pk:--}" "${acp:--}" "${pfa:--}->${pfh:--}" "${sblk:--}"
    done
  done
}

run_1d_point() {
  local k=$1 n=${2:-1024}
  local csv="$OUT/${k}.csv" reg row r tc eps cpe pk acp pfa pfh sblk extra_pa="" ptr_pa=""

  case "$k" in
    fdotp_hdv|vspf_*_hdv)
      echo "ERROR: $k is excluded from active sweep." >&2
      return 2
      ;;
  esac

  declare -A avlreg=( [vsdot_hdv]=A2 [vsdwt_hdv]=A2 )
  case "$k" in
    vstencil3_hdv|vfir5_hdv)
      extra_pa="+HDV_PACKET_WATCHDOG=20000"
      ;;
  esac

  note "########## Single 1D AVL point: $k AVL=$n ##########"
  echo "$AVL_ROWHDR" > "$csv"
  echo "==================== $k  (single AVL=$n) ===================="
  printf "%-7s %-7s %-8s %-7s %-6s %-7s %-7s %-9s %s\n" \
         "AVL" "result" "cycles" "cyc/el" "EPs" "pkts" "avg/pk" "pf_ar->hit" "seq_blk"

  rm -f "$APPS/$k/main.c.o" "$APPS/bin/$k"
  if ! ( cd "$APPS" && timeout 600 make "bin/$k" ) > "$OUT/build_avl_${k}.log" 2>&1; then
    echo "  $k: BUILD FAIL (see $OUT/build_avl_${k}.log)"
    return 1
  fi

  log="$OUT/log_avl_${k}_${n}.log"
  reg=${avlreg[$k]:-A0}
  ptr_pa=$(one_d_ptr_plusargs "$k")
  timeout 3600 make sim app="$k" \
    hdv_plusargs="+HDV_${reg}=${n} $ptr_pa$extra_pa +HDV_EXPECTED_EP=8000000" \
    > "$log" 2>&1

  write_kernel_csv_row "avl" "$k" "" "$n" "" "" "" "$n" 0 "$csv"

  r=$(grep -E 'mock host' "$log" | head -1 | grep -oE 'PASSED|FAILED'); [ -z "$r" ] && r="ERR"
  tc=$(kv 'mock host' 'total_task_cycles')
  eps=$(d 'HDV-CSR.*DONE' 'accepted'); [ -z "$eps" ] && eps=$(grep -E 'mock host' "$log" | grep -oE 'got [0-9]+' | grep -oE '[0-9]+')
  cpe="-"; [ -n "$tc" ] && cpe=$(echo "scale=3; $tc/$n" | bc)
  pk=$(kv 'IPU-PERF' 'packets'); acp=$(kv 'IPU-PERF' 'avg_cycles_per_pkt')
  pfa=$(kv 'PERF-ADDRGEN\]' 'pf_ar')
  pfh=$(kv 'PERF-ADDRGEN\]' 'pf_hit')
  sblk=$(kv 'PERF-SEQ' 'blocked')
  printf "%-7s %-7s %-8s %-7s %-6s %-7s %-7s %-9s %s\n" \
         "$n" "$r" "${tc:--}" "$cpe" "${eps:--}" "${pk:--}" "${acp:--}" "${pfa:--}->${pfh:--}" "${sblk:--}"
}

# ---------------------------------------------------------------------------
# BLAS/GEMM sweep
# ---------------------------------------------------------------------------
BLAS_ROWHDR="$KERNEL_ROWHDR"
declare -A BLAS_TAG_INIT=()

ensure_blas_tag_csv() {
  local tag=$1
  if [ -z "${BLAS_TAG_INIT[$tag]+x}" ]; then
    if [ "$APPEND_OUT" = "1" ] && [ -s "$OUT/${tag}.csv" ]; then
      :
    else
      echo "$BLAS_ROWHDR" > "$OUT/${tag}.csv"
    fi
    BLAS_TAG_INIT[$tag]=1
  fi
}

drop_existing_blas_row() {
  local tag=$1 size=$2 rows=$3 n=$4 csv="$OUT/${tag}.csv"
  if [ "$APPEND_OUT" != "1" ] || [ ! -s "$csv" ]; then
    return
  fi
  local tmp
  tmp=$(mktemp)
  awk -F, -v tag="$tag" -v size="$size" -v rows="$rows" -v n="$n" \
    'NR == 1 || !($2 == tag && $5 == size && $6 == rows && $7 == n)' \
    "$csv" > "$tmp"
  mv "$tmp" "$csv"
}

parse_blas_perf() {
  local tag=$1 size=$2 rows=$3 n=$4 macc=$5
  ensure_blas_tag_csv "$tag"
  drop_existing_blas_row "$tag" "$size" "$rows" "$n"
  write_kernel_csv_row "blas" "$tag" "$tag" "" "$size" "$rows" "$n" 0 "$macc" "$OUT/${tag}.csv"

  local r tc eps cpm vqmax pfa pfh sblk
  r=$(grep -E 'mock host' "$log" | head -1 | grep -oE 'PASSED|FAILED'); [ -z "$r" ] && r="ERR"
  tc=$(kv 'mock host' 'total_task_cycles')
  eps=$(d 'HDV-CSR.*DONE' 'accepted'); [ -z "$eps" ] && eps=$(grep -E 'mock host' "$log" | grep -oE 'got [0-9]+' | grep -oE '[0-9]+')
  cpm="-"; [ -n "$tc" ] && [ "$macc" -gt 0 ] 2>/dev/null && cpm=$(echo "scale=4; $tc/$macc" | bc)
  vqmax=$(kv 'HDV-PERF' 'vq_max_occupancy')
  pfa=$(kv 'PERF-ADDRGEN\]' 'pf_ar')
  pfh=$(kv 'PERF-ADDRGEN\]' 'pf_hit')
  sblk=$(kv 'PERF-SEQ' 'blocked')
  printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
         "$tag" "$size" "$rows" "$r" "${tc:--}" "$cpm" "${eps:--}" "${vqmax:--}" \
         "${pfa:--}->${pfh:--}" "${sblk:--}"
}

sweep_vsgemm() {
  local ns="${1:-16 32 64 128}"
  note "########## Group 2A: vsgemm ##########"
  echo "==================== vsgemm  {lmul}x{rows}x{N} ===================="
  printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
         "tag" "N" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"

  local lmul rows n nlist tag s1 s2 macc
  for lmul in 1 4; do
    for rows in 1 2 4; do
      nlist="$ns"
      [ "$lmul" = "1" ] && [ "$rows" != "4" ] && nlist="32"
      [ "$lmul" = "1" ] && [ "$rows" = "4" ] && nlist="32 64 128"
      for n in $nlist; do
        tag="vsgemm_m${lmul}_${rows}r"
        rm -f "$APPS/vsgemm_hdv/main.c.o"
        ( cd "$APPS" && timeout 600 make bin/vsgemm_hdv gemm_lmul=$lmul gemm_rows=$rows gemm_n=$n ) \
          > "$OUT/build_vsgemm_m${lmul}_${rows}r_${n}.log" 2>&1
        s1=$(addr_of vsgemm_hdv src1); s2=$(addr_of vsgemm_hdv src2)
        if [ -z "$s1" ] || [ -z "$s2" ]; then
          echo "  vsgemm m${lmul} ${rows}r N=$n: BUILD/ADDR FAIL"
          continue
        fi
        log="$OUT/log_blas_${tag}_${n}.log"
        if [ "$SKIP_LONG" = "1" ] &&
           { { [ "$lmul" = "4" ] && [ "$n" -ge 128 ]; } ||
             { [ "$lmul" = "1" ] && [ "$rows" = "4" ] && [ "$n" -ge 128 ]; }; }; then
          skip_long_note "$tag N=$n"
          printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
                 "$tag" "$n" "$rows" "SKIP" "-" "-" "-" "-" "-->-" "over_10min"
          continue
        fi
        if { [ "$lmul" = "4" ] && [ "$rows" != "4" ] && [ "$n" -ge 64 ]; } ||
           { [ "$lmul" = "4" ] && [ "$rows" = "4" ] && [ "$n" -ge 128 ]; } ||
           { [ "$lmul" = "1" ] && [ "$rows" = "4" ] && [ "$n" -ge 64 ]; }; then
          timeout 3600 make sim app=vsgemm_hdv \
            hdv_plusargs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=1000000" \
            > "$log" 2>&1
        else
          timeout 600 make sim app=vsgemm_hdv \
            hdv_plusargs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n +HDV_EXPECTED_EP=8000000" \
            > "$log" 2>&1
        fi
        if [ "$lmul" = "1" ] && [ "$rows" != "4" ]; then
          macc=32768
        else
          macc=$((n*n*n))
        fi
        parse_blas_perf "$tag" "$n" "$rows" "$n" "$macc"
      done
    done
  done
}

sweep_blas_dim() {
  local ns="${1:-16 32 64 128}"
  note "########## Group 2B: BLAS dim sweep ##########"

  declare -A b_dimreg=( [vssymv_hdv]=A3 [vssyrk_hdv]=A2 [vstrsm_hdv]=A2
                        [vsger_hdv]=A1  [vsgemv_hdv]=A3 )
  local k n s1 s2 reg ptrs macc
  for k in vsger_hdv vssymv_hdv vssyrk_hdv vstrsm_hdv vsgemv_hdv; do
    rm -f "$APPS/$k/main.c.o"
    ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=4 ) > "$OUT/build_blas_${k}.log" 2>&1
    s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
    if [ -z "$s1" ]; then
      echo "  $k: BUILD/ADDR FAIL"
      continue
    fi
    echo "==================== $k  (dim sweep) ===================="
    printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
           "tag" "size" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
    reg=${b_dimreg[$k]}
    for n in $ns; do
      case "$k" in
        vsger_hdv)  ptrs="+HDV_A0=128 +HDV_A2=$s2 +HDV_A3=$((s2+512)) +HDV_A4=$s1 +HDV_A1=$n" ;;
        vssymv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n" ;;
        vssyrk_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$n" ;;
        vstrsm_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$n" ;;
        vsgemv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$((s2+512)) +HDV_A3=$n" ;;
      esac
      log="$OUT/log_blas_${k}_${n}.log"
      if [ "$SKIP_LONG" = "1" ] &&
         { { [ "$k" = "vssyrk_hdv" ] && [ "$n" -ge 64 ]; } ||
           { [ "$k" = "vstrsm_hdv" ] && [ "$n" -ge 128 ]; }; }; then
        skip_long_note "$k N=$n"
        printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
               "$k" "$n" "-" "SKIP" "-" "-" "-" "-" "-->-" "over_10min"
        continue
      fi
      if { [ "$k" = "vssyrk_hdv" ] && [ "$n" -ge 32 ]; } ||
         { [ "$k" = "vstrsm_hdv" ] && [ "$n" -ge 64 ]; }; then
        timeout 3600 make sim app=$k \
          hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
      else
        timeout 600 make sim app=$k \
          hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000" > "$log" 2>&1
      fi
      if [ "$k" = "vsger_hdv" ]; then
        macc=$((128*n))
      else
        macc=$((n*n))
      fi
      parse_blas_perf "$k" "$n" "-" "$n" "$macc"
    done
  done
}

sweep_blas_pf() {
  local ms="${1:-32 64}"
  note "########## Group 2C: BLAS LMUL prefetch sweep ##########"

  local k lm M s1 s2 yoff ptrs
  for k in vssymv_hdv vsgemv_hdv vstrsm_hdv; do
    for lm in 2 4 8; do
      rm -f "$APPS/$k/main.c.o"
      ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=$lm ) > "$OUT/build_blaspf_${k}_${lm}.log" 2>&1
      s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
      if [ -z "$s1" ]; then
        echo "  $k m$lm: BUILD/ADDR FAIL"
        continue
      fi
      yoff=$((lm*128))
      echo "============== $k  m$lm  (LMUL prefetch sweep) =============="
      printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
             "tag" "m$lm" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
      for M in $ms; do
        case "$k" in
          vssymv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$M" ;;
          vsgemv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$((s2+yoff)) +HDV_A3=$M" ;;
          vstrsm_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$M" ;;
        esac
        log="$OUT/log_blaspf_${k}_${lm}_${M}.log"
        if [ "$SKIP_LONG" = "1" ] && [ "$k" = "vstrsm_hdv" ] &&
           [ "$lm" = "8" ] && [ "$M" -ge 64 ]; then
          skip_long_note "${k}_m${lm} M=$M"
          printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
                 "${k}_m${lm}" "$lm" "$M" "SKIP" "-" "-" "-" "-" "-->-" "over_10min"
          continue
        fi
        if [ "$k" = "vstrsm_hdv" ] &&
           { { [ "$lm" = "2" ] && [ "$M" -ge 64 ]; } ||
             { [ "$lm" = "4" ] && [ "$M" -ge 64 ]; } ||
             { [ "$lm" = "8" ] && [ "$M" -ge 32 ]; }; }; then
          timeout 3600 make sim app=$k \
            hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
        else
          timeout 600 make sim app=$k \
            hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000" > "$log" 2>&1
        fi
        parse_blas_perf "${k}_m${lm}" "$lm" "$M" "$M" "$((M*lm*32))"
      done
    done
  done
}

sweep_blas_groups() {
  local ns="${1:-128}" groups_list="${2:-2 4 8}" lms="${3:-4}"
  note "########## Group 2D: BLAS GEMV/SYMV multi-row sweep ##########"

  local k lm n groups s1 s2 yoff ptrs tag log macc vlmax
  for k in vssymv_hdv vsgemv_hdv; do
    for lm in $lms; do
      rm -f "$APPS/$k/main.c.o"
      ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=$lm ) > "$OUT/build_blasgrp_${k}_${lm}.log" 2>&1
      s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
      if [ -z "$s1" ]; then
        echo "  $k m$lm: BUILD/ADDR FAIL"
        continue
      fi
      yoff=$((lm*128))
      vlmax=$((lm*32))
      echo "============== $k  m$lm  (multi-row sweep) =============="
      printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
             "tag" "N" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
      for n in $ns; do
        if [ "$n" -gt "$vlmax" ]; then
          note "[skip] ${k}_m${lm} N=$n rows=* skipped: N exceeds VLMAX=$vlmax"
          continue
        fi
        for groups in $groups_list; do
          case "$k" in
            vssymv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n +HDV_A4=$groups" ;;
            vsgemv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$((s2+yoff)) +HDV_A3=$n +HDV_A4=$groups" ;;
          esac
          tag="${k}_m${lm}_${groups}g"
          log="$OUT/log_blaspf_${k}_${lm}_${n}_${groups}g.log"
          timeout 600 make sim app=$k \
            hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000" > "$log" 2>&1
          macc=$((n*groups))
          parse_blas_perf "$tag" "$lm" "$groups" "$n" "$macc"
        done
      done
    done
  done
}

sweep_blas_all() {
  local ns="${1:-16 32 64 128}"
  sweep_blas_dim "$ns"
  sweep_blas_pf "32 64"
  sweep_blas_groups "128" "2 4 8" "4"
  sweep_vsgemm "$ns"
}

run_long_sweep() {
  note "########## Long-only sweep: points skipped by --skip-long ##########"

  local lmul rows n tag s1 s2 macc
  note "########## Long Group A: vsgemm m4 N=128 ##########"
  echo "==================== vsgemm long points ===================="
  printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
         "tag" "N" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
  lmul=4
  n=128
  for rows in 1 2 4; do
    rm -f "$APPS/vsgemm_hdv/main.c.o"
    ( cd "$APPS" && timeout 600 make bin/vsgemm_hdv gemm_lmul=$lmul gemm_rows=$rows ) \
      > "$OUT/build_vsgemm_m${lmul}_${rows}r.log" 2>&1
    s1=$(addr_of vsgemm_hdv src1); s2=$(addr_of vsgemm_hdv src2)
    if [ -z "$s1" ] || [ -z "$s2" ]; then
      echo "  vsgemm m${lmul} ${rows}r: BUILD/ADDR FAIL"
      continue
    fi
    tag="vsgemm_m${lmul}_${rows}r"
    log="$OUT/log_blas_${tag}_${n}.log"
    timeout 3600 make sim app=vsgemm_hdv \
      hdv_plusargs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=1000000" \
      > "$log" 2>&1
    macc=$((n*n*n))
    parse_blas_perf "$tag" "$n" "$rows" "$n" "$macc"
  done

  note "########## Long Group B: BLAS dim long points ##########"
  local k ptrs
  for k in vssyrk_hdv vstrsm_hdv; do
    rm -f "$APPS/$k/main.c.o"
    ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=4 ) > "$OUT/build_blas_${k}.log" 2>&1
    s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
    if [ -z "$s1" ]; then
      echo "  $k: BUILD/ADDR FAIL"
      continue
    fi
    echo "==================== $k long dim points ===================="
    printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
           "tag" "size" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
    case "$k" in
      vssyrk_hdv)
        for n in 64 128; do
          ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$n"
          log="$OUT/log_blas_${k}_${n}.log"
          timeout 3600 make sim app=$k \
            hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
          parse_blas_perf "$k" "$n" "-" "$n" "$((n*n))"
        done
        ;;
      vstrsm_hdv)
        n=128
        ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$n"
        log="$OUT/log_blas_${k}_${n}.log"
        timeout 3600 make sim app=$k \
          hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
        parse_blas_perf "$k" "$n" "-" "$n" "$((n*n))"
        ;;
    esac
  done

  note "########## Long Group C: BLAS LMUL prefetch long points ##########"
  local lm M yoff
  k=vstrsm_hdv
  lm=8
  M=64
  rm -f "$APPS/$k/main.c.o"
  ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=$lm ) > "$OUT/build_blaspf_${k}_${lm}.log" 2>&1
  s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
  if [ -n "$s1" ]; then
    echo "==================== $k m$lm long prefetch point ===================="
    printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
           "tag" "m$lm" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
    ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$M"
    log="$OUT/log_blaspf_${k}_${lm}_${M}.log"
    timeout 3600 make sim app=$k \
      hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
    parse_blas_perf "${k}_m${lm}" "$lm" "$M" "$M" "$((M*lm*32))"
  else
    echo "  ${k}_m${lm}: BUILD/ADDR FAIL"
  fi
}

run_onepoint_sweep() {
  note "########## One-point sweep: one short point per kernel/variant ##########"
  run_1d_sweep "1024"
  sweep_blas_dim "32"
  sweep_blas_pf "32"
  sweep_blas_groups "128" "2" "4"
  sweep_vsgemm "32"
  run_fixed_sweep
}

# ---------------------------------------------------------------------------
# Fixed/app-shaped points
# ---------------------------------------------------------------------------
run_fixed_point() {
  local app=$1 pa=$2 tag=$3 label=$4
  log="$OUT/${tag}.log"
  ( timeout 3600 make sim app="$app" hdv_plusargs="$pa +HDV_EXPECTED_EP=8000000" > "$log" 2>&1 )
  local r c pfa pfh sblk
  r=$(grep -iE 'mock host' "$log" | grep -oE 'PASSED|FAILED' | head -1)
  c=$(grep -iE 'mock host' "$log" | grep -oE 'cycle=[0-9]+' | grep -oE '[0-9]+' | head -1)
  pfa=$(kv 'PERF-ADDRGEN\]' 'pf_ar')
  pfh=$(kv 'PERF-ADDRGEN\]' 'pf_hit')
  sblk=$(kv 'PERF-SEQ' 'blocked')
  printf "%-34s %-7s cyc=%-8s pf=%-9s seq_blk=%s\n" \
         "$label" "${r:-TIMEOUT}" "${c:-NA}" "${pfa:--}->${pfh:--}" "${sblk:--}"
  echo "$KERNEL_ROWHDR" > "$OUT/${tag}.csv"
  write_kernel_csv_row "fixed" "$tag" "$tag" "" "" "" "" 0 0 "$OUT/${tag}.csv"
}

run_fixed_sweep() {
  note "########## Group 3: fixed/app-shaped kernels ##########"

  local s1 s2 ci o i f av bv bx by bz lbv bq ap fo si so

  ( cd "$APPS" && make bin/vssyrk_hdv blas_lmul=1 > "../hardware/$OUT/build_vssyrk_m1_fix.log" 2>&1 )
  s1=$(addr_of vssyrk_hdv src1); s2=$(addr_of vssyrk_hdv src2)
  run_fixed_point vssyrk_hdv "+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=32 +HDV_TASK_WATCHDOG=$WD" "vssyrk_m1_fix" "vssyrk m1 32x32 (strided)"

  ( cd "$APPS" && make bin/vstrsm_hdv blas_lmul=1 > "../hardware/$OUT/build_vstrsm_m1_fix.log" 2>&1 )
  s1=$(addr_of vstrsm_hdv src1); s2=$(addr_of vstrsm_hdv src2)
  run_fixed_point vstrsm_hdv "+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=32 +HDV_TASK_WATCHDOG=$WD" "vstrsm_m1_fix" "vstrsm m1 32x32"

  ( cd "$APPS" && make bin/vsspmv_hdv > "../hardware/$OUT/build_vsspmv_fix.log" 2>&1 )
  s1=$(addr_of vsspmv_hdv src1); s2=$(addr_of vsspmv_hdv src2); ci=$(addr_of vsspmv_hdv col_idx)
  run_fixed_point vsspmv_hdv "+HDV_A0=$s1 +HDV_A1=$ci +HDV_A2=$s2 +HDV_A3=$((s2+256)) +HDV_TASK_WATCHDOG=$WD" "vsspmv_fix" "vsspmv sparse 32x32"

  ( cd "$APPS" && make bin/fconv2d_hdv > "../hardware/$OUT/build_fconv2d_fix.log" 2>&1 )
  o=$(addr_of fconv2d_hdv o); i=$(addr_of fconv2d_hdv i); f=$(addr_of fconv2d_hdv f)
  run_fixed_point fconv2d_hdv "+HDV_A0=$o +HDV_A1=$i +HDV_A2=$f +HDV_A3=64 +HDV_A4=32 +HDV_A5=3 +HDV_TASK_WATCHDOG=$WD" "fconv2d_fix" "fconv2d 3x3 e64 R64xC32"

  ( cd "$APPS" && make bin/jacobi2d_hdv > "../hardware/$OUT/build_jacobi2d_fix.log" 2>&1 )
  av=$(addr_of jacobi2d_hdv A_v); bv=$(addr_of jacobi2d_hdv B_v)
  run_fixed_point jacobi2d_hdv "+HDV_A0=128 +HDV_A1=64 +HDV_A2=$av +HDV_A3=$bv +HDV_TASK_WATCHDOG=$WD" "jacobi2d_fix" "jacobi2d 5pt e64 128x64"

  ( cd "$APPS" && make bin/lavamd_hdv > "../hardware/$OUT/build_lavamd_fix.log" 2>&1 )
  bx=$(addr_of lavamd_hdv bx); by=$(addr_of lavamd_hdv by); bz=$(addr_of lavamd_hdv bz)
  lbv=$(addr_of lavamd_hdv bv); bq=$(addr_of lavamd_hdv bq); ap=$(addr_of lavamd_hdv aparams); fo=$(addr_of lavamd_hdv fout_v)
  run_fixed_point lavamd_hdv "+HDV_A0=$bx +HDV_A1=$by +HDV_A2=$bz +HDV_A3=$lbv +HDV_A4=$bq +HDV_A5=$ap +HDV_A6=$fo +HDV_A7=256 +HDV_TASK_WATCHDOG=$WD" "lavamd_fix" "lavamd N-body NPAR=256"

  ( cd "$APPS" && make bin/softmax_hdv > "../hardware/$OUT/build_softmax_fix.log" 2>&1 )
  si=$(addr_of softmax_hdv i); so=$(addr_of softmax_hdv o_v)
  run_fixed_point softmax_hdv "+HDV_A0=$si +HDV_A1=$so +HDV_A2=3 +HDV_A3=256 +HDV_TASK_WATCHDOG=$WD" "softmax_fix" "softmax ch3 x inner256"
}

run_fixed_named() {
  local tag=$1
  local s1 s2 ci o i f av bv bx by bz lbv bq ap fo si so

  note "########## Single fixed/app-shaped point: $tag ##########"
  case "$tag" in
    vssyrk_m1_fix)
      ( cd "$APPS" && make bin/vssyrk_hdv blas_lmul=1 > "../hardware/$OUT/build_vssyrk_m1_fix.log" 2>&1 )
      s1=$(addr_of vssyrk_hdv src1); s2=$(addr_of vssyrk_hdv src2)
      run_fixed_point vssyrk_hdv "+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=32 +HDV_TASK_WATCHDOG=$WD" "vssyrk_m1_fix" "vssyrk m1 32x32 (strided)"
      ;;
    vstrsm_m1_fix)
      ( cd "$APPS" && make bin/vstrsm_hdv blas_lmul=1 > "../hardware/$OUT/build_vstrsm_m1_fix.log" 2>&1 )
      s1=$(addr_of vstrsm_hdv src1); s2=$(addr_of vstrsm_hdv src2)
      run_fixed_point vstrsm_hdv "+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=32 +HDV_TASK_WATCHDOG=$WD" "vstrsm_m1_fix" "vstrsm m1 32x32"
      ;;
    vsspmv_fix)
      ( cd "$APPS" && make bin/vsspmv_hdv > "../hardware/$OUT/build_vsspmv_fix.log" 2>&1 )
      s1=$(addr_of vsspmv_hdv src1); s2=$(addr_of vsspmv_hdv src2); ci=$(addr_of vsspmv_hdv col_idx)
      run_fixed_point vsspmv_hdv "+HDV_A0=$s1 +HDV_A1=$ci +HDV_A2=$s2 +HDV_A3=$((s2+256)) +HDV_TASK_WATCHDOG=$WD" "vsspmv_fix" "vsspmv sparse 32x32"
      ;;
    fconv2d_fix)
      ( cd "$APPS" && make bin/fconv2d_hdv > "../hardware/$OUT/build_fconv2d_fix.log" 2>&1 )
      o=$(addr_of fconv2d_hdv o); i=$(addr_of fconv2d_hdv i); f=$(addr_of fconv2d_hdv f)
      run_fixed_point fconv2d_hdv "+HDV_A0=$o +HDV_A1=$i +HDV_A2=$f +HDV_A3=64 +HDV_A4=32 +HDV_A5=3 +HDV_TASK_WATCHDOG=$WD" "fconv2d_fix" "fconv2d 3x3 e64 R64xC32"
      ;;
    jacobi2d_fix)
      ( cd "$APPS" && make bin/jacobi2d_hdv > "../hardware/$OUT/build_jacobi2d_fix.log" 2>&1 )
      av=$(addr_of jacobi2d_hdv A_v); bv=$(addr_of jacobi2d_hdv B_v)
      run_fixed_point jacobi2d_hdv "+HDV_A0=128 +HDV_A1=64 +HDV_A2=$av +HDV_A3=$bv +HDV_TASK_WATCHDOG=$WD" "jacobi2d_fix" "jacobi2d 5pt e64 128x64"
      ;;
    lavamd_fix)
      ( cd "$APPS" && make bin/lavamd_hdv > "../hardware/$OUT/build_lavamd_fix.log" 2>&1 )
      bx=$(addr_of lavamd_hdv bx); by=$(addr_of lavamd_hdv by); bz=$(addr_of lavamd_hdv bz)
      lbv=$(addr_of lavamd_hdv bv); bq=$(addr_of lavamd_hdv bq); ap=$(addr_of lavamd_hdv aparams); fo=$(addr_of lavamd_hdv fout_v)
      run_fixed_point lavamd_hdv "+HDV_A0=$bx +HDV_A1=$by +HDV_A2=$bz +HDV_A3=$lbv +HDV_A4=$bq +HDV_A5=$ap +HDV_A6=$fo +HDV_A7=256 +HDV_TASK_WATCHDOG=$WD" "lavamd_fix" "lavamd N-body NPAR=256"
      ;;
    softmax_fix)
      ( cd "$APPS" && make bin/softmax_hdv > "../hardware/$OUT/build_softmax_fix.log" 2>&1 )
      si=$(addr_of softmax_hdv i); so=$(addr_of softmax_hdv o_v)
      run_fixed_point softmax_hdv "+HDV_A0=$si +HDV_A1=$so +HDV_A2=3 +HDV_A3=256 +HDV_TASK_WATCHDOG=$WD" "softmax_fix" "softmax ch3 x inner256"
      ;;
    *)
      return 1
      ;;
  esac
  return 0
}

run_blas_dim_point() {
  local k=$1 n=${2:-32}
  local s1 s2 ptrs macc

  note "########## Single BLAS dim point: $k N=$n ##########"
  rm -f "$APPS/$k/main.c.o"
  ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=4 ) > "$OUT/build_blas_${k}.log" 2>&1
  s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
  if [ -z "$s1" ]; then
    echo "  $k: BUILD/ADDR FAIL"
    return 1
  fi
  case "$k" in
    vsger_hdv)  ptrs="+HDV_A0=128 +HDV_A2=$s2 +HDV_A3=$((s2+512)) +HDV_A4=$s1 +HDV_A1=$n" ;;
    vssymv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n" ;;
    vssyrk_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$n" ;;
    vstrsm_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$n" ;;
    vsgemv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$((s2+512)) +HDV_A3=$n" ;;
    *) return 1 ;;
  esac

  echo "==================== $k  single dim point ===================="
  printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
         "tag" "size" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
  log="$OUT/log_blas_${k}_${n}.log"
  if { [ "$k" = "vssyrk_hdv" ] && [ "$n" -ge 32 ]; } ||
     { [ "$k" = "vstrsm_hdv" ] && [ "$n" -ge 64 ]; }; then
    timeout 3600 make sim app=$k \
      hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
  else
    timeout 600 make sim app=$k \
      hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000" > "$log" 2>&1
  fi
  if [ "$k" = "vsger_hdv" ]; then
    macc=$((128*n))
  else
    macc=$((n*n))
  fi
  parse_blas_perf "$k" "$n" "-" "$n" "$macc"
}

run_blas_pf_point() {
  local k=$1 lm=$2 M=${3:-32} groups=${4:-1}
  local s1 s2 yoff ptrs tag log_suffix rows macc

  note "########## Single BLAS LMUL point: ${k}_m${lm} M=$M ##########"
  rm -f "$APPS/$k/main.c.o"
  ( cd "$APPS" && timeout 600 make bin/$k blas_lmul=$lm ) > "$OUT/build_blaspf_${k}_${lm}.log" 2>&1
  s1=$(addr_of "$k" src1); s2=$(addr_of "$k" src2)
  if [ -z "$s1" ]; then
    echo "  $k m$lm: BUILD/ADDR FAIL"
    return 1
  fi
  yoff=$((lm*128))
  case "$k" in
    vssymv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$M" ;;
    vsgemv_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$((s2+yoff)) +HDV_A3=$M" ;;
    vstrsm_hdv) ptrs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$M" ;;
    *) return 1 ;;
  esac
  if { [ "$k" = "vssymv_hdv" ] || [ "$k" = "vsgemv_hdv" ]; } && [ "$groups" != "1" ]; then
    ptrs="$ptrs +HDV_A4=$groups"
  fi

  tag="${k}_m${lm}"
  log_suffix="${k}_${lm}_${M}"
  rows="$M"
  macc=$((M*lm*32))
  if { [ "$k" = "vssymv_hdv" ] || [ "$k" = "vsgemv_hdv" ]; } && [ "$groups" != "1" ]; then
    tag="${tag}_${groups}g"
    log_suffix="${log_suffix}_${groups}g"
    rows="$groups"
    macc=$((M*groups))
  fi
  echo "============== $k  m$lm  single LMUL point =============="
  printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
         "tag" "m$lm" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
  log="$OUT/log_blaspf_${log_suffix}.log"
  if [ "$k" = "vstrsm_hdv" ] &&
     { { [ "$lm" = "2" ] && [ "$M" -ge 64 ]; } ||
       { [ "$lm" = "4" ] && [ "$M" -ge 64 ]; } ||
       { [ "$lm" = "8" ] && [ "$M" -ge 32 ]; }; }; then
    timeout 3600 make sim app=$k \
      hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=800000" > "$log" 2>&1
  else
    timeout 600 make sim app=$k \
      hdv_plusargs="$ptrs +HDV_EXPECTED_EP=8000000" > "$log" 2>&1
  fi
  parse_blas_perf "$tag" "$lm" "$rows" "$M" "$macc"
}

run_vsgemm_point() {
  local lmul=$1 rows=$2 n=${3:-32}
  local tag="vsgemm_m${lmul}_${rows}r" s1 s2 macc

  if [ "$lmul" = "1" ] && [ "$rows" != "4" ] && [ "$n" != "32" ]; then
    echo "  $tag: invalid N=$n; m1 ${rows}r vsgemm is fixed 32x32x32."
    return 1
  fi
  if [ "$lmul" = "1" ] && [ "$rows" = "4" ] &&
     [ "$n" != "32" ] && [ "$n" != "64" ] && [ "$n" != "128" ]; then
    echo "  $tag: invalid N=$n; m1 4r vsgemm supports N=32/64/128."
    return 1
  fi

  note "########## Single vsgemm point: $tag N=$n ##########"
  rm -f "$APPS/vsgemm_hdv/main.c.o"
  ( cd "$APPS" && timeout 600 make bin/vsgemm_hdv gemm_lmul=$lmul gemm_rows=$rows gemm_n=$n ) \
    > "$OUT/build_${tag}.log" 2>&1
  s1=$(addr_of vsgemm_hdv src1); s2=$(addr_of vsgemm_hdv src2)
  if [ -z "$s1" ] || [ -z "$s2" ]; then
    echo "  $tag: BUILD/ADDR FAIL"
    return 1
  fi

  echo "==================== vsgemm single point ===================="
  printf "%-18s %-5s %-5s %-7s %-8s %-9s %-7s %-7s %-9s %s\n" \
         "tag" "N" "rows" "result" "cycles" "cyc/macc" "EPs" "vq_max" "pf_ar->hit" "seq_blk"
  log="$OUT/log_blas_${tag}_${n}.log"
  if { [ "$lmul" = "4" ] && [ "$rows" != "4" ] && [ "$n" -ge 64 ]; } ||
     { [ "$lmul" = "4" ] && [ "$rows" = "4" ] && [ "$n" -ge 128 ]; } ||
     { [ "$lmul" = "1" ] && [ "$rows" = "4" ] && [ "$n" -ge 64 ]; }; then
    timeout 3600 make sim app=vsgemm_hdv \
      hdv_plusargs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n +HDV_EXPECTED_EP=8000000 +HDV_TASK_WATCHDOG=1000000" \
      > "$log" 2>&1
  else
    timeout 600 make sim app=vsgemm_hdv \
      hdv_plusargs="+HDV_A0=$s1 +HDV_A1=$s2 +HDV_A2=$s1 +HDV_A3=$n +HDV_EXPECTED_EP=8000000" \
      > "$log" 2>&1
  fi
  if [ "$lmul" = "1" ] && [ "$rows" != "4" ]; then
    macc=32768
  else
    macc=$((n*n*n))
  fi
  parse_blas_perf "$tag" "$n" "$rows" "$n" "$macc"
}

run_point() {
  local name=$1 a=${2:-} b=${3:-} c=${4:-}
  if [ -z "$name" ]; then
    echo "usage: $0 point <kernel-or-tag> [avl|size|M|N] [extra]"
    return 1
  fi

  case "$name" in
    vsaxpy_hdv|vvaddint32_hdv|vscopy_hdv|vsswap_hdv|vsdot_hdv|vsscal_hdv|vmc_hdv|dropout_hdv|vsdwt_hdv|vstencil3_hdv|vfir5_hdv)
      run_1d_point "$name" "${a:-1024}"
      return
      ;;
    vsger_hdv|vssymv_hdv|vssyrk_hdv|vstrsm_hdv|vsgemv_hdv)
      run_blas_dim_point "$name" "${a:-32}"
      return
      ;;
    vssymv_hdv_m[248]|vsgemv_hdv_m[248]|vstrsm_hdv_m[248])
      local base=${name%_m[248]} lm=${name##*_m}
      run_blas_pf_point "$base" "$lm" "${a:-32}" "${b:-1}"
      return
      ;;
    vsgemm_m*_?r)
      if [[ "$name" =~ ^vsgemm_m([0-9]+)_([0-9]+)r$ ]]; then
        run_vsgemm_point "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "${a:-32}"
        return
      fi
      ;;
    vsgemm_hdv)
      run_vsgemm_point "${a:-4}" "${b:-1}" "${c:-32}"
      return
      ;;
    *_fix)
      run_fixed_named "$name"
      return
      ;;
  esac

  echo "unknown point '$name'"
  echo "examples:"
  echo "  $0 point vvaddint32_hdv 2048"
  echo "  $0 point lavamd_fix"
  echo "  $0 point vsgemm_m4_1r 128"
  echo "  $0 point vssyrk_hdv 128"
  echo "  $0 point vstrsm_hdv_m8 64"
  echo "  $0 point vsgemv_hdv_m4 128 8"
  echo "  $0 point vssymv_hdv_m4 128 8"
  return 1
}

case "$MODE" in
  all)
    run_1d_sweep "${ARG1:-32 64 128 256 512 1024 2048 4096}"
    sweep_blas_all "16 32 64 128"
    run_fixed_sweep
    ;;
  onepoint)
    run_onepoint_sweep
    ;;
  point)
    run_point "$ARG1" "$ARG2" "$ARG3" "$ARG4" || exit 1
    ;;
  1d)
    run_1d_sweep "${ARG1:-32 64 128 256 512 1024 2048 4096}"
    ;;
  kernel)
    if [ -z "$ARG1" ]; then
      echo "usage: $0 kernel <kernel_name> [avl-list]"
      exit 1
    fi
    run_1d_sweep "${ARG2:-32 64 128 256 512 1024 2048 4096}" "$ARG1"
    ;;
  blas)
    sweep_blas_all "${ARG1:-16 32 64 128}"
    ;;
  blas_dim)
    sweep_blas_dim "${ARG1:-16 32 64 128}"
    ;;
  blas_pf)
    sweep_blas_pf "${ARG1:-32 64}"
    ;;
  blas_groups)
    sweep_blas_groups "${ARG1:-128}" "${ARG2:-2 4 8}" "${ARG3:-4}"
    ;;
  vsgemm)
    sweep_vsgemm "${ARG1:-16 32 64 128}"
    ;;
  fixed)
    run_fixed_sweep
    ;;
  long)
    run_long_sweep
    ;;
  *)
    echo "usage: $0 {all|onepoint|point|1d|kernel|blas|blas_dim|blas_pf|blas_groups|vsgemm|fixed|long} [args]"
    exit 1
    ;;
esac

if [ "${KERNEL_SWEEP_NO_SUM:-0}" = "1" ]; then
  echo "  -> summary skipped (KERNEL_SWEEP_NO_SUM=1)"
else
  ./kernel_sweep_sum.sh "$OUT"
fi

echo ""
echo "==== output -> $OUT/ ===="
