// Generated by scripts/gen_akv_abi.py. Do not edit.
package akv_pkg;

`ifdef ARA_AKV_ENABLE
  localparam bit AkvEnable = 1'b1;
`else
  localparam bit AkvEnable = 1'b0;
`endif

`ifdef ARA_AKV_V2_ENABLE
  localparam bit AkvV2Enable = 1'b1;
`else
  localparam bit AkvV2Enable = 1'b0;
`endif

  localparam int unsigned AkvArchitectureVersion = 1;
  localparam int unsigned AkvDescriptorVersion = 1;
  localparam int unsigned AkvDescriptorBytes = 64;
  localparam int unsigned AkvDescriptorAlignmentLog2 = 6;
  localparam logic [6:0] AkvOpcodeCustom2 = 7'h5b;
  localparam logic [2:0] AkvFillFunct3 = 3'd2;
  localparam logic [2:0] AkvLoadFunct3 = 3'd3;
  localparam logic [2:0] AkvInfoFunct3 = 3'd4;
  localparam logic [2:0] AkvReleaseFunct3 = 3'd5;
  localparam int unsigned AkvV2ProfileVersion = 2;
  localparam int unsigned AkvV2TileTokens = 64;
  localparam int unsigned AkvV2TokenBanks = 8;
  localparam int unsigned AkvV2SelectorIndexBits = 6;
  localparam int unsigned AkvV2PayloadAlignmentLog2 =
      5;
  localparam logic [2:0] AkvV2FillFunct3 = 3'd6;
  localparam logic [2:0] AkvV2ColumnLoadFunct3 = 3'd7;
  localparam int unsigned AkvHeadDim64 = 64;
  localparam int unsigned AkvHeadDim96 = 96;
  localparam int unsigned AkvHeadDim128 = 128;
  localparam int unsigned AkvHeadDim256 = 256;
  localparam logic [6:0] AkvHeadDimCode64 = 7'd0;
  localparam logic [6:0] AkvHeadDimCode128 = 7'd1;
  localparam logic [6:0] AkvHeadDimCode96 = 7'd2;
  localparam int unsigned AkvV2DAxisTailCapabilityBit = 38;
  localparam int unsigned AkvV2D256SegmentedCapabilityBit = 39;
  localparam int unsigned AkvV2ColumnSegmentBit = 7;
  localparam int unsigned AkvContextCount = 1;
  localparam int unsigned AkvMaxQRows = 8;
  localparam int unsigned AkvTileTokens = 8;
  localparam int unsigned AkvMaxHeadDim = 128;
  localparam int unsigned AkvContextBytes =
      (AkvMaxQRows + 2 * AkvTileTokens) * AkvMaxHeadDim * 2;
  localparam int unsigned AkvV2ContextBytes =
      (AkvMaxQRows + 2 * AkvV2TileTokens) * AkvMaxHeadDim * 2;

  typedef enum logic [7:0] {
    AKV_ELEMENT_FORMAT_INVALID = 8'd0,
    AKV_ELEMENT_FORMAT_F16 = 8'd1
  } akv_element_format_e;

  typedef enum logic [1:0] {
    AKV_STREAM_Q = 2'd0,
    AKV_STREAM_K = 2'd1,
    AKV_STREAM_V = 2'd2
  } akv_stream_e;

  typedef enum logic {
    AKV_FILL_FULL = 1'b0,
    AKV_FILL_REFILL = 1'b1
  } akv_fill_mode_e;

  typedef enum logic [2:0] {
    AKV_COMMAND_FULL,
    AKV_COMMAND_REFILL,
    AKV_COMMAND_LOAD,
    AKV_COMMAND_RELEASE,
    AKV_COMMAND_V2_FULL,
    AKV_COMMAND_V2_REFILL,
    AKV_COMMAND_V2_COLUMN_LOAD
  } akv_command_e;

  typedef enum logic [4:0] {
    AKV_VALIDATION_OK,
    AKV_VALIDATION_COMMAND,
    AKV_VALIDATION_DESCRIPTOR_ALIGNMENT,
    AKV_VALIDATION_DESCRIPTOR_VERSION,
    AKV_VALIDATION_DESCRIPTOR_FORMAT,
    AKV_VALIDATION_Q_ROWS,
    AKV_VALIDATION_HEAD_DIM,
    AKV_VALIDATION_KV_LENGTH,
    AKV_VALIDATION_RESERVED,
    AKV_VALIDATION_STRIDE,
    AKV_VALIDATION_RANGE_OVERFLOW,
    AKV_VALIDATION_TILE_RANGE,
    AKV_VALIDATION_CONTEXT,
    AKV_VALIDATION_SELECTOR,
    AKV_VALIDATION_DESTINATION
  } akv_validation_error_e;

  typedef struct packed {
    logic [63:0] reserved2;
    logic [63:0] reserved1;
    logic [63:0] v_base;
    logic [63:0] k_base;
    logic [63:0] q_base;
    logic [31:0] reserved0;
    logic [31:0] v_token_stride_bytes;
    logic [31:0] k_token_stride_bytes;
    logic [31:0] q_row_stride_bytes;
    logic [15:0] kv_length;
    logic [15:0] head_dim;
    logic [7:0] flags;
    logic [7:0] q_rows;
    akv_element_format_e element_format;
    logic [7:0] version;
  } akv_descriptor_v1_t;

  function automatic logic [7:0] akv_head_dim_code(input int unsigned head_dim);
    unique case (head_dim)
      AkvHeadDim64: akv_head_dim_code = 8'(AkvHeadDimCode64);
      AkvHeadDim128: akv_head_dim_code = 8'(AkvHeadDimCode128);
      AkvHeadDim96: akv_head_dim_code = 8'(AkvHeadDimCode96);
      default: akv_head_dim_code = 8'hff;
    endcase
  endfunction : akv_head_dim_code

  function automatic logic [63:0] akv_capability_word(
      input logic [63:0] index, input bit enabled
  );
    akv_capability_word = '0;
    unique case (index)
      64'd0: akv_capability_word =
          64'(1) |
          (64'(1) << 8) |
          (64'(64) << 16) |
          (64'(8) << 24) |
          (64'(8) << 32) |
          (64'(1) << 40) |
          (64'(enabled) << 48) |
          (64'd1 << 49) | (64'd1 << 50) | (64'd1 << 51);
      64'd1: akv_capability_word =
          64'(AkvOpcodeCustom2) |
          (64'(AkvFillFunct3) << 8) |
          (64'(AkvLoadFunct3) << 11) |
          (64'(AkvInfoFunct3) << 14) |
          (64'(AkvReleaseFunct3) << 17) |
          (64'(AkvDescriptorAlignmentLog2) << 20);
      default: ;
    endcase
  endfunction : akv_capability_word

  function automatic logic [63:0] akv_v2_capability_word(
      input logic [63:0] index, input bit enabled
  );
    akv_v2_capability_word = '0;
    unique case (index)
      64'd2: akv_v2_capability_word =
          64'(2) |
          (64'(64) << 8) |
          (64'(8) << 16) |
          (64'(6) << 24) |
          (64'(enabled) << 32) |
          (64'd1 << 33) | (64'd1 << 34) | (64'd1 << 35) |
          (64'd1 << 36) | (64'd1 << 37) |
          (64'd1 << AkvV2DAxisTailCapabilityBit) |
          (64'd1 << AkvV2D256SegmentedCapabilityBit);
      64'd3: akv_v2_capability_word =
          64'(AkvOpcodeCustom2) |
          (64'(AkvV2FillFunct3) << 8) |
          (64'(AkvV2ColumnLoadFunct3) << 11) |
          (64'(AkvMaxHeadDim) << 16) |
          (64'd1 << 24);
      default: ;
    endcase
  endfunction : akv_v2_capability_word

endpackage : akv_pkg
