// Generated by scripts/gen_akv_abi.py. Do not edit.
package akv_pkg;

`ifdef AKV_ENABLE
  localparam bit AkvEnable = 1'b1;
`else
  localparam bit AkvEnable = 1'b0;
`endif

  localparam int unsigned AkvArchitectureVersion = 1;
  localparam int unsigned AkvDescriptorVersion = 1;
  localparam int unsigned AkvDescriptorBytes = 64;
  localparam int unsigned AkvDescriptorAlignmentLog2 = 6;
  localparam logic [6:0] AkvOpcodeCustom2 = 7'h5b;
  localparam logic [2:0] AkvFillFunct3 = 3'd2;
  localparam logic [2:0] AkvLoadFunct3 = 3'd3;
  localparam logic [2:0] AkvInfoFunct3 = 3'd4;
  localparam logic [2:0] AkvReleaseFunct3 = 3'd5;
  localparam int unsigned AkvContextCount = 1;
  localparam int unsigned AkvMaxQRows = 8;
  localparam int unsigned AkvTileTokens = 8;
  localparam int unsigned AkvMaxHeadDim = 128;
  localparam int unsigned AkvContextBytes =
      (AkvMaxQRows + 2 * AkvTileTokens) * AkvMaxHeadDim * 2;

  typedef enum logic [7:0] {
    AKV_ELEMENT_FORMAT_INVALID = 8'd0,
    AKV_ELEMENT_FORMAT_F16 = 8'd1
  } akv_element_format_e;

  typedef enum logic [1:0] {
    AKV_STREAM_Q = 2'd0,
    AKV_STREAM_K = 2'd1,
    AKV_STREAM_V = 2'd2
  } akv_stream_e;

  typedef enum logic {
    AKV_FILL_FULL = 1'b0,
    AKV_FILL_REFILL = 1'b1
  } akv_fill_mode_e;

  typedef struct packed {
    logic [63:0] reserved2;
    logic [63:0] reserved1;
    logic [63:0] v_base;
    logic [63:0] k_base;
    logic [63:0] q_base;
    logic [31:0] reserved0;
    logic [31:0] v_token_stride_bytes;
    logic [31:0] k_token_stride_bytes;
    logic [31:0] q_row_stride_bytes;
    logic [15:0] kv_length;
    logic [15:0] head_dim;
    logic [7:0] flags;
    logic [7:0] q_rows;
    akv_element_format_e element_format;
    logic [7:0] version;
  } akv_descriptor_v1_t;

  function automatic logic [7:0] akv_head_dim_code(input int unsigned head_dim);
    unique case (head_dim)
      64: akv_head_dim_code = 8'd0;
      128: akv_head_dim_code = 8'd1;
      default: akv_head_dim_code = 8'hff;
    endcase
  endfunction : akv_head_dim_code

  function automatic logic [63:0] akv_capability_word(
      input logic [63:0] index, input bit enabled
  );
    akv_capability_word = '0;
    unique case (index)
      64'd0: akv_capability_word =
          64'(1) |
          (64'(1) << 8) |
          (64'(64) << 16) |
          (64'(8) << 24) |
          (64'(8) << 32) |
          (64'(1) << 40) |
          (64'(enabled) << 48) |
          (64'd1 << 49) | (64'd1 << 50) | (64'd1 << 51);
      64'd1: akv_capability_word =
          64'(AkvOpcodeCustom2) |
          (64'(AkvFillFunct3) << 8) |
          (64'(AkvLoadFunct3) << 11) |
          (64'(AkvInfoFunct3) << 14) |
          (64'(AkvReleaseFunct3) << 17) |
          (64'(AkvDescriptorAlignmentLog2) << 20);
      default: ;
    endcase
  endfunction : akv_capability_word

endpackage : akv_pkg
