// Generated by scripts/gen_qbs_abi.py. Do not edit.
package qbs_pkg;

`ifdef ARA_QBS_ENABLE
  localparam bit QbsEnable = 1'b1;
`else
  localparam bit QbsEnable = 1'b0;
`endif

  localparam int unsigned QbsArchitectureVersion = 1;
  localparam int unsigned QbsNumericalContractVersion = 1;
  localparam int unsigned QbsDescriptorVersion = 1;
  localparam int unsigned QbsDescriptorBytes = 16;
  localparam int unsigned QbsDescriptorAlignmentLog2 = 4;

  localparam logic [6:0] QbsOpcodeCustom2 = 7'h5b;
  localparam logic [2:0] QbsQbexecFunct3 = 3'd0;
  localparam logic [2:0] QbsQbinfoFunct3 = 3'd1;

  localparam int unsigned QbsMaxM = 4;
  localparam int unsigned QbsMaxN = 32;
  localparam int unsigned QbsMaxKBlocks = 64;
  localparam int unsigned QbsBlockElements = 256;
  localparam int unsigned QbsWeightBaseAlignmentLog2 = 1;
  localparam int unsigned QbsActivationBaseAlignmentLog2 = 2;

  localparam int unsigned QbsQ4KBlockBytes = 144;
  localparam int unsigned QbsQ4KSubgroupCount = 8;
  localparam int unsigned QbsQ4KSubgroupElements = 32;
  localparam int unsigned QbsQ6KBlockBytes = 210;
  localparam int unsigned QbsQ6KSubgroupCount = 16;
  localparam int unsigned QbsQ6KSubgroupElements = 16;
  localparam int unsigned QbsQ8KBlockBytes = 292;
  localparam int unsigned QbsQ8KBsumsCount = 16;

  typedef enum logic [3:0] {
    QBS_WEIGHT_PROFILE_INVALID = 4'd0,
    QBS_WEIGHT_PROFILE_Q4_K = 4'd1,
    QBS_WEIGHT_PROFILE_Q6_K = 4'd2
  } qbs_weight_profile_e;

  typedef enum logic [3:0] {
    QBS_ACTIVATION_PROFILE_INVALID = 4'd0,
    QBS_ACTIVATION_PROFILE_Q8_K = 4'd1
  } qbs_activation_profile_e;

  typedef enum logic [3:0] {
    QBS_WEIGHT_LAYOUT_INVALID = 4'd0,
    QBS_WEIGHT_LAYOUT_ROW_MAJOR = 4'd1,
    QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR = 4'd2
  } qbs_weight_layout_e;

  typedef enum logic [3:0] {
    QBS_ACTIVATION_LAYOUT_INVALID = 4'd0,
    QBS_ACTIVATION_LAYOUT_ROW_MAJOR = 4'd1,
    QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED = 4'd2
  } qbs_activation_layout_e;

  // Internal validation result. These values are not software-visible ABI;
  // they make directed RTL checks and command fault attribution unambiguous.
  typedef enum logic [4:0] {
    QBS_VALIDATION_OK = 5'd0,
    QBS_VALIDATION_DESCRIPTOR_ALIGNMENT = 5'd1,
    QBS_VALIDATION_DESCRIPTOR_VERSION = 5'd2,
    QBS_VALIDATION_DESCRIPTOR_RESERVED = 5'd3,
    QBS_VALIDATION_WEIGHT_PROFILE = 5'd4,
    QBS_VALIDATION_ACTIVATION_PROFILE = 5'd5,
    QBS_VALIDATION_WEIGHT_LAYOUT = 5'd6,
    QBS_VALIDATION_ACTIVATION_LAYOUT = 5'd7,
    QBS_VALIDATION_M_RANGE = 5'd8,
    QBS_VALIDATION_N_RANGE = 5'd9,
    QBS_VALIDATION_K_RANGE = 5'd10,
    QBS_VALIDATION_VD_ALIGNMENT = 5'd11,
    QBS_VALIDATION_WEIGHT_ALIGNMENT = 5'd12,
    QBS_VALIDATION_ACTIVATION_ALIGNMENT = 5'd13,
    QBS_VALIDATION_WEIGHT_RANGE_OVERFLOW = 5'd14,
    QBS_VALIDATION_ACTIVATION_RANGE_OVERFLOW = 5'd15
  } qbs_validation_error_e;

  // Internal read-path fault attribution. These values are not part of the
  // software ABI; the QBS command controller maps them to architectural
  // load exceptions only after the current AXI response has been drained.
  typedef enum logic [2:0] {
    QBS_READ_FAULT_NONE = 3'd0,
    QBS_READ_FAULT_REQUEST = 3'd1,
    QBS_READ_FAULT_MMU = 3'd2,
    QBS_READ_FAULT_AXI_RESPONSE = 3'd3,
    QBS_READ_FAULT_AXI_PROTOCOL = 3'd4,
    QBS_READ_FAULT_PMA = 3'd5
  } qbs_read_fault_e;

  typedef struct packed {
    logic [63:0] weight_base;
    logic [63:0] header;
  } qbs_descriptor_v1_t;

  localparam int unsigned QbsDescVersionLsb = 0;
  localparam int unsigned QbsDescWeightProfileLsb = 4;
  localparam int unsigned QbsDescActivationProfileLsb = 8;
  localparam int unsigned QbsDescWeightLayoutLsb = 12;
  localparam int unsigned QbsDescActivationLayoutLsb = 16;
  localparam int unsigned QbsDescNMinus1Lsb = 20;
  localparam int unsigned QbsDescKBlocksMinus1Lsb = 25;
  localparam int unsigned QbsDescReservedLsb = 33;

  function automatic logic [63:0] qbs_capability_word(
      input logic [63:0] index,
      input int unsigned vlen_bits
  );
    int unsigned max_n;
    logic [63:0] result;
    max_n = vlen_bits / 32;
    if (max_n > QbsMaxN) max_n = QbsMaxN;
    result = '0;
    unique case (index)
      64'h00: begin
        if (max_n != 0) begin
          result[7:0]   = 8'(QbsArchitectureVersion);
          result[15:8]  = 8'(QbsDescriptorVersion);
          result[23:16] = 8'(QbsDescriptorBytes);
          result[25:24] = 2'(QbsMaxM - 1);
          result[30:26] = 5'(max_n - 1);
          result[38:31] = 8'(QbsMaxKBlocks - 1);
          result[42:39] = 4'(QbsNumericalContractVersion);
          result[47:43] = 5'b1_1111;
        end
      end
      64'h01: begin
        result[QBS_WEIGHT_LAYOUT_ROW_MAJOR] = 1'b1;
        result[QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR] = 1'b1;
        result[16 + QBS_ACTIVATION_LAYOUT_ROW_MAJOR] = 1'b1;
        result[16 + QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED] = 1'b1;
        result[39:32] = 8'(QbsDescriptorAlignmentLog2);
        result[47:40] = 8'(QbsWeightBaseAlignmentLog2);
        result[55:48] = 8'(QbsActivationBaseAlignmentLog2);
        result[63:56] = 8'd32;
      end
      64'h11,
      64'h12:
        result[QBS_ACTIVATION_PROFILE_Q8_K] = 1'b1;
      64'h21: begin
        result[15:0]  = 16'(QbsQ4KBlockBytes);
        result[31:16] = 16'(QbsBlockElements);
        result[39:32] = 8'(QbsQ4KSubgroupCount);
        result[47:40] = 8'(QbsQ4KSubgroupElements);
      end
      64'h22: begin
        result[15:0]  = 16'(QbsQ6KBlockBytes);
        result[31:16] = 16'(QbsBlockElements);
        result[39:32] = 8'(QbsQ6KSubgroupCount);
        result[47:40] = 8'(QbsQ6KSubgroupElements);
      end
      64'h31: begin
        result[15:0]  = 16'(QbsQ8KBlockBytes);
        result[31:16] = 16'(QbsBlockElements);
        result[39:32] = 8'(QbsQ8KBsumsCount);
      end
      default: ;
    endcase
    return result;
  endfunction : qbs_capability_word

endpackage : qbs_pkg
