/* Generated by scripts/gen_akv_abi.py. Do not edit. */
#ifndef AKV_ABI_H
#define AKV_ABI_H

#include <stddef.h>
#include <stdint.h>

#define AKV_ARCHITECTURE_VERSION 1u
#define AKV_DESCRIPTOR_VERSION 1u
#define AKV_DESCRIPTOR_BYTES 64u
#define AKV_DESCRIPTOR_ALIGNMENT_LOG2 6u
#define AKV_OPCODE_CUSTOM2 0x5bu
#define AKV_FILL_FUNCT3 2u
#define AKV_LOAD_FUNCT3 3u
#define AKV_INFO_FUNCT3 4u
#define AKV_RELEASE_FUNCT3 5u
#define AKV_CONTEXT_COUNT 1u
#define AKV_MAX_Q_ROWS 8u
#define AKV_TILE_TOKENS 8u
#define AKV_V2_PROFILE_VERSION 2u
#define AKV_V2_TILE_TOKENS 64u
#define AKV_V2_TOKEN_BANKS 8u
#define AKV_V2_SELECTOR_INDEX_BITS 6u
#define AKV_V2_FILL_FUNCT3 6u
#define AKV_V2_COLUMN_LOAD_FUNCT3 7u
#define AKV_HEAD_DIM_64 64u
#define AKV_HEAD_DIM_96 96u
#define AKV_HEAD_DIM_128 128u
#define AKV_HEAD_DIM_256 256u
#define AKV_HEAD_DIM_CODE_64 0u
#define AKV_HEAD_DIM_CODE_128 1u
#define AKV_HEAD_DIM_CODE_96 2u
#define AKV_HEAD_DIM_CODE_INVALID 0xffu
#define AKV_V2_D_AXIS_TAIL_CAPABILITY_BIT 38u
#define AKV_V2_D256_SEGMENTED_CAPABILITY_BIT 39u
#define AKV_V2_COLUMN_SEGMENT_BIT 7u

typedef enum {
  AKV_ELEMENT_FORMAT_INVALID = 0,
  AKV_ELEMENT_FORMAT_F16 = 1,
} akv_element_format_t;

typedef enum {
  AKV_STREAM_Q = 0,
  AKV_STREAM_K = 1,
  AKV_STREAM_V = 2,
} akv_stream_t;

typedef enum {
  AKV_FILL_FULL = 0,
  AKV_FILL_REFILL = 1,
} akv_fill_mode_t;

typedef struct __attribute__((aligned(AKV_DESCRIPTOR_BYTES))) {
  uint8_t version;
  uint8_t element_format;
  uint8_t q_rows;
  uint8_t flags;
  uint16_t head_dim;
  uint16_t kv_length;
  uint32_t q_row_stride_bytes;
  uint32_t k_token_stride_bytes;
  uint32_t v_token_stride_bytes;
  uint32_t reserved0;
  uint64_t q_base;
  uint64_t k_base;
  uint64_t v_base;
  uint64_t reserved1;
  uint64_t reserved2;
} akv_descriptor_t;

#if defined(__cplusplus)
static_assert(sizeof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
              "AKV descriptor size mismatch");
static_assert(alignof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
              "AKV descriptor alignment mismatch");
#else
_Static_assert(sizeof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
               "AKV descriptor size mismatch");
_Static_assert(_Alignof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
               "AKV descriptor alignment mismatch");
#endif

static inline uint32_t akv_head_dim_code(uint32_t head_dim) {
  if (head_dim == AKV_HEAD_DIM_64) return AKV_HEAD_DIM_CODE_64;
  if (head_dim == AKV_HEAD_DIM_128) return AKV_HEAD_DIM_CODE_128;
  if (head_dim == AKV_HEAD_DIM_96) return AKV_HEAD_DIM_CODE_96;
  return AKV_HEAD_DIM_CODE_INVALID;
}

static inline uint32_t akv_destination_registers(uint32_t head_dim) {
  if (head_dim == AKV_HEAD_DIM_64) return 1u;
  if (head_dim == AKV_HEAD_DIM_96 || head_dim == AKV_HEAD_DIM_128) return 2u;
  return 0u;
}

static inline uint32_t akv_tile_length(uint32_t kv_length,
                                       uint32_t tile_start) {
  if (tile_start >= kv_length) return 0u;
  const uint32_t remaining = kv_length - tile_start;
  return remaining < AKV_TILE_TOKENS ? remaining : AKV_TILE_TOKENS;
}

static inline uint32_t akv_v2_tile_length(uint32_t kv_length,
                                          uint32_t tile_start) {
  if (tile_start >= kv_length) return 0u;
  const uint32_t remaining = kv_length - tile_start;
  return remaining < AKV_V2_TILE_TOKENS ? remaining : AKV_V2_TILE_TOKENS;
}

static inline uint32_t akv_selector(akv_stream_t stream, uint32_t index) {
  if ((uint32_t)stream > (uint32_t)AKV_STREAM_V || index >= 8u)
    return UINT32_MAX;
  return (uint32_t)stream | (index << 2);
}

static inline uint32_t akv_selector_stream(uint32_t selector) {
  return selector & 0x3u;
}

static inline uint32_t akv_selector_index(uint32_t selector) {
  return (selector >> 2) & 0x7u;
}

static inline uint32_t akv_v2_selector(akv_stream_t stream, uint32_t index) {
  if ((uint32_t)stream > (uint32_t)AKV_STREAM_V ||
      index >= AKV_V2_TILE_TOKENS)
    return UINT32_MAX;
  return (uint32_t)stream | (index << 2);
}

static inline uint32_t akv_v2_selector_index(uint32_t selector) {
  return (selector >> 2) & ((1u << AKV_V2_SELECTOR_INDEX_BITS) - 1u);
}

static inline uint32_t akv_v2_column_selector(uint32_t segment,
                                               uint32_t dimension) {
  if (segment >= 2u || dimension >= AKV_HEAD_DIM_128)
    return UINT32_MAX;
  return (segment << AKV_V2_COLUMN_SEGMENT_BIT) | dimension;
}

static inline uint32_t akv_v2_column_segment(uint32_t selector) {
  return (selector >> AKV_V2_COLUMN_SEGMENT_BIT) & 1u;
}

static inline uint32_t akv_v2_column_dimension(uint32_t selector) {
  return selector & ((1u << AKV_V2_COLUMN_SEGMENT_BIT) - 1u);
}

static inline int akv_range_fits(uint64_t base, uint32_t stride,
                                 uint32_t count, uint32_t row_bytes) {
  if (count == 0u || row_bytes == 0u) return 0;
  const uint64_t last = (uint64_t)(count - 1u) * stride;
  return last <= UINT64_MAX - base &&
         (uint64_t)(row_bytes - 1u) <= UINT64_MAX - (base + last);
}

static inline int akv_descriptor_common_is_valid(
    const void *descriptor_address, int allow_d96) {
  if (descriptor_address == NULL ||
      ((uintptr_t)descriptor_address & (AKV_DESCRIPTOR_BYTES - 1u)) != 0u)
    return 0;
  const akv_descriptor_t *descriptor =
      (const akv_descriptor_t *)descriptor_address;
  if (descriptor->version != AKV_DESCRIPTOR_VERSION ||
      descriptor->element_format != AKV_ELEMENT_FORMAT_F16 ||
      descriptor->q_rows == 0u || descriptor->q_rows > AKV_MAX_Q_ROWS ||
      (descriptor->head_dim != AKV_HEAD_DIM_64 &&
       descriptor->head_dim != AKV_HEAD_DIM_128 &&
       (!allow_d96 || descriptor->head_dim != AKV_HEAD_DIM_96)) ||
      descriptor->kv_length == 0u || descriptor->flags != 0u ||
      descriptor->reserved0 != 0u || descriptor->reserved1 != 0u ||
      descriptor->reserved2 != 0u)
    return 0;
  const uint32_t row_bytes = (uint32_t)descriptor->head_dim * 2u;
  if (descriptor->q_row_stride_bytes < row_bytes ||
      descriptor->k_token_stride_bytes < row_bytes ||
      descriptor->v_token_stride_bytes < row_bytes ||
      ((descriptor->q_base | descriptor->k_base | descriptor->v_base |
        descriptor->q_row_stride_bytes | descriptor->k_token_stride_bytes |
        descriptor->v_token_stride_bytes) & UINT64_C(1)) != 0u)
    return 0;
  return akv_range_fits(descriptor->q_base,
                        descriptor->q_row_stride_bytes,
                        descriptor->q_rows, row_bytes) &&
         akv_range_fits(descriptor->k_base,
                        descriptor->k_token_stride_bytes,
                        descriptor->kv_length, row_bytes) &&
         akv_range_fits(descriptor->v_base,
                        descriptor->v_token_stride_bytes,
                        descriptor->kv_length, row_bytes);
}

static inline int akv_descriptor_is_valid(const void *descriptor_address) {
  return akv_descriptor_common_is_valid(descriptor_address, 0);
}

static inline int akv_v2_descriptor_is_valid(
    const void *descriptor_address) {
  if (!akv_descriptor_common_is_valid(descriptor_address, 1)) return 0;
  const akv_descriptor_t *descriptor =
      (const akv_descriptor_t *)descriptor_address;
  return ((descriptor->q_base | descriptor->k_base | descriptor->v_base |
           descriptor->q_row_stride_bytes |
           descriptor->k_token_stride_bytes |
           descriptor->v_token_stride_bytes) & UINT64_C(31)) == 0u;
}

static inline int akv_load_selector_is_valid(const akv_descriptor_t *descriptor,
                                              uint32_t tile_length,
                                              uint32_t selector) {
  if (!akv_descriptor_is_valid(descriptor) || (selector >> 5) != 0u)
    return 0;
  const uint32_t stream = akv_selector_stream(selector);
  const uint32_t index = akv_selector_index(selector);
  if (stream == AKV_STREAM_Q) return index < descriptor->q_rows;
  if (stream == AKV_STREAM_K || stream == AKV_STREAM_V)
    return index < tile_length && tile_length <= AKV_TILE_TOKENS;
  return 0;
}

static inline int akv_v2_row_selector_is_valid(
    const akv_descriptor_t *descriptor, uint32_t tile_length,
    uint32_t selector) {
  if (!akv_v2_descriptor_is_valid(descriptor) ||
      (selector >> (2u + AKV_V2_SELECTOR_INDEX_BITS)) != 0u ||
      tile_length == 0u || tile_length > AKV_V2_TILE_TOKENS)
    return 0;
  const uint32_t stream = akv_selector_stream(selector);
  const uint32_t index = akv_v2_selector_index(selector);
  if (stream == AKV_STREAM_Q) return index < descriptor->q_rows;
  if (stream == AKV_STREAM_K || stream == AKV_STREAM_V)
    return index < tile_length;
  return 0;
}

static inline int akv_v2_column_is_valid(
    const akv_descriptor_t *descriptor, uint32_t tile_length,
    uint32_t selector) {
  return akv_v2_descriptor_is_valid(descriptor) && tile_length != 0u &&
         tile_length <= AKV_V2_TILE_TOKENS &&
         (selector >> (AKV_V2_COLUMN_SEGMENT_BIT + 1u)) == 0u &&
         akv_v2_column_dimension(selector) < descriptor->head_dim;
}

static inline uint64_t akv_capability_word(uint64_t index, int enabled) {
  if (index == 0u)
    return (uint64_t)AKV_ARCHITECTURE_VERSION |
           ((uint64_t)AKV_DESCRIPTOR_VERSION << 8) |
           ((uint64_t)AKV_DESCRIPTOR_BYTES << 16) |
           ((uint64_t)AKV_MAX_Q_ROWS << 24) |
           ((uint64_t)AKV_TILE_TOKENS << 32) |
           ((uint64_t)AKV_CONTEXT_COUNT << 40) |
           ((uint64_t)(enabled != 0) << 48) |
           (UINT64_C(1) << 49) | (UINT64_C(1) << 50) |
           (UINT64_C(1) << 51);
  if (index == 1u)
    return (uint64_t)AKV_OPCODE_CUSTOM2 |
           ((uint64_t)AKV_FILL_FUNCT3 << 8) |
           ((uint64_t)AKV_LOAD_FUNCT3 << 11) |
           ((uint64_t)AKV_INFO_FUNCT3 << 14) |
           ((uint64_t)AKV_RELEASE_FUNCT3 << 17) |
           ((uint64_t)AKV_DESCRIPTOR_ALIGNMENT_LOG2 << 20);
  return UINT64_C(0);
}

static inline uint64_t akv_v2_capability_word(uint64_t index, int enabled) {
  if (index == 2u)
    return (uint64_t)AKV_V2_PROFILE_VERSION |
           ((uint64_t)AKV_V2_TILE_TOKENS << 8) |
           ((uint64_t)AKV_V2_TOKEN_BANKS << 16) |
           ((uint64_t)AKV_V2_SELECTOR_INDEX_BITS << 24) |
           ((uint64_t)(enabled != 0) << 32) |
           (UINT64_C(1) << 33) | (UINT64_C(1) << 34) |
           (UINT64_C(1) << 35) | (UINT64_C(1) << 36) |
           (UINT64_C(1) << 37) |
           (UINT64_C(1) << AKV_V2_D_AXIS_TAIL_CAPABILITY_BIT) |
           (UINT64_C(1) << AKV_V2_D256_SEGMENTED_CAPABILITY_BIT);
  if (index == 3u)
    return (uint64_t)AKV_OPCODE_CUSTOM2 |
           ((uint64_t)AKV_V2_FILL_FUNCT3 << 8) |
           ((uint64_t)AKV_V2_COLUMN_LOAD_FUNCT3 << 11) |
           ((uint64_t)AKV_HEAD_DIM_128 << 16) |
           (UINT64_C(1) << 24);
  return UINT64_C(0);
}

static inline uint32_t akv_encode_r(uint32_t funct3, uint32_t funct7,
                                    uint32_t rd, uint32_t rs1,
                                    uint32_t rs2) {
  return ((funct7 & 0x7fu) << 25) | ((rs2 & 0x1fu) << 20) |
         ((rs1 & 0x1fu) << 15) | ((funct3 & 0x7u) << 12) |
         ((rd & 0x1fu) << 7) | AKV_OPCODE_CUSTOM2;
}

static inline uint32_t akv_encode_fill(uint32_t descriptor_rs1,
                                       uint32_t tile_start_rs2,
                                       akv_fill_mode_t mode) {
  return akv_encode_r(AKV_FILL_FUNCT3, (uint32_t)mode, 0u,
                      descriptor_rs1, tile_start_rs2);
}

static inline uint32_t akv_encode_load(uint32_t vd, uint32_t selector_rs1,
                                       uint32_t head_dim) {
  return akv_encode_r(AKV_LOAD_FUNCT3, akv_head_dim_code(head_dim), vd,
                      selector_rs1, 0u);
}

static inline uint32_t akv_encode_info(uint32_t rd, uint32_t index_rs1) {
  return akv_encode_r(AKV_INFO_FUNCT3, 0u, rd, index_rs1, 0u);
}

static inline uint32_t akv_encode_release(void) {
  return akv_encode_r(AKV_RELEASE_FUNCT3, 0u, 0u, 0u, 0u);
}

static inline uint32_t akv_encode_v2_fill(uint32_t descriptor_rs1,
                                          uint32_t tile_start_rs2,
                                          akv_fill_mode_t mode) {
  return akv_encode_r(AKV_V2_FILL_FUNCT3, (uint32_t)mode, 0u,
                      descriptor_rs1, tile_start_rs2);
}

static inline uint32_t akv_encode_v2_column_load(uint32_t vd,
                                                 uint32_t dimension_rs1) {
  return akv_encode_r(AKV_V2_COLUMN_LOAD_FUNCT3, 0u, vd,
                      dimension_rs1, 0u);
}

#endif
