/* Generated by scripts/gen_qbs_abi.py. Do not edit. */
#ifndef ARA_QBS_ABI_H_
#define ARA_QBS_ABI_H_

#include <stddef.h>
#include <stdint.h>

#define QBS_EXTENSION_NAME "Xaraqbs"
#define QBS_ARCH_VERSION 3u
#define QBS_NUMERICAL_CONTRACT_VERSION 1u
#define QBS_ROUNDING_MODE_RNE 0u
#define QBS_NUMERICAL_ROUNDING_MODE QBS_ROUNDING_MODE_RNE
#define QBS_NUMERICAL_USES_DYNAMIC_FRM 0u
#define QBS_DESCRIPTOR_VERSION 2u
#define QBS_DESCRIPTOR_BYTES 16u
#define QBS_DESCRIPTOR_ALIGNMENT_LOG2 4u

#define QBS_OPCODE_CUSTOM2 0x5bu
#define QBS_QBEXEC_FUNCT3 0u
#define QBS_QBINFO_FUNCT3 1u
#define QBS_M_MINUS_ONE_BITS 3u

#define QBS_MAX_M 8u
#define QBS_MAX_N 32u
#define QBS_MAX_RESULTS 128u
#define QBS_WIDE_M_MIN 5u
#define QBS_WIDE_M_MAX_N 16u
#define QBS_WIDE_M_MIN_INPUT_REDUCTION_PERCENT 15u
#define QBS_MAX_K_BLOCKS 256u
/* Compatibility alias for numerical-contract v1 K-quant profiles. */
#define QBS_BLOCK_ELEMENTS 256u
#define QBS_WEIGHT_BASE_ALIGNMENT_LOG2 1u
#define QBS_ACTIVATION_BASE_ALIGNMENT_LOG2 2u
#define QBS_ACTIVATION_CONTEXT_COUNT 1u
#define QBS_ACTIVATION_CONTEXT_MAX_M 1u
#define QBS_ACTIVATION_CONTEXT_MAX_K_BLOCKS 16u
#define QBS_ACTIVATION_CONTEXT_GENERATION_BITS 8u

typedef enum {
  QBS_SCALE_INVALID = 0,
  QBS_SCALE_FP16 = 1,
  QBS_SCALE_FP32 = 2,
} qbs_scale_format_t;

typedef enum {
  QBS_CORRECTION_NONE = 0,
  QBS_CORRECTION_AFFINE_MIN = 1,
} qbs_correction_mode_t;

#define QBS_MAX_WEIGHT_BLOCK_BYTES 210u
#define QBS_MAX_ACTIVATION_BLOCK_BYTES 292u
#define QBS_Q4_K_BLOCK_BYTES 144u
#define QBS_Q4_K_BLOCK_ELEMENTS 256u
#define QBS_Q4_K_SUBGROUP_COUNT 8u
#define QBS_Q4_K_SUBGROUP_ELEMENTS 32u
#define QBS_Q4_K_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q4_K_CORRECTION_MODE QBS_CORRECTION_AFFINE_MIN
#define QBS_Q5_K_BLOCK_BYTES 176u
#define QBS_Q5_K_BLOCK_ELEMENTS 256u
#define QBS_Q5_K_SUBGROUP_COUNT 8u
#define QBS_Q5_K_SUBGROUP_ELEMENTS 32u
#define QBS_Q5_K_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q5_K_CORRECTION_MODE QBS_CORRECTION_AFFINE_MIN
#define QBS_Q6_K_BLOCK_BYTES 210u
#define QBS_Q6_K_BLOCK_ELEMENTS 256u
#define QBS_Q6_K_SUBGROUP_COUNT 16u
#define QBS_Q6_K_SUBGROUP_ELEMENTS 16u
#define QBS_Q6_K_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q6_K_CORRECTION_MODE QBS_CORRECTION_NONE
#define QBS_Q3_K_BLOCK_BYTES 110u
#define QBS_Q3_K_BLOCK_ELEMENTS 256u
#define QBS_Q3_K_SUBGROUP_COUNT 16u
#define QBS_Q3_K_SUBGROUP_ELEMENTS 16u
#define QBS_Q3_K_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q3_K_CORRECTION_MODE QBS_CORRECTION_NONE
#define QBS_Q8_0_WEIGHT_BLOCK_BYTES 34u
#define QBS_Q8_0_WEIGHT_BLOCK_ELEMENTS 32u
#define QBS_Q8_0_WEIGHT_SUBGROUP_COUNT 1u
#define QBS_Q8_0_WEIGHT_SUBGROUP_ELEMENTS 32u
#define QBS_Q8_0_WEIGHT_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q8_0_WEIGHT_CORRECTION_MODE QBS_CORRECTION_NONE
#define QBS_Q4_0_BLOCK_BYTES 18u
#define QBS_Q4_0_BLOCK_ELEMENTS 32u
#define QBS_Q4_0_SUBGROUP_COUNT 1u
#define QBS_Q4_0_SUBGROUP_ELEMENTS 32u
#define QBS_Q4_0_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q4_0_CORRECTION_MODE QBS_CORRECTION_NONE
#define QBS_Q2_K_BLOCK_BYTES 84u
#define QBS_Q2_K_BLOCK_ELEMENTS 256u
#define QBS_Q2_K_SUBGROUP_COUNT 16u
#define QBS_Q2_K_SUBGROUP_ELEMENTS 16u
#define QBS_Q2_K_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q2_K_CORRECTION_MODE QBS_CORRECTION_AFFINE_MIN
#define QBS_Q5_0_BLOCK_BYTES 22u
#define QBS_Q5_0_BLOCK_ELEMENTS 32u
#define QBS_Q5_0_SUBGROUP_COUNT 1u
#define QBS_Q5_0_SUBGROUP_ELEMENTS 32u
#define QBS_Q5_0_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q5_0_CORRECTION_MODE QBS_CORRECTION_NONE
#define QBS_IQ4_NL_BLOCK_BYTES 18u
#define QBS_IQ4_NL_BLOCK_ELEMENTS 32u
#define QBS_IQ4_NL_SUBGROUP_COUNT 1u
#define QBS_IQ4_NL_SUBGROUP_ELEMENTS 32u
#define QBS_IQ4_NL_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_IQ4_NL_CORRECTION_MODE QBS_CORRECTION_NONE
#define QBS_Q8_K_BLOCK_BYTES 292u
#define QBS_Q8_K_BLOCK_ELEMENTS 256u
#define QBS_Q8_K_SCALE_FORMAT QBS_SCALE_FP32
#define QBS_Q8_K_SCALE_BYTES 4u
#define QBS_Q8_K_QUANT_BYTES 256u
#define QBS_Q8_K_AUX_COUNT 16u
#define QBS_Q8_K_AUX_ELEMENT_BYTES 2u
#define QBS_Q8_K_BSUMS_COUNT 16u
#define QBS_Q8_0_BLOCK_BYTES 34u
#define QBS_Q8_0_BLOCK_ELEMENTS 32u
#define QBS_Q8_0_SCALE_FORMAT QBS_SCALE_FP16
#define QBS_Q8_0_SCALE_BYTES 2u
#define QBS_Q8_0_QUANT_BYTES 32u
#define QBS_Q8_0_AUX_COUNT 0u
#define QBS_Q8_0_AUX_ELEMENT_BYTES 0u

/* Stable software format contracts. These IDs are independent of the 4-bit hardware profile encoding. */
#define QBS_WEIGHT_ENCODING_Q4_K UINT64_C(0x5142535701000001)
#define QBS_WEIGHT_ENCODING_Q5_K UINT64_C(0x5142535701000002)
#define QBS_WEIGHT_ENCODING_Q6_K UINT64_C(0x5142535701000003)
#define QBS_WEIGHT_ENCODING_Q3_K UINT64_C(0x5142535701000004)
#define QBS_WEIGHT_ENCODING_Q8_0_WEIGHT UINT64_C(0x5142535701000005)
#define QBS_WEIGHT_ENCODING_S8_B32_F16_TWOS_COMPLEMENT QBS_WEIGHT_ENCODING_Q8_0_WEIGHT
#define QBS_WEIGHT_ENCODING_Q4_0 UINT64_C(0x5142535701000006)
#define QBS_WEIGHT_ENCODING_S4_B32_F16_SPLIT_NIBBLE_OFFSET8 QBS_WEIGHT_ENCODING_Q4_0
#define QBS_WEIGHT_ENCODING_Q2_K UINT64_C(0x5142535701000007)
#define QBS_WEIGHT_ENCODING_Q5_0 UINT64_C(0x5142535701000008)
#define QBS_WEIGHT_ENCODING_S5_B32_F16_NIBBLE_HIGHBIT_OFFSET16 QBS_WEIGHT_ENCODING_Q5_0
#define QBS_WEIGHT_ENCODING_IQ4_NL UINT64_C(0x5142535701000009)
#define QBS_ACTIVATION_ENCODING_Q8_K UINT64_C(0x5142534101000001)
#define QBS_ACTIVATION_ENCODING_S8_B256_F32_BSUM16_I16 QBS_ACTIVATION_ENCODING_Q8_K
#define QBS_ACTIVATION_ENCODING_Q8_0 UINT64_C(0x5142534101000002)
#define QBS_ACTIVATION_ENCODING_S8_B32_F16_TWOS_COMPLEMENT QBS_ACTIVATION_ENCODING_Q8_0

typedef enum {
  QBS_WEIGHT_PROFILE_INVALID = 0,
  QBS_WEIGHT_PROFILE_Q4_K = 1,
  QBS_WEIGHT_PROFILE_Q5_K = 4,
  QBS_WEIGHT_PROFILE_Q6_K = 2,
  QBS_WEIGHT_PROFILE_Q3_K = 5,
  QBS_WEIGHT_PROFILE_Q8_0_WEIGHT = 6,
  QBS_WEIGHT_PROFILE_Q4_0 = 3,
  QBS_WEIGHT_PROFILE_Q2_K = 7,
  QBS_WEIGHT_PROFILE_Q5_0 = 8,
  QBS_WEIGHT_PROFILE_IQ4_NL = 9,
} qbs_weight_profile_t;

typedef enum {
  QBS_ACTIVATION_PROFILE_INVALID = 0,
  QBS_ACTIVATION_PROFILE_Q8_K = 1,
  QBS_ACTIVATION_PROFILE_Q8_0 = 2,
} qbs_activation_profile_t;

typedef enum {
  QBS_WEIGHT_LAYOUT_INVALID = 0,
  QBS_WEIGHT_LAYOUT_ROW_MAJOR = 1,
  QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR = 2,
} qbs_weight_layout_t;

typedef enum {
  QBS_ACTIVATION_LAYOUT_INVALID = 0,
  QBS_ACTIVATION_LAYOUT_ROW_MAJOR = 1,
  QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED = 2,
  QBS_ACTIVATION_LAYOUT_M8_INTERLEAVED = 3,
} qbs_activation_layout_t;

typedef enum {
  QBS_ACTIVATION_ACCESS_DIRECT = 0,
  QBS_ACTIVATION_ACCESS_FILL = 1,
  QBS_ACTIVATION_ACCESS_REUSE = 2,
  QBS_ACTIVATION_ACCESS_RELEASE = 3,
} qbs_activation_access_t;

typedef struct __attribute__((aligned(16))) {
  uint64_t header;
  uint64_t weight_base;
} qbs_descriptor_v2_t;

typedef qbs_descriptor_v2_t qbs_descriptor_t;

typedef struct {
  uint8_t descriptor_version;
  uint8_t weight_profile;
  uint8_t activation_profile;
  uint8_t weight_layout;
  uint8_t activation_layout;
  uint8_t n;
  uint16_t k_blocks;
  uint8_t activation_access;
  uint8_t context_id;
  uint8_t context_generation;
} qbs_descriptor_fields_t;

#if defined(__cplusplus)
static_assert(sizeof(qbs_descriptor_t) == QBS_DESCRIPTOR_BYTES,
              "invalid QBS descriptor size");
#else
_Static_assert(sizeof(qbs_descriptor_t) == QBS_DESCRIPTOR_BYTES,
               "invalid QBS descriptor size");
#endif

static inline const char *qbs_weight_profile_name(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return "Q4_K";
    case QBS_WEIGHT_PROFILE_Q5_K: return "Q5_K";
    case QBS_WEIGHT_PROFILE_Q6_K: return "Q6_K";
    case QBS_WEIGHT_PROFILE_Q3_K: return "Q3_K";
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return "Q8_0_WEIGHT";
    case QBS_WEIGHT_PROFILE_Q4_0: return "Q4_0";
    case QBS_WEIGHT_PROFILE_Q2_K: return "Q2_K";
    case QBS_WEIGHT_PROFILE_Q5_0: return "Q5_0";
    case QBS_WEIGHT_PROFILE_IQ4_NL: return "IQ4_NL";
    default: return "invalid";
  }
}

static inline const char *qbs_activation_profile_name(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return "Q8_K";
    case QBS_ACTIVATION_PROFILE_Q8_0: return "Q8_0";
    default: return "invalid";
  }
}

static inline uint64_t qbs_weight_encoding_id(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return QBS_WEIGHT_ENCODING_Q4_K;
    case QBS_WEIGHT_PROFILE_Q5_K: return QBS_WEIGHT_ENCODING_Q5_K;
    case QBS_WEIGHT_PROFILE_Q6_K: return QBS_WEIGHT_ENCODING_Q6_K;
    case QBS_WEIGHT_PROFILE_Q3_K: return QBS_WEIGHT_ENCODING_Q3_K;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return QBS_WEIGHT_ENCODING_Q8_0_WEIGHT;
    case QBS_WEIGHT_PROFILE_Q4_0: return QBS_WEIGHT_ENCODING_Q4_0;
    case QBS_WEIGHT_PROFILE_Q2_K: return QBS_WEIGHT_ENCODING_Q2_K;
    case QBS_WEIGHT_PROFILE_Q5_0: return QBS_WEIGHT_ENCODING_Q5_0;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return QBS_WEIGHT_ENCODING_IQ4_NL;
    default: return UINT64_C(0);
  }
}

static inline uint64_t qbs_activation_encoding_id(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return QBS_ACTIVATION_ENCODING_Q8_K;
    case QBS_ACTIVATION_PROFILE_Q8_0: return QBS_ACTIVATION_ENCODING_Q8_0;
    default: return UINT64_C(0);
  }
}

static inline const char *qbs_weight_encoding_name(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return "qbs.weight.ggml.q4_k.v1";
    case QBS_WEIGHT_PROFILE_Q5_K: return "qbs.weight.ggml.q5_k.v1";
    case QBS_WEIGHT_PROFILE_Q6_K: return "qbs.weight.ggml.q6_k.v1";
    case QBS_WEIGHT_PROFILE_Q3_K: return "qbs.weight.ggml.q3_k.v1";
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return "qbs.weight.s8.b32.fp16.twos_complement.v1";
    case QBS_WEIGHT_PROFILE_Q4_0: return "qbs.weight.s4.b32.fp16.split_nibble_offset8.v1";
    case QBS_WEIGHT_PROFILE_Q2_K: return "qbs.weight.ggml.q2_k.v1";
    case QBS_WEIGHT_PROFILE_Q5_0: return "qbs.weight.s5.b32.fp16.nibble_highbit_offset16.v1";
    case QBS_WEIGHT_PROFILE_IQ4_NL: return "qbs.weight.ggml.iq4_nl.v1";
    default: return "invalid";
  }
}

static inline const char *qbs_activation_encoding_name(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return "qbs.activation.s8.b256.fp32.bsum16_i16.v1";
    case QBS_ACTIVATION_PROFILE_Q8_0: return "qbs.activation.s8.b32.fp16.twos_complement.v1";
    default: return "invalid";
  }
}

static inline qbs_weight_profile_t qbs_weight_profile_from_encoding(
    uint64_t encoding_id) {
  switch (encoding_id) {
    case QBS_WEIGHT_ENCODING_Q4_K: return QBS_WEIGHT_PROFILE_Q4_K;
    case QBS_WEIGHT_ENCODING_Q5_K: return QBS_WEIGHT_PROFILE_Q5_K;
    case QBS_WEIGHT_ENCODING_Q6_K: return QBS_WEIGHT_PROFILE_Q6_K;
    case QBS_WEIGHT_ENCODING_Q3_K: return QBS_WEIGHT_PROFILE_Q3_K;
    case QBS_WEIGHT_ENCODING_Q8_0_WEIGHT: return QBS_WEIGHT_PROFILE_Q8_0_WEIGHT;
    case QBS_WEIGHT_ENCODING_Q4_0: return QBS_WEIGHT_PROFILE_Q4_0;
    case QBS_WEIGHT_ENCODING_Q2_K: return QBS_WEIGHT_PROFILE_Q2_K;
    case QBS_WEIGHT_ENCODING_Q5_0: return QBS_WEIGHT_PROFILE_Q5_0;
    case QBS_WEIGHT_ENCODING_IQ4_NL: return QBS_WEIGHT_PROFILE_IQ4_NL;
    default: return QBS_WEIGHT_PROFILE_INVALID;
  }
}

static inline qbs_activation_profile_t qbs_activation_profile_from_encoding(
    uint64_t encoding_id) {
  switch (encoding_id) {
    case QBS_ACTIVATION_ENCODING_Q8_K: return QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_ACTIVATION_ENCODING_Q8_0: return QBS_ACTIVATION_PROFILE_Q8_0;
    default: return QBS_ACTIVATION_PROFILE_INVALID;
  }
}

static inline unsigned qbs_weight_block_bytes(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return 144u;
    case QBS_WEIGHT_PROFILE_Q5_K: return 176u;
    case QBS_WEIGHT_PROFILE_Q6_K: return 210u;
    case QBS_WEIGHT_PROFILE_Q3_K: return 110u;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return 34u;
    case QBS_WEIGHT_PROFILE_Q4_0: return 18u;
    case QBS_WEIGHT_PROFILE_Q2_K: return 84u;
    case QBS_WEIGHT_PROFILE_Q5_0: return 22u;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return 18u;
    default: return 0u;
  }
}

static inline unsigned qbs_weight_block_elements(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return 256u;
    case QBS_WEIGHT_PROFILE_Q5_K: return 256u;
    case QBS_WEIGHT_PROFILE_Q6_K: return 256u;
    case QBS_WEIGHT_PROFILE_Q3_K: return 256u;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return 32u;
    case QBS_WEIGHT_PROFILE_Q4_0: return 32u;
    case QBS_WEIGHT_PROFILE_Q2_K: return 256u;
    case QBS_WEIGHT_PROFILE_Q5_0: return 32u;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return 32u;
    default: return 0u;
  }
}

static inline unsigned qbs_weight_subgroup_count(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return 8u;
    case QBS_WEIGHT_PROFILE_Q5_K: return 8u;
    case QBS_WEIGHT_PROFILE_Q6_K: return 16u;
    case QBS_WEIGHT_PROFILE_Q3_K: return 16u;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return 1u;
    case QBS_WEIGHT_PROFILE_Q4_0: return 1u;
    case QBS_WEIGHT_PROFILE_Q2_K: return 16u;
    case QBS_WEIGHT_PROFILE_Q5_0: return 1u;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return 1u;
    default: return 0u;
  }
}

static inline unsigned qbs_weight_subgroup_elements(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return 32u;
    case QBS_WEIGHT_PROFILE_Q5_K: return 32u;
    case QBS_WEIGHT_PROFILE_Q6_K: return 16u;
    case QBS_WEIGHT_PROFILE_Q3_K: return 16u;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return 32u;
    case QBS_WEIGHT_PROFILE_Q4_0: return 32u;
    case QBS_WEIGHT_PROFILE_Q2_K: return 16u;
    case QBS_WEIGHT_PROFILE_Q5_0: return 32u;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return 32u;
    default: return 0u;
  }
}

static inline qbs_scale_format_t qbs_weight_scale_format(unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q5_K: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q6_K: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q3_K: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q4_0: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q2_K: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_Q5_0: return QBS_SCALE_FP16;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return QBS_SCALE_FP16;
    default: return QBS_SCALE_INVALID;
  }
}

static inline qbs_correction_mode_t qbs_weight_correction_mode(
    unsigned profile) {
  switch (profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return QBS_CORRECTION_AFFINE_MIN;
    case QBS_WEIGHT_PROFILE_Q5_K: return QBS_CORRECTION_AFFINE_MIN;
    case QBS_WEIGHT_PROFILE_Q6_K: return QBS_CORRECTION_NONE;
    case QBS_WEIGHT_PROFILE_Q3_K: return QBS_CORRECTION_NONE;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return QBS_CORRECTION_NONE;
    case QBS_WEIGHT_PROFILE_Q4_0: return QBS_CORRECTION_NONE;
    case QBS_WEIGHT_PROFILE_Q2_K: return QBS_CORRECTION_AFFINE_MIN;
    case QBS_WEIGHT_PROFILE_Q5_0: return QBS_CORRECTION_NONE;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return QBS_CORRECTION_NONE;
    default: return QBS_CORRECTION_NONE;
  }
}

static inline unsigned qbs_activation_block_bytes(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return 292u;
    case QBS_ACTIVATION_PROFILE_Q8_0: return 34u;
    default: return 0u;
  }
}

static inline unsigned qbs_activation_block_elements(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return 256u;
    case QBS_ACTIVATION_PROFILE_Q8_0: return 32u;
    default: return 0u;
  }
}

static inline qbs_scale_format_t qbs_activation_scale_format(
    unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return QBS_SCALE_FP32;
    case QBS_ACTIVATION_PROFILE_Q8_0: return QBS_SCALE_FP16;
    default: return QBS_SCALE_INVALID;
  }
}

static inline unsigned qbs_activation_scale_bytes(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return 4u;
    case QBS_ACTIVATION_PROFILE_Q8_0: return 2u;
    default: return 0u;
  }
}

static inline unsigned qbs_activation_quant_bytes(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return 256u;
    case QBS_ACTIVATION_PROFILE_Q8_0: return 32u;
    default: return 0u;
  }
}

static inline unsigned qbs_activation_aux_count(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return 16u;
    case QBS_ACTIVATION_PROFILE_Q8_0: return 0u;
    default: return 0u;
  }
}

static inline unsigned qbs_activation_aux_element_bytes(unsigned profile) {
  switch (profile) {
    case QBS_ACTIVATION_PROFILE_Q8_K: return 2u;
    case QBS_ACTIVATION_PROFILE_Q8_0: return 0u;
    default: return 0u;
  }
}

static inline int qbs_profiles_compatible(unsigned weight_profile,
                                          unsigned activation_profile) {
  switch (weight_profile) {
    case QBS_WEIGHT_PROFILE_Q4_K:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q5_K:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q6_K:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q3_K:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_0;
    case QBS_WEIGHT_PROFILE_Q4_0:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_0;
    case QBS_WEIGHT_PROFILE_Q2_K:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q5_0:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_0;
    case QBS_WEIGHT_PROFILE_IQ4_NL:
      return activation_profile == QBS_ACTIVATION_PROFILE_Q8_0;
    default: return 0;
  }
}

static inline qbs_activation_profile_t qbs_default_activation_profile(
    unsigned weight_profile) {
  switch (weight_profile) {
    case QBS_WEIGHT_PROFILE_Q4_K: return QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q5_K: return QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q6_K: return QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q3_K: return QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q8_0_WEIGHT: return QBS_ACTIVATION_PROFILE_Q8_0;
    case QBS_WEIGHT_PROFILE_Q4_0: return QBS_ACTIVATION_PROFILE_Q8_0;
    case QBS_WEIGHT_PROFILE_Q2_K: return QBS_ACTIVATION_PROFILE_Q8_K;
    case QBS_WEIGHT_PROFILE_Q5_0: return QBS_ACTIVATION_PROFILE_Q8_0;
    case QBS_WEIGHT_PROFILE_IQ4_NL: return QBS_ACTIVATION_PROFILE_Q8_0;
    default: return QBS_ACTIVATION_PROFILE_INVALID;
  }
}

static inline uint64_t qbs_pack_descriptor_header(
    const qbs_descriptor_fields_t *fields) {
  return ((uint64_t)(fields->descriptor_version & 0x0fu) << 0) |
         ((uint64_t)(fields->weight_profile & 0x0fu) << 4) |
         ((uint64_t)(fields->activation_profile & 0x0fu) << 8) |
         ((uint64_t)(fields->weight_layout & 0x0fu) << 12) |
         ((uint64_t)(fields->activation_layout & 0x0fu) << 16) |
         ((uint64_t)((fields->n - 1u) & 0x1fu) << 20) |
         ((uint64_t)((fields->k_blocks - 1u) & 0xffu) << 25) |
         ((uint64_t)(fields->activation_access & 0x03u) << 33) |
         ((uint64_t)(fields->context_id & 0x0fu) << 35) |
         ((uint64_t)fields->context_generation << 39);
}

static inline qbs_descriptor_fields_t qbs_unpack_descriptor_header(
    uint64_t header) {
  qbs_descriptor_fields_t fields;
  fields.descriptor_version = (uint8_t)((header >> 0) & 0x0fu);
  fields.weight_profile = (uint8_t)((header >> 4) & 0x0fu);
  fields.activation_profile = (uint8_t)((header >> 8) & 0x0fu);
  fields.weight_layout = (uint8_t)((header >> 12) & 0x0fu);
  fields.activation_layout = (uint8_t)((header >> 16) & 0x0fu);
  fields.n = (uint8_t)(((header >> 20) & 0x1fu) + 1u);
  fields.k_blocks = (uint16_t)(((header >> 25) & 0xffu) + 1u);
  fields.activation_access = (uint8_t)((header >> 33) & 0x03u);
  fields.context_id = (uint8_t)((header >> 35) & 0x0fu);
  fields.context_generation = (uint8_t)((header >> 39) & 0xffu);
  return fields;
}

static inline uint64_t qbs_capability_word(unsigned index,
                                            unsigned vlen_bits) {
  unsigned max_n = vlen_bits / 32u;
  if (max_n > QBS_MAX_N) max_n = QBS_MAX_N;
  if (index == 0x00u) {
    if (max_n == 0) return 0;
    return ((uint64_t)QBS_ARCH_VERSION << 0) |
           ((uint64_t)QBS_DESCRIPTOR_VERSION << 8) |
           ((uint64_t)QBS_DESCRIPTOR_BYTES << 16) |
           ((uint64_t)(QBS_MAX_M - 1u) << 24) |
           ((uint64_t)(max_n - 1u) << 27) |
           ((uint64_t)(QBS_MAX_K_BLOCKS - 1u) << 32) |
           ((uint64_t)QBS_NUMERICAL_CONTRACT_VERSION << 40) |
           (UINT64_C(1) << 44) | (UINT64_C(1) << 45) |
           (UINT64_C(1) << 46) | (UINT64_C(1) << 47) |
           (UINT64_C(1) << 48) |
           ((uint64_t)(QBS_MAX_RESULTS - 1u) << 56);
  }
  if (index == 0x01u) {
    const uint64_t weight_layouts =
        (UINT64_C(1) << QBS_WEIGHT_LAYOUT_ROW_MAJOR) |
        (UINT64_C(1) << QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR);
    const uint64_t activation_layouts =
        (UINT64_C(1) << QBS_ACTIVATION_LAYOUT_ROW_MAJOR) |
        (UINT64_C(1) << QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED) |
        (UINT64_C(1) << QBS_ACTIVATION_LAYOUT_M8_INTERLEAVED);
    return weight_layouts | (activation_layouts << 16) |
           ((uint64_t)QBS_DESCRIPTOR_ALIGNMENT_LOG2 << 32) |
           ((uint64_t)QBS_WEIGHT_BASE_ALIGNMENT_LOG2 << 40) |
           ((uint64_t)QBS_ACTIVATION_BASE_ALIGNMENT_LOG2 << 48) |
           (UINT64_C(32) << 56);
  }
  if (index == 0x02u) {
    const uint64_t context_profiles =
        (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K);
    const uint64_t context_layouts =
        (UINT64_C(1) << QBS_ACTIVATION_LAYOUT_ROW_MAJOR);
    return ((uint64_t)QBS_ACTIVATION_CONTEXT_COUNT << 0) |
           ((uint64_t)(QBS_ACTIVATION_CONTEXT_MAX_M - 1u) << 4) |
           ((uint64_t)(QBS_ACTIVATION_CONTEXT_MAX_K_BLOCKS - 1u) << 7) |
           (context_profiles << 12) |
           (UINT64_C(0x0f) << 28) |
           ((uint64_t)QBS_ACTIVATION_CONTEXT_GENERATION_BITS << 32) |
           (context_layouts << 40);
  }
  if (index == 0x11u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K);
  if (index == 0x21u)
    return (uint64_t)QBS_Q4_K_BLOCK_BYTES |
           ((uint64_t)QBS_Q4_K_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q4_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q4_K_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q4_K_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q4_K_CORRECTION_MODE << 56);
  if (index == 0x14u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K);
  if (index == 0x24u)
    return (uint64_t)QBS_Q5_K_BLOCK_BYTES |
           ((uint64_t)QBS_Q5_K_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q5_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q5_K_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q5_K_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q5_K_CORRECTION_MODE << 56);
  if (index == 0x12u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K);
  if (index == 0x22u)
    return (uint64_t)QBS_Q6_K_BLOCK_BYTES |
           ((uint64_t)QBS_Q6_K_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q6_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q6_K_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q6_K_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q6_K_CORRECTION_MODE << 56);
  if (index == 0x15u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K);
  if (index == 0x25u)
    return (uint64_t)QBS_Q3_K_BLOCK_BYTES |
           ((uint64_t)QBS_Q3_K_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q3_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q3_K_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q3_K_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q3_K_CORRECTION_MODE << 56);
  if (index == 0x16u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_0);
  if (index == 0x26u)
    return (uint64_t)QBS_Q8_0_WEIGHT_BLOCK_BYTES |
           ((uint64_t)QBS_Q8_0_WEIGHT_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q8_0_WEIGHT_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q8_0_WEIGHT_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q8_0_WEIGHT_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q8_0_WEIGHT_CORRECTION_MODE << 56);
  if (index == 0x13u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_0);
  if (index == 0x23u)
    return (uint64_t)QBS_Q4_0_BLOCK_BYTES |
           ((uint64_t)QBS_Q4_0_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q4_0_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q4_0_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q4_0_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q4_0_CORRECTION_MODE << 56);
  if (index == 0x17u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K);
  if (index == 0x27u)
    return (uint64_t)QBS_Q2_K_BLOCK_BYTES |
           ((uint64_t)QBS_Q2_K_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q2_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q2_K_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q2_K_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q2_K_CORRECTION_MODE << 56);
  if (index == 0x18u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_0);
  if (index == 0x28u)
    return (uint64_t)QBS_Q5_0_BLOCK_BYTES |
           ((uint64_t)QBS_Q5_0_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q5_0_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q5_0_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_Q5_0_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_Q5_0_CORRECTION_MODE << 56);
  if (index == 0x19u)
    return (UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_0);
  if (index == 0x29u)
    return (uint64_t)QBS_IQ4_NL_BLOCK_BYTES |
           ((uint64_t)QBS_IQ4_NL_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_IQ4_NL_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_IQ4_NL_SUBGROUP_ELEMENTS << 40) |
           ((uint64_t)QBS_IQ4_NL_SCALE_FORMAT << 48) |
           ((uint64_t)QBS_IQ4_NL_CORRECTION_MODE << 56);
  if (index == 0x31u)
    return (uint64_t)QBS_Q8_K_BLOCK_BYTES |
           ((uint64_t)QBS_Q8_K_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q8_K_AUX_COUNT << 32) |
           ((uint64_t)QBS_Q8_K_SCALE_BYTES << 40) |
           ((uint64_t)QBS_Q8_K_AUX_ELEMENT_BYTES << 48) |
           ((uint64_t)QBS_Q8_K_SCALE_FORMAT << 56);
  if (index == 0x32u)
    return (uint64_t)QBS_Q8_0_BLOCK_BYTES |
           ((uint64_t)QBS_Q8_0_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q8_0_AUX_COUNT << 32) |
           ((uint64_t)QBS_Q8_0_SCALE_BYTES << 40) |
           ((uint64_t)QBS_Q8_0_AUX_ELEMENT_BYTES << 48) |
           ((uint64_t)QBS_Q8_0_SCALE_FORMAT << 56);
  return 0;
}

static inline uint32_t qbs_encode_qbexec(unsigned vd, unsigned rs1,
                                         unsigned rs2, unsigned m) {
  const uint32_t funct7 =
      (uint32_t)((m - 1u) & ((1u << QBS_M_MINUS_ONE_BITS) - 1u));
  return (funct7 << 25) | ((uint32_t)(rs2 & 0x1fu) << 20) |
         ((uint32_t)(rs1 & 0x1fu) << 15) | (QBS_QBEXEC_FUNCT3 << 12) |
         ((uint32_t)(vd & 0x1fu) << 7) | QBS_OPCODE_CUSTOM2;
}

static inline uint32_t qbs_encode_qbinfo(unsigned rd, unsigned rs1) {
  return ((uint32_t)(rs1 & 0x1fu) << 15) | (QBS_QBINFO_FUNCT3 << 12) |
         ((uint32_t)(rd & 0x1fu) << 7) | QBS_OPCODE_CUSTOM2;
}

#endif  /* ARA_QBS_ABI_H_ */
