#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 CASE_ID" >&2
  exit 2
fi

repo_root=$(cd -- "$(dirname -- "$0")/../../.." && pwd)
script_dir=${repo_root}/hardware/scripts/llama_q4km_extract
platform=/home/wangwy/llama/platforms/cva6-qemu
image=${platform}/images/qwen2.5-q4km-capture.ext4
capture_root=/home/wangwy/llama/captures/qwen2.5-1.5b-q4_k_m
log=/home/wangwy/llama/captures/qwen2.5-1.5b-q4_k_m-replay-qemu.log
result=/home/wangwy/llama/captures/qwen2.5-1.5b-q4_k_m-replay-result.log

if pgrep -f 'qemu-system-riscv64.*q4kmdata' >/dev/null; then
  echo "Q4_K_M QEMU is already running" >&2
  exit 1
fi

resolved=$("${script_dir}/cases.py" --root "${capture_root}" resolve "$1")
level=${resolved%%$'\t'*}
host_path=${resolved#*$'\t'}
guest_path=captures/qwen2.5-1.5b-q4_k_m/${host_path}

# Non-linear/dataflow leaf descriptions are generated by cases.py on the host.
# Mirror only the selected descriptor into the data image; its relative tensor
# references then resolve to the original capture already stored on that image.
if [[ ${level} == block-leaf ]]; then
  host_case=${capture_root}/${host_path}/case.json
  image_case=/${guest_path}/case.json
  image_dir=${image_case%/*}
  current=
  IFS=/ read -r -a components <<< "${image_dir}"
  for component in "${components[@]}"; do
    [[ -z ${component} ]] && continue
    current=${current}/${component}
    debugfs -w -R "mkdir ${current}" "${image}" >/dev/null 2>&1 || true
  done
  debugfs -w -R "rm ${image_case}" "${image}" >/dev/null 2>&1 || true
  debugfs -w -R "write ${host_case} ${image_case}" "${image}" >/dev/null
fi

request=$(mktemp)
trap 'rm -f "${request}"' EXIT
printf '%s %s\n' "${level}" "${guest_path}" > "${request}"

debugfs -w -R 'rm /q4km-replay.log' "${image}" >/dev/null 2>&1 || true
debugfs -w -R 'rm /q4km-replay.request' "${image}" >/dev/null 2>&1 || true
debugfs -w -R "write ${request} /q4km-replay.request" "${image}" >/dev/null

source "${platform}/env.sh"
"${CROSS_BIN}/qemu-system-riscv64" \
  -M virt \
  -cpu "rv64,v=true,vlen=1024,elen=64" \
  -smp 1 \
  -m 8G \
  -nographic \
  -bios "${QEMU_IMAGES}/fw_dynamic.bin" \
  -initrd "${QEMU_IMAGES}/rootfs.cpio" \
  -kernel "${QEMU_IMAGES}/Image" \
  -drive "file=${image},format=raw,if=none,id=q4kmdata" \
  -device "virtio-blk-pci,drive=q4kmdata" \
  -append "rootwait root=/dev/ram ro console=ttyS0" \
  > "${log}" 2>&1

rm -f "${result}"
debugfs -R "dump /q4km-replay.log ${result}" "${image}" >/dev/null
cat "${result}"

status=$(sed -n 's/^exit_status=//p' "${result}" | tail -n 1)
if [[ ! ${status} =~ ^[0-9]+$ ]]; then
  echo "q4km-replay: result log has no valid exit_status" >&2
  exit 2
fi
exit "${status}"
