#!/usr/bin/env python3
"""Generate C and SystemVerilog AKV ABI definitions from one JSON source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "config/akv_abi.json"
C_PATHS = [
    ROOT / "apps/common/akv_abi.h",
    ROOT / "software/akv/include/akv/akv_abi.h",
]
SV_PATH = ROOT / "hardware/include/akv_pkg.sv"


def load_spec() -> dict:
    return json.loads(SPEC_PATH.read_text(encoding="utf-8"))


def validate_spec(spec: dict) -> None:
    descriptor = spec["descriptor"]
    instruction = spec["instruction"]
    limits = spec["limits"]
    token = spec["token_axis_profile"]
    if spec["architecture_version"] != 1:
        raise ValueError("AKV architecture version must be one")
    if descriptor != {"version": 1, "bytes": 64, "alignment_log2": 6}:
        raise ValueError("AKV descriptor v1 is fixed at 64-byte size/alignment")
    opcode = int(instruction["opcode"], 0)
    if opcode != 0x5B:
        raise ValueError("AKV v1 shares the custom-2 opcode with QBS")
    funct3 = [instruction[name] for name in (
        "fill_funct3", "load_funct3", "info_funct3", "release_funct3"
    )]
    if len(set(funct3)) != 4 or any(not 0 <= value < 8 for value in funct3):
        raise ValueError("AKV funct3 values must be distinct 3-bit values")
    if any(value in (0, 1) for value in funct3):
        raise ValueError("AKV funct3 values 0 and 1 are reserved by QBS")
    if limits["context_count"] != 1:
        raise ValueError("AKV v1 defines exactly one non-architectural context")
    if not 1 <= limits["max_q_rows"] <= 8:
        raise ValueError("AKV q-row selector has a 3-bit index")
    if limits["tile_tokens"] != 8:
        raise ValueError("AKV v1 fixes the KV tile at eight tokens")
    if limits["head_dims"] != [64, 128]:
        raise ValueError("AKV v1 supports only D=64 and D=128")
    if spec["element_formats"] != {"F16": 1}:
        raise ValueError("AKV v1 supports only F16 resident vectors")
    if spec["streams"] != {"Q": 0, "K": 1, "V": 2}:
        raise ValueError("AKV v1 stream encoding changed")
    if spec["fill_modes"] != {"FULL": 0, "REFILL": 1}:
        raise ValueError("AKV fill-mode encoding changed")
    if token["version"] != 2:
        raise ValueError("AKV token-axis profile version must be two")
    if token["tile_tokens"] != 64:
        raise ValueError("AKV-v2 token-axis profile fixes a 64-token tile")
    if token["token_banks"] != 8:
        raise ValueError("AKV-v2 token-axis profile fixes eight token banks")
    if token["selector_index_bits"] != 6:
        raise ValueError("AKV-v2 row selector uses a six-bit index")
    if token["payload_alignment_log2"] != 5:
        raise ValueError("AKV-v2 payload rows require 32-byte alignment")
    if token["head_dims"] != [64, 96, 128] or not token["d_axis_tail"]:
        raise ValueError("AKV-v2 supports D64/D96/D128 with D-axis tails")
    if (token["segmented_head_dims"] != [256] or
            token["column_segment_bit"] != 7 or
            not token["d256_segmented"]):
        raise ValueError("AKV-v2 D256 uses two D128 physical segments")
    extension_funct3 = [token["fill_funct3"], token["column_load_funct3"]]
    if extension_funct3 != [6, 7]:
        raise ValueError("AKV-v2 uses the two remaining custom-2 funct3 values")
    if set(extension_funct3) & set(funct3) or len(set(extension_funct3)) != 2:
        raise ValueError("AKV-v1 and AKV-v2 funct3 values must be distinct")
    if (token["column_panel_width"] != 4 or
            token["column_panel_funct7"] != 1 or
            token["column_panel_capability_bit"] != 40):
        raise ValueError("AKV-v2 panel profile is fixed at four columns")


def c_header(spec: dict) -> str:
    desc = spec["descriptor"]
    insn = spec["instruction"]
    limits = spec["limits"]
    token = spec["token_axis_profile"]
    opcode = int(insn["opcode"], 0)
    return f"""/* Generated by scripts/gen_akv_abi.py. Do not edit. */
#ifndef AKV_ABI_H
#define AKV_ABI_H

#include <stddef.h>
#include <stdint.h>

#define AKV_ARCHITECTURE_VERSION {spec['architecture_version']}u
#define AKV_DESCRIPTOR_VERSION {desc['version']}u
#define AKV_DESCRIPTOR_BYTES {desc['bytes']}u
#define AKV_DESCRIPTOR_ALIGNMENT_LOG2 {desc['alignment_log2']}u
#define AKV_OPCODE_CUSTOM2 0x{opcode:02x}u
#define AKV_FILL_FUNCT3 {insn['fill_funct3']}u
#define AKV_LOAD_FUNCT3 {insn['load_funct3']}u
#define AKV_INFO_FUNCT3 {insn['info_funct3']}u
#define AKV_RELEASE_FUNCT3 {insn['release_funct3']}u
#define AKV_CONTEXT_COUNT {limits['context_count']}u
#define AKV_MAX_Q_ROWS {limits['max_q_rows']}u
#define AKV_TILE_TOKENS {limits['tile_tokens']}u
#define AKV_V2_PROFILE_VERSION {token['version']}u
#define AKV_V2_TILE_TOKENS {token['tile_tokens']}u
#define AKV_V2_TOKEN_BANKS {token['token_banks']}u
#define AKV_V2_SELECTOR_INDEX_BITS {token['selector_index_bits']}u
#define AKV_V2_PAYLOAD_ALIGNMENT_LOG2 {token['payload_alignment_log2']}u
#define AKV_V2_FILL_FUNCT3 {token['fill_funct3']}u
#define AKV_V2_COLUMN_LOAD_FUNCT3 {token['column_load_funct3']}u
#define AKV_HEAD_DIM_64 64u
#define AKV_HEAD_DIM_96 96u
#define AKV_HEAD_DIM_128 128u
#define AKV_HEAD_DIM_256 256u
#define AKV_HEAD_DIM_CODE_64 0u
#define AKV_HEAD_DIM_CODE_128 1u
#define AKV_HEAD_DIM_CODE_96 2u
#define AKV_HEAD_DIM_CODE_INVALID 0xffu
#define AKV_V2_D_AXIS_TAIL_CAPABILITY_BIT 38u
#define AKV_V2_D256_SEGMENTED_CAPABILITY_BIT 39u
#define AKV_V2_COLUMN_PANEL_CAPABILITY_BIT {token['column_panel_capability_bit']}u
#define AKV_V2_COLUMN_SEGMENT_BIT {token['column_segment_bit']}u
#define AKV_V2_COLUMN_PANEL_WIDTH {token['column_panel_width']}u
#define AKV_V2_COLUMN_SINGLE_FUNCT7 0u
#define AKV_V2_COLUMN_PANEL_FUNCT7 {token['column_panel_funct7']}u

typedef enum {{
  AKV_ELEMENT_FORMAT_INVALID = 0,
  AKV_ELEMENT_FORMAT_F16 = {spec['element_formats']['F16']},
}} akv_element_format_t;

typedef enum {{
  AKV_STREAM_Q = {spec['streams']['Q']},
  AKV_STREAM_K = {spec['streams']['K']},
  AKV_STREAM_V = {spec['streams']['V']},
}} akv_stream_t;

typedef enum {{
  AKV_FILL_FULL = {spec['fill_modes']['FULL']},
  AKV_FILL_REFILL = {spec['fill_modes']['REFILL']},
}} akv_fill_mode_t;

typedef struct __attribute__((aligned(AKV_DESCRIPTOR_BYTES))) {{
  uint8_t version;
  uint8_t element_format;
  uint8_t q_rows;
  uint8_t flags;
  uint16_t head_dim;
  uint16_t kv_length;
  uint32_t q_row_stride_bytes;
  uint32_t k_token_stride_bytes;
  uint32_t v_token_stride_bytes;
  uint32_t reserved0;
  uint64_t q_base;
  uint64_t k_base;
  uint64_t v_base;
  uint64_t reserved1;
  uint64_t reserved2;
}} akv_descriptor_t;

#if defined(__cplusplus)
static_assert(sizeof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
              "AKV descriptor size mismatch");
static_assert(alignof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
              "AKV descriptor alignment mismatch");
#else
_Static_assert(sizeof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
               "AKV descriptor size mismatch");
_Static_assert(_Alignof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
               "AKV descriptor alignment mismatch");
#endif

static inline uint32_t akv_head_dim_code(uint32_t head_dim) {{
  if (head_dim == AKV_HEAD_DIM_64) return AKV_HEAD_DIM_CODE_64;
  if (head_dim == AKV_HEAD_DIM_128) return AKV_HEAD_DIM_CODE_128;
  if (head_dim == AKV_HEAD_DIM_96) return AKV_HEAD_DIM_CODE_96;
  return AKV_HEAD_DIM_CODE_INVALID;
}}

static inline uint32_t akv_destination_registers(uint32_t head_dim) {{
  if (head_dim == AKV_HEAD_DIM_64) return 1u;
  if (head_dim == AKV_HEAD_DIM_96 || head_dim == AKV_HEAD_DIM_128) return 2u;
  return 0u;
}}

static inline uint32_t akv_tile_length(uint32_t kv_length,
                                       uint32_t tile_start) {{
  if (tile_start >= kv_length) return 0u;
  const uint32_t remaining = kv_length - tile_start;
  return remaining < AKV_TILE_TOKENS ? remaining : AKV_TILE_TOKENS;
}}

static inline uint32_t akv_v2_tile_length(uint32_t kv_length,
                                          uint32_t tile_start) {{
  if (tile_start >= kv_length) return 0u;
  const uint32_t remaining = kv_length - tile_start;
  return remaining < AKV_V2_TILE_TOKENS ? remaining : AKV_V2_TILE_TOKENS;
}}

static inline uint32_t akv_selector(akv_stream_t stream, uint32_t index) {{
  if ((uint32_t)stream > (uint32_t)AKV_STREAM_V || index >= 8u)
    return UINT32_MAX;
  return (uint32_t)stream | (index << 2);
}}

static inline uint32_t akv_selector_stream(uint32_t selector) {{
  return selector & 0x3u;
}}

static inline uint32_t akv_selector_index(uint32_t selector) {{
  return (selector >> 2) & 0x7u;
}}

static inline uint32_t akv_v2_selector(akv_stream_t stream, uint32_t index) {{
  if ((uint32_t)stream > (uint32_t)AKV_STREAM_V ||
      index >= AKV_V2_TILE_TOKENS)
    return UINT32_MAX;
  return (uint32_t)stream | (index << 2);
}}

static inline uint32_t akv_v2_selector_index(uint32_t selector) {{
  return (selector >> 2) & ((1u << AKV_V2_SELECTOR_INDEX_BITS) - 1u);
}}

static inline uint32_t akv_v2_column_selector(uint32_t segment,
                                               uint32_t dimension) {{
  if (segment >= 2u || dimension >= AKV_HEAD_DIM_128)
    return UINT32_MAX;
  return (segment << AKV_V2_COLUMN_SEGMENT_BIT) | dimension;
}}

static inline uint32_t akv_v2_column_segment(uint32_t selector) {{
  return (selector >> AKV_V2_COLUMN_SEGMENT_BIT) & 1u;
}}

static inline uint32_t akv_v2_column_dimension(uint32_t selector) {{
  return selector & ((1u << AKV_V2_COLUMN_SEGMENT_BIT) - 1u);
}}

static inline int akv_range_fits(uint64_t base, uint32_t stride,
                                 uint32_t count, uint32_t row_bytes) {{
  if (count == 0u || row_bytes == 0u) return 0;
  const uint64_t last = (uint64_t)(count - 1u) * stride;
  return last <= UINT64_MAX - base &&
         (uint64_t)(row_bytes - 1u) <= UINT64_MAX - (base + last);
}}

static inline int akv_descriptor_common_is_valid(
    const void *descriptor_address, int allow_d96) {{
  if (descriptor_address == NULL ||
      ((uintptr_t)descriptor_address & (AKV_DESCRIPTOR_BYTES - 1u)) != 0u)
    return 0;
  const akv_descriptor_t *descriptor =
      (const akv_descriptor_t *)descriptor_address;
  if (descriptor->version != AKV_DESCRIPTOR_VERSION ||
      descriptor->element_format != AKV_ELEMENT_FORMAT_F16 ||
      descriptor->q_rows == 0u || descriptor->q_rows > AKV_MAX_Q_ROWS ||
      (descriptor->head_dim != AKV_HEAD_DIM_64 &&
       descriptor->head_dim != AKV_HEAD_DIM_128 &&
       (!allow_d96 || descriptor->head_dim != AKV_HEAD_DIM_96)) ||
      descriptor->kv_length == 0u || descriptor->flags != 0u ||
      descriptor->reserved0 != 0u || descriptor->reserved1 != 0u ||
      descriptor->reserved2 != 0u)
    return 0;
  const uint32_t row_bytes = (uint32_t)descriptor->head_dim * 2u;
  if (descriptor->q_row_stride_bytes < row_bytes ||
      descriptor->k_token_stride_bytes < row_bytes ||
      descriptor->v_token_stride_bytes < row_bytes ||
      ((descriptor->q_base | descriptor->k_base | descriptor->v_base |
        descriptor->q_row_stride_bytes | descriptor->k_token_stride_bytes |
        descriptor->v_token_stride_bytes) & UINT64_C(1)) != 0u)
    return 0;
  return akv_range_fits(descriptor->q_base,
                        descriptor->q_row_stride_bytes,
                        descriptor->q_rows, row_bytes) &&
         akv_range_fits(descriptor->k_base,
                        descriptor->k_token_stride_bytes,
                        descriptor->kv_length, row_bytes) &&
         akv_range_fits(descriptor->v_base,
                        descriptor->v_token_stride_bytes,
                        descriptor->kv_length, row_bytes);
}}

static inline int akv_descriptor_is_valid(const void *descriptor_address) {{
  return akv_descriptor_common_is_valid(descriptor_address, 0);
}}

static inline int akv_v2_descriptor_is_valid(
    const void *descriptor_address) {{
  if (!akv_descriptor_common_is_valid(descriptor_address, 1)) return 0;
  const akv_descriptor_t *descriptor =
      (const akv_descriptor_t *)descriptor_address;
  return ((descriptor->q_base | descriptor->k_base | descriptor->v_base |
           descriptor->q_row_stride_bytes |
           descriptor->k_token_stride_bytes |
           descriptor->v_token_stride_bytes) &
          ((UINT64_C(1) << AKV_V2_PAYLOAD_ALIGNMENT_LOG2) - 1u)) == 0u;
}}

static inline int akv_load_selector_is_valid(const akv_descriptor_t *descriptor,
                                              uint32_t tile_length,
                                              uint32_t selector) {{
  if (!akv_descriptor_is_valid(descriptor) || (selector >> 5) != 0u)
    return 0;
  const uint32_t stream = akv_selector_stream(selector);
  const uint32_t index = akv_selector_index(selector);
  if (stream == AKV_STREAM_Q) return index < descriptor->q_rows;
  if (stream == AKV_STREAM_K || stream == AKV_STREAM_V)
    return index < tile_length && tile_length <= AKV_TILE_TOKENS;
  return 0;
}}

static inline int akv_v2_row_selector_is_valid(
    const akv_descriptor_t *descriptor, uint32_t tile_length,
    uint32_t selector) {{
  if (!akv_v2_descriptor_is_valid(descriptor) ||
      (selector >> (2u + AKV_V2_SELECTOR_INDEX_BITS)) != 0u ||
      tile_length == 0u || tile_length > AKV_V2_TILE_TOKENS)
    return 0;
  const uint32_t stream = akv_selector_stream(selector);
  const uint32_t index = akv_v2_selector_index(selector);
  if (stream == AKV_STREAM_Q) return index < descriptor->q_rows;
  if (stream == AKV_STREAM_K || stream == AKV_STREAM_V)
    return index < tile_length;
  return 0;
}}

static inline int akv_v2_column_is_valid(
    const akv_descriptor_t *descriptor, uint32_t tile_length,
    uint32_t selector) {{
  return akv_v2_descriptor_is_valid(descriptor) && tile_length != 0u &&
         tile_length <= AKV_V2_TILE_TOKENS &&
         (selector >> (AKV_V2_COLUMN_SEGMENT_BIT + 1u)) == 0u &&
         akv_v2_column_dimension(selector) < descriptor->head_dim;
}}

static inline int akv_v2_column_panel_is_valid(
    const akv_descriptor_t *descriptor, uint32_t tile_length,
    uint32_t selector) {{
  const uint32_t dimension = akv_v2_column_dimension(selector);
  return akv_v2_column_is_valid(descriptor, tile_length, selector) &&
         (dimension & (AKV_V2_COLUMN_PANEL_WIDTH - 1u)) == 0u &&
         dimension + AKV_V2_COLUMN_PANEL_WIDTH <= descriptor->head_dim;
}}

static inline uint64_t akv_capability_word(uint64_t index, int enabled) {{
  if (index == 0u)
    return (uint64_t)AKV_ARCHITECTURE_VERSION |
           ((uint64_t)AKV_DESCRIPTOR_VERSION << 8) |
           ((uint64_t)AKV_DESCRIPTOR_BYTES << 16) |
           ((uint64_t)AKV_MAX_Q_ROWS << 24) |
           ((uint64_t)AKV_TILE_TOKENS << 32) |
           ((uint64_t)AKV_CONTEXT_COUNT << 40) |
           ((uint64_t)(enabled != 0) << 48) |
           (UINT64_C(1) << 49) | (UINT64_C(1) << 50) |
           (UINT64_C(1) << 51);
  if (index == 1u)
    return (uint64_t)AKV_OPCODE_CUSTOM2 |
           ((uint64_t)AKV_FILL_FUNCT3 << 8) |
           ((uint64_t)AKV_LOAD_FUNCT3 << 11) |
           ((uint64_t)AKV_INFO_FUNCT3 << 14) |
           ((uint64_t)AKV_RELEASE_FUNCT3 << 17) |
           ((uint64_t)AKV_DESCRIPTOR_ALIGNMENT_LOG2 << 20);
  return UINT64_C(0);
}}

static inline uint64_t akv_v2_capability_word(uint64_t index, int enabled) {{
  if (index == 2u)
    return (uint64_t)AKV_V2_PROFILE_VERSION |
           ((uint64_t)AKV_V2_TILE_TOKENS << 8) |
           ((uint64_t)AKV_V2_TOKEN_BANKS << 16) |
           ((uint64_t)AKV_V2_SELECTOR_INDEX_BITS << 24) |
           ((uint64_t)(enabled != 0) << 32) |
           (UINT64_C(1) << 33) | (UINT64_C(1) << 34) |
           (UINT64_C(1) << 35) | (UINT64_C(1) << 36) |
           (UINT64_C(1) << 37) |
           (UINT64_C(1) << AKV_V2_D_AXIS_TAIL_CAPABILITY_BIT) |
           (UINT64_C(1) << AKV_V2_D256_SEGMENTED_CAPABILITY_BIT) |
           (UINT64_C(1) << AKV_V2_COLUMN_PANEL_CAPABILITY_BIT);
  if (index == 3u)
    return (uint64_t)AKV_OPCODE_CUSTOM2 |
           ((uint64_t)AKV_V2_FILL_FUNCT3 << 8) |
           ((uint64_t)AKV_V2_COLUMN_LOAD_FUNCT3 << 11) |
           ((uint64_t)AKV_HEAD_DIM_128 << 16) |
           (UINT64_C(1) << 24);
  return UINT64_C(0);
}}

static inline uint32_t akv_encode_r(uint32_t funct3, uint32_t funct7,
                                    uint32_t rd, uint32_t rs1,
                                    uint32_t rs2) {{
  return ((funct7 & 0x7fu) << 25) | ((rs2 & 0x1fu) << 20) |
         ((rs1 & 0x1fu) << 15) | ((funct3 & 0x7u) << 12) |
         ((rd & 0x1fu) << 7) | AKV_OPCODE_CUSTOM2;
}}

static inline uint32_t akv_encode_fill(uint32_t descriptor_rs1,
                                       uint32_t tile_start_rs2,
                                       akv_fill_mode_t mode) {{
  return akv_encode_r(AKV_FILL_FUNCT3, (uint32_t)mode, 0u,
                      descriptor_rs1, tile_start_rs2);
}}

static inline uint32_t akv_encode_load(uint32_t vd, uint32_t selector_rs1,
                                       uint32_t head_dim) {{
  return akv_encode_r(AKV_LOAD_FUNCT3, akv_head_dim_code(head_dim), vd,
                      selector_rs1, 0u);
}}

static inline uint32_t akv_encode_info(uint32_t rd, uint32_t index_rs1) {{
  return akv_encode_r(AKV_INFO_FUNCT3, 0u, rd, index_rs1, 0u);
}}

static inline uint32_t akv_encode_release(void) {{
  return akv_encode_r(AKV_RELEASE_FUNCT3, 0u, 0u, 0u, 0u);
}}

static inline uint32_t akv_encode_v2_fill(uint32_t descriptor_rs1,
                                          uint32_t tile_start_rs2,
                                          akv_fill_mode_t mode) {{
  return akv_encode_r(AKV_V2_FILL_FUNCT3, (uint32_t)mode, 0u,
                      descriptor_rs1, tile_start_rs2);
}}

static inline uint32_t akv_encode_v2_column_load(uint32_t vd,
                                                 uint32_t dimension_rs1) {{
  return akv_encode_r(AKV_V2_COLUMN_LOAD_FUNCT3,
                      AKV_V2_COLUMN_SINGLE_FUNCT7, vd,
                      dimension_rs1, 0u);
}}

static inline uint32_t akv_encode_v2_column_panel_load(
    uint32_t vd, uint32_t dimension_rs1) {{
  return akv_encode_r(AKV_V2_COLUMN_LOAD_FUNCT3,
                      AKV_V2_COLUMN_PANEL_FUNCT7, vd,
                      dimension_rs1, 0u);
}}

#endif
"""


def sv_package(spec: dict) -> str:
    desc = spec["descriptor"]
    insn = spec["instruction"]
    limits = spec["limits"]
    token = spec["token_axis_profile"]
    opcode = int(insn["opcode"], 0)
    return f"""// Generated by scripts/gen_akv_abi.py. Do not edit.
package akv_pkg;

`ifdef ARA_AKV_ENABLE
  localparam bit AkvEnable = 1'b1;
`else
  localparam bit AkvEnable = 1'b0;
`endif

`ifdef ARA_AKV_V2_ENABLE
  localparam bit AkvV2Enable = 1'b1;
`else
  localparam bit AkvV2Enable = 1'b0;
`endif

  localparam int unsigned AkvArchitectureVersion = {spec['architecture_version']};
  localparam int unsigned AkvDescriptorVersion = {desc['version']};
  localparam int unsigned AkvDescriptorBytes = {desc['bytes']};
  localparam int unsigned AkvDescriptorAlignmentLog2 = {desc['alignment_log2']};
  localparam logic [6:0] AkvOpcodeCustom2 = 7'h{opcode:02x};
  localparam logic [2:0] AkvFillFunct3 = 3'd{insn['fill_funct3']};
  localparam logic [2:0] AkvLoadFunct3 = 3'd{insn['load_funct3']};
  localparam logic [2:0] AkvInfoFunct3 = 3'd{insn['info_funct3']};
  localparam logic [2:0] AkvReleaseFunct3 = 3'd{insn['release_funct3']};
  localparam int unsigned AkvV2ProfileVersion = {token['version']};
  localparam int unsigned AkvV2TileTokens = {token['tile_tokens']};
  localparam int unsigned AkvV2TokenBanks = {token['token_banks']};
  localparam int unsigned AkvV2SelectorIndexBits = {token['selector_index_bits']};
  localparam int unsigned AkvV2PayloadAlignmentLog2 =
      {token['payload_alignment_log2']};
  localparam logic [2:0] AkvV2FillFunct3 = 3'd{token['fill_funct3']};
  localparam logic [2:0] AkvV2ColumnLoadFunct3 = 3'd{token['column_load_funct3']};
  localparam int unsigned AkvHeadDim64 = 64;
  localparam int unsigned AkvHeadDim96 = 96;
  localparam int unsigned AkvHeadDim128 = 128;
  localparam int unsigned AkvHeadDim256 = 256;
  localparam logic [6:0] AkvHeadDimCode64 = 7'd0;
  localparam logic [6:0] AkvHeadDimCode128 = 7'd1;
  localparam logic [6:0] AkvHeadDimCode96 = 7'd2;
  localparam int unsigned AkvV2DAxisTailCapabilityBit = 38;
  localparam int unsigned AkvV2D256SegmentedCapabilityBit = 39;
  localparam int unsigned AkvV2ColumnPanelCapabilityBit =
      {token['column_panel_capability_bit']};
  localparam int unsigned AkvV2ColumnSegmentBit = {token['column_segment_bit']};
  localparam int unsigned AkvV2ColumnPanelWidth =
      {token['column_panel_width']};
  localparam logic [6:0] AkvV2ColumnSingleFunct7 = 7'd0;
  localparam logic [6:0] AkvV2ColumnPanelFunct7 =
      7'd{token['column_panel_funct7']};
  localparam int unsigned AkvContextCount = {limits['context_count']};
  localparam int unsigned AkvMaxQRows = {limits['max_q_rows']};
  localparam int unsigned AkvTileTokens = {limits['tile_tokens']};
  localparam int unsigned AkvMaxHeadDim = 128;
  localparam int unsigned AkvContextBytes =
      (AkvMaxQRows + 2 * AkvTileTokens) * AkvMaxHeadDim * 2;
  localparam int unsigned AkvV2ContextBytes =
      (AkvMaxQRows + 2 * AkvV2TileTokens) * AkvMaxHeadDim * 2;

  typedef enum logic [7:0] {{
    AKV_ELEMENT_FORMAT_INVALID = 8'd0,
    AKV_ELEMENT_FORMAT_F16 = 8'd{spec['element_formats']['F16']}
  }} akv_element_format_e;

  typedef enum logic [1:0] {{
    AKV_STREAM_Q = 2'd{spec['streams']['Q']},
    AKV_STREAM_K = 2'd{spec['streams']['K']},
    AKV_STREAM_V = 2'd{spec['streams']['V']}
  }} akv_stream_e;

  typedef enum logic {{
    AKV_FILL_FULL = 1'b{spec['fill_modes']['FULL']},
    AKV_FILL_REFILL = 1'b{spec['fill_modes']['REFILL']}
  }} akv_fill_mode_e;

  typedef enum logic [2:0] {{
    AKV_COMMAND_FULL,
    AKV_COMMAND_REFILL,
    AKV_COMMAND_LOAD,
    AKV_COMMAND_RELEASE,
    AKV_COMMAND_V2_FULL,
    AKV_COMMAND_V2_REFILL,
    AKV_COMMAND_V2_COLUMN_LOAD
  }} akv_command_e;

  typedef enum logic [4:0] {{
    AKV_VALIDATION_OK,
    AKV_VALIDATION_COMMAND,
    AKV_VALIDATION_DESCRIPTOR_ALIGNMENT,
    AKV_VALIDATION_DESCRIPTOR_VERSION,
    AKV_VALIDATION_DESCRIPTOR_FORMAT,
    AKV_VALIDATION_Q_ROWS,
    AKV_VALIDATION_HEAD_DIM,
    AKV_VALIDATION_KV_LENGTH,
    AKV_VALIDATION_RESERVED,
    AKV_VALIDATION_STRIDE,
    AKV_VALIDATION_RANGE_OVERFLOW,
    AKV_VALIDATION_TILE_RANGE,
    AKV_VALIDATION_CONTEXT,
    AKV_VALIDATION_SELECTOR,
    AKV_VALIDATION_DESTINATION
  }} akv_validation_error_e;

  typedef struct packed {{
    logic [63:0] reserved2;
    logic [63:0] reserved1;
    logic [63:0] v_base;
    logic [63:0] k_base;
    logic [63:0] q_base;
    logic [31:0] reserved0;
    logic [31:0] v_token_stride_bytes;
    logic [31:0] k_token_stride_bytes;
    logic [31:0] q_row_stride_bytes;
    logic [15:0] kv_length;
    logic [15:0] head_dim;
    logic [7:0] flags;
    logic [7:0] q_rows;
    akv_element_format_e element_format;
    logic [7:0] version;
  }} akv_descriptor_v1_t;

  function automatic logic [7:0] akv_head_dim_code(input int unsigned head_dim);
    unique case (head_dim)
      AkvHeadDim64: akv_head_dim_code = 8'(AkvHeadDimCode64);
      AkvHeadDim128: akv_head_dim_code = 8'(AkvHeadDimCode128);
      AkvHeadDim96: akv_head_dim_code = 8'(AkvHeadDimCode96);
      default: akv_head_dim_code = 8'hff;
    endcase
  endfunction : akv_head_dim_code

  function automatic logic [63:0] akv_capability_word(
      input logic [63:0] index, input bit enabled
  );
    akv_capability_word = '0;
    unique case (index)
      64'd0: akv_capability_word =
          64'({spec['architecture_version']}) |
          (64'({desc['version']}) << 8) |
          (64'({desc['bytes']}) << 16) |
          (64'({limits['max_q_rows']}) << 24) |
          (64'({limits['tile_tokens']}) << 32) |
          (64'({limits['context_count']}) << 40) |
          (64'(enabled) << 48) |
          (64'd1 << 49) | (64'd1 << 50) | (64'd1 << 51);
      64'd1: akv_capability_word =
          64'(AkvOpcodeCustom2) |
          (64'(AkvFillFunct3) << 8) |
          (64'(AkvLoadFunct3) << 11) |
          (64'(AkvInfoFunct3) << 14) |
          (64'(AkvReleaseFunct3) << 17) |
          (64'(AkvDescriptorAlignmentLog2) << 20);
      default: ;
    endcase
  endfunction : akv_capability_word

  function automatic logic [63:0] akv_v2_capability_word(
      input logic [63:0] index, input bit enabled
  );
    akv_v2_capability_word = '0;
    unique case (index)
      64'd2: akv_v2_capability_word =
          64'({token['version']}) |
          (64'({token['tile_tokens']}) << 8) |
          (64'({token['token_banks']}) << 16) |
          (64'({token['selector_index_bits']}) << 24) |
          (64'(enabled) << 32) |
          (64'd1 << 33) | (64'd1 << 34) | (64'd1 << 35) |
          (64'd1 << 36) | (64'd1 << 37) |
          (64'd1 << AkvV2DAxisTailCapabilityBit) |
          (64'd1 << AkvV2D256SegmentedCapabilityBit) |
          (64'd1 << AkvV2ColumnPanelCapabilityBit);
      64'd3: akv_v2_capability_word =
          64'(AkvOpcodeCustom2) |
          (64'(AkvV2FillFunct3) << 8) |
          (64'(AkvV2ColumnLoadFunct3) << 11) |
          (64'(AkvMaxHeadDim) << 16) |
          (64'd1 << 24);
      default: ;
    endcase
  endfunction : akv_v2_capability_word

endpackage : akv_pkg
"""


def generated_outputs(spec: dict) -> dict[Path, str]:
    header = c_header(spec)
    return {**{path: header for path in C_PATHS}, SV_PATH: sv_package(spec)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = load_spec()
    validate_spec(spec)
    outputs = generated_outputs(spec)
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
