#!/usr/bin/env python3
"""Generate the software and RTL QBS ABI definitions from one JSON source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "config/qbs_abi.json"
C_PATH = ROOT / "apps/common/qbs_abi.h"
SV_PATH = ROOT / "hardware/include/qbs_pkg.sv"


def load_spec() -> dict:
    with SPEC_PATH.open("r", encoding="utf-8") as source:
        return json.load(source)


def c_header(spec: dict) -> str:
    desc = spec["descriptor"]
    insn = spec["instruction"]
    limits = spec["limits"]
    q4 = spec["weight_profiles"]["Q4_K"]
    q6 = spec["weight_profiles"]["Q6_K"]
    q8 = spec["activation_profiles"]["Q8_K"]
    wl = spec["weight_layouts"]
    al = spec["activation_layouts"]
    return f"""/* Generated by scripts/gen_qbs_abi.py. Do not edit. */
#ifndef ARA_QBS_ABI_H_
#define ARA_QBS_ABI_H_

#include <stddef.h>
#include <stdint.h>

#define QBS_EXTENSION_NAME \"{spec['extension_name']}\"
#define QBS_ARCH_VERSION {spec['architecture_version']}u
#define QBS_NUMERICAL_CONTRACT_VERSION {spec['numerical_contract_version']}u
#define QBS_DESCRIPTOR_VERSION {desc['version']}u
#define QBS_DESCRIPTOR_BYTES {desc['bytes']}u
#define QBS_DESCRIPTOR_ALIGNMENT_LOG2 {desc['alignment_log2']}u

#define QBS_OPCODE_CUSTOM2 0x{insn['opcode']:02x}u
#define QBS_QBEXEC_FUNCT3 {insn['qbexec_funct3']}u
#define QBS_QBINFO_FUNCT3 {insn['qbinfo_funct3']}u

#define QBS_MAX_M {limits['max_m']}u
#define QBS_MAX_N {limits['max_n']}u
#define QBS_MAX_K_BLOCKS {limits['max_k_blocks']}u
#define QBS_BLOCK_ELEMENTS {limits['block_elements']}u
#define QBS_WEIGHT_BASE_ALIGNMENT_LOG2 {limits['weight_base_alignment_log2']}u
#define QBS_ACTIVATION_BASE_ALIGNMENT_LOG2 {limits['activation_base_alignment_log2']}u

#define QBS_Q4_K_BLOCK_BYTES {q4['block_bytes']}u
#define QBS_Q4_K_SUBGROUP_COUNT {q4['subgroup_count']}u
#define QBS_Q4_K_SUBGROUP_ELEMENTS {q4['subgroup_elements']}u
#define QBS_Q6_K_BLOCK_BYTES {q6['block_bytes']}u
#define QBS_Q6_K_SUBGROUP_COUNT {q6['subgroup_count']}u
#define QBS_Q6_K_SUBGROUP_ELEMENTS {q6['subgroup_elements']}u
#define QBS_Q8_K_BLOCK_BYTES {q8['block_bytes']}u
#define QBS_Q8_K_BSUMS_COUNT {q8['bsums_count']}u

typedef enum {{
  QBS_WEIGHT_PROFILE_INVALID = 0,
  QBS_WEIGHT_PROFILE_Q4_K = {q4['id']},
  QBS_WEIGHT_PROFILE_Q6_K = {q6['id']},
}} qbs_weight_profile_t;

typedef enum {{
  QBS_ACTIVATION_PROFILE_INVALID = 0,
  QBS_ACTIVATION_PROFILE_Q8_K = {q8['id']},
}} qbs_activation_profile_t;

typedef enum {{
  QBS_WEIGHT_LAYOUT_INVALID = 0,
  QBS_WEIGHT_LAYOUT_ROW_MAJOR = {wl['ROW_MAJOR']},
  QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR = {wl['R4_BLOCK_MAJOR']},
}} qbs_weight_layout_t;

typedef enum {{
  QBS_ACTIVATION_LAYOUT_INVALID = 0,
  QBS_ACTIVATION_LAYOUT_ROW_MAJOR = {al['ROW_MAJOR']},
  QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED = {al['M4_INTERLEAVED']},
}} qbs_activation_layout_t;

typedef struct __attribute__((aligned(16))) {{
  uint64_t header;
  uint64_t weight_base;
}} qbs_descriptor_v1_t;

typedef struct {{
  uint8_t descriptor_version;
  uint8_t weight_profile;
  uint8_t activation_profile;
  uint8_t weight_layout;
  uint8_t activation_layout;
  uint8_t n;
  uint16_t k_blocks;
}} qbs_descriptor_fields_t;

#if defined(__cplusplus)
static_assert(sizeof(qbs_descriptor_v1_t) == QBS_DESCRIPTOR_BYTES,
              "invalid QBS descriptor size");
#else
_Static_assert(sizeof(qbs_descriptor_v1_t) == QBS_DESCRIPTOR_BYTES,
               "invalid QBS descriptor size");
#endif

static inline uint64_t qbs_pack_descriptor_header(
    const qbs_descriptor_fields_t *fields) {{
  return ((uint64_t)(fields->descriptor_version & 0x0fu) << 0) |
         ((uint64_t)(fields->weight_profile & 0x0fu) << 4) |
         ((uint64_t)(fields->activation_profile & 0x0fu) << 8) |
         ((uint64_t)(fields->weight_layout & 0x0fu) << 12) |
         ((uint64_t)(fields->activation_layout & 0x0fu) << 16) |
         ((uint64_t)((fields->n - 1u) & 0x1fu) << 20) |
         ((uint64_t)((fields->k_blocks - 1u) & 0xffu) << 25);
}}

static inline qbs_descriptor_fields_t qbs_unpack_descriptor_header(
    uint64_t header) {{
  qbs_descriptor_fields_t fields;
  fields.descriptor_version = (uint8_t)((header >> 0) & 0x0fu);
  fields.weight_profile = (uint8_t)((header >> 4) & 0x0fu);
  fields.activation_profile = (uint8_t)((header >> 8) & 0x0fu);
  fields.weight_layout = (uint8_t)((header >> 12) & 0x0fu);
  fields.activation_layout = (uint8_t)((header >> 16) & 0x0fu);
  fields.n = (uint8_t)(((header >> 20) & 0x1fu) + 1u);
  fields.k_blocks = (uint16_t)(((header >> 25) & 0xffu) + 1u);
  return fields;
}}

static inline uint64_t qbs_capability_word(unsigned index,
                                            unsigned vlen_bits) {{
  unsigned max_n = vlen_bits / 32u;
  if (max_n > QBS_MAX_N) max_n = QBS_MAX_N;
  if (index == 0x00u) {{
    if (max_n == 0) return 0;
    return ((uint64_t)QBS_ARCH_VERSION << 0) |
           ((uint64_t)QBS_DESCRIPTOR_VERSION << 8) |
           ((uint64_t)QBS_DESCRIPTOR_BYTES << 16) |
           ((uint64_t)(QBS_MAX_M - 1u) << 24) |
           ((uint64_t)(max_n - 1u) << 26) |
           ((uint64_t)(QBS_MAX_K_BLOCKS - 1u) << 31) |
           ((uint64_t)QBS_NUMERICAL_CONTRACT_VERSION << 39) |
           (UINT64_C(1) << 43) | (UINT64_C(1) << 44) |
           (UINT64_C(1) << 45) | (UINT64_C(1) << 46) |
           (UINT64_C(1) << 47);
  }}
  if (index == 0x01u) {{
    const uint64_t weight_layouts =
        (UINT64_C(1) << QBS_WEIGHT_LAYOUT_ROW_MAJOR) |
        (UINT64_C(1) << QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR);
    const uint64_t activation_layouts =
        (UINT64_C(1) << QBS_ACTIVATION_LAYOUT_ROW_MAJOR) |
        (UINT64_C(1) << QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED);
    return weight_layouts | (activation_layouts << 16) |
           ((uint64_t)QBS_DESCRIPTOR_ALIGNMENT_LOG2 << 32) |
           ((uint64_t)QBS_WEIGHT_BASE_ALIGNMENT_LOG2 << 40) |
           ((uint64_t)QBS_ACTIVATION_BASE_ALIGNMENT_LOG2 << 48) |
           (UINT64_C(32) << 56);
  }}
  if (index == 0x10u + QBS_WEIGHT_PROFILE_Q4_K ||
      index == 0x10u + QBS_WEIGHT_PROFILE_Q6_K)
    return UINT64_C(1) << QBS_ACTIVATION_PROFILE_Q8_K;
  if (index == 0x20u + QBS_WEIGHT_PROFILE_Q4_K)
    return (uint64_t)QBS_Q4_K_BLOCK_BYTES |
           ((uint64_t)QBS_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q4_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q4_K_SUBGROUP_ELEMENTS << 40);
  if (index == 0x20u + QBS_WEIGHT_PROFILE_Q6_K)
    return (uint64_t)QBS_Q6_K_BLOCK_BYTES |
           ((uint64_t)QBS_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q6_K_SUBGROUP_COUNT << 32) |
           ((uint64_t)QBS_Q6_K_SUBGROUP_ELEMENTS << 40);
  if (index == 0x30u + QBS_ACTIVATION_PROFILE_Q8_K)
    return (uint64_t)QBS_Q8_K_BLOCK_BYTES |
           ((uint64_t)QBS_BLOCK_ELEMENTS << 16) |
           ((uint64_t)QBS_Q8_K_BSUMS_COUNT << 32);
  return 0;
}}

static inline uint32_t qbs_encode_qbexec(unsigned vd, unsigned rs1,
                                         unsigned rs2, unsigned m) {{
  const uint32_t funct7 = (uint32_t)((m - 1u) & 0x3u);
  return (funct7 << 25) | ((uint32_t)(rs2 & 0x1fu) << 20) |
         ((uint32_t)(rs1 & 0x1fu) << 15) | (QBS_QBEXEC_FUNCT3 << 12) |
         ((uint32_t)(vd & 0x1fu) << 7) | QBS_OPCODE_CUSTOM2;
}}

static inline uint32_t qbs_encode_qbinfo(unsigned rd, unsigned rs1) {{
  return ((uint32_t)(rs1 & 0x1fu) << 15) | (QBS_QBINFO_FUNCT3 << 12) |
         ((uint32_t)(rd & 0x1fu) << 7) | QBS_OPCODE_CUSTOM2;
}}

#endif  /* ARA_QBS_ABI_H_ */
"""


def sv_package(spec: dict) -> str:
    desc = spec["descriptor"]
    insn = spec["instruction"]
    limits = spec["limits"]
    q4 = spec["weight_profiles"]["Q4_K"]
    q6 = spec["weight_profiles"]["Q6_K"]
    q8 = spec["activation_profiles"]["Q8_K"]
    wl = spec["weight_layouts"]
    al = spec["activation_layouts"]
    return f"""// Generated by scripts/gen_qbs_abi.py. Do not edit.
package qbs_pkg;

`ifdef ARA_QBS_ENABLE
  localparam bit QbsEnable = 1'b1;
`else
  localparam bit QbsEnable = 1'b0;
`endif

  localparam int unsigned QbsArchitectureVersion = {spec['architecture_version']};
  localparam int unsigned QbsNumericalContractVersion = {spec['numerical_contract_version']};
  localparam int unsigned QbsDescriptorVersion = {desc['version']};
  localparam int unsigned QbsDescriptorBytes = {desc['bytes']};
  localparam int unsigned QbsDescriptorAlignmentLog2 = {desc['alignment_log2']};

  localparam logic [6:0] QbsOpcodeCustom2 = 7'h{insn['opcode']:02x};
  localparam logic [2:0] QbsQbexecFunct3 = 3'd{insn['qbexec_funct3']};
  localparam logic [2:0] QbsQbinfoFunct3 = 3'd{insn['qbinfo_funct3']};

  localparam int unsigned QbsMaxM = {limits['max_m']};
  localparam int unsigned QbsMaxN = {limits['max_n']};
  localparam int unsigned QbsMaxKBlocks = {limits['max_k_blocks']};
  localparam int unsigned QbsBlockElements = {limits['block_elements']};
  localparam int unsigned QbsWeightBaseAlignmentLog2 = {limits['weight_base_alignment_log2']};
  localparam int unsigned QbsActivationBaseAlignmentLog2 = {limits['activation_base_alignment_log2']};

  localparam int unsigned QbsQ4KBlockBytes = {q4['block_bytes']};
  localparam int unsigned QbsQ4KSubgroupCount = {q4['subgroup_count']};
  localparam int unsigned QbsQ4KSubgroupElements = {q4['subgroup_elements']};
  localparam int unsigned QbsQ6KBlockBytes = {q6['block_bytes']};
  localparam int unsigned QbsQ6KSubgroupCount = {q6['subgroup_count']};
  localparam int unsigned QbsQ6KSubgroupElements = {q6['subgroup_elements']};
  localparam int unsigned QbsQ8KBlockBytes = {q8['block_bytes']};
  localparam int unsigned QbsQ8KBsumsCount = {q8['bsums_count']};

  typedef enum logic [3:0] {{
    QBS_WEIGHT_PROFILE_INVALID = 4'd0,
    QBS_WEIGHT_PROFILE_Q4_K = 4'd{q4['id']},
    QBS_WEIGHT_PROFILE_Q6_K = 4'd{q6['id']}
  }} qbs_weight_profile_e;

  typedef enum logic [3:0] {{
    QBS_ACTIVATION_PROFILE_INVALID = 4'd0,
    QBS_ACTIVATION_PROFILE_Q8_K = 4'd{q8['id']}
  }} qbs_activation_profile_e;

  typedef enum logic [3:0] {{
    QBS_WEIGHT_LAYOUT_INVALID = 4'd0,
    QBS_WEIGHT_LAYOUT_ROW_MAJOR = 4'd{wl['ROW_MAJOR']},
    QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR = 4'd{wl['R4_BLOCK_MAJOR']}
  }} qbs_weight_layout_e;

  typedef enum logic [3:0] {{
    QBS_ACTIVATION_LAYOUT_INVALID = 4'd0,
    QBS_ACTIVATION_LAYOUT_ROW_MAJOR = 4'd{al['ROW_MAJOR']},
    QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED = 4'd{al['M4_INTERLEAVED']}
  }} qbs_activation_layout_e;

  // Internal validation result. These values are not software-visible ABI;
  // they make directed RTL checks and command fault attribution unambiguous.
  typedef enum logic [4:0] {{
    QBS_VALIDATION_OK = 5'd0,
    QBS_VALIDATION_DESCRIPTOR_ALIGNMENT = 5'd1,
    QBS_VALIDATION_DESCRIPTOR_VERSION = 5'd2,
    QBS_VALIDATION_DESCRIPTOR_RESERVED = 5'd3,
    QBS_VALIDATION_WEIGHT_PROFILE = 5'd4,
    QBS_VALIDATION_ACTIVATION_PROFILE = 5'd5,
    QBS_VALIDATION_WEIGHT_LAYOUT = 5'd6,
    QBS_VALIDATION_ACTIVATION_LAYOUT = 5'd7,
    QBS_VALIDATION_M_RANGE = 5'd8,
    QBS_VALIDATION_N_RANGE = 5'd9,
    QBS_VALIDATION_K_RANGE = 5'd10,
    QBS_VALIDATION_VD_ALIGNMENT = 5'd11,
    QBS_VALIDATION_WEIGHT_ALIGNMENT = 5'd12,
    QBS_VALIDATION_ACTIVATION_ALIGNMENT = 5'd13,
    QBS_VALIDATION_WEIGHT_RANGE_OVERFLOW = 5'd14,
    QBS_VALIDATION_ACTIVATION_RANGE_OVERFLOW = 5'd15
  }} qbs_validation_error_e;

  // Internal read-path fault attribution. These values are not part of the
  // software ABI; the QBS command controller maps them to architectural
  // load exceptions only after the current AXI response has been drained.
  typedef enum logic [2:0] {{
    QBS_READ_FAULT_NONE = 3'd0,
    QBS_READ_FAULT_REQUEST = 3'd1,
    QBS_READ_FAULT_MMU = 3'd2,
    QBS_READ_FAULT_AXI_RESPONSE = 3'd3,
    QBS_READ_FAULT_AXI_PROTOCOL = 3'd4,
    QBS_READ_FAULT_PMA = 3'd5
  }} qbs_read_fault_e;

  typedef struct packed {{
    logic [63:0] weight_base;
    logic [63:0] header;
  }} qbs_descriptor_v1_t;

  localparam int unsigned QbsDescVersionLsb = 0;
  localparam int unsigned QbsDescWeightProfileLsb = 4;
  localparam int unsigned QbsDescActivationProfileLsb = 8;
  localparam int unsigned QbsDescWeightLayoutLsb = 12;
  localparam int unsigned QbsDescActivationLayoutLsb = 16;
  localparam int unsigned QbsDescNMinus1Lsb = 20;
  localparam int unsigned QbsDescKBlocksMinus1Lsb = 25;
  localparam int unsigned QbsDescReservedLsb = 33;

  function automatic logic [63:0] qbs_capability_word(
      input logic [63:0] index,
      input int unsigned vlen_bits
  );
    int unsigned max_n;
    logic [63:0] result;
    max_n = vlen_bits / 32;
    if (max_n > QbsMaxN) max_n = QbsMaxN;
    result = '0;
    unique case (index)
      64'h00: begin
        if (max_n != 0) begin
          result[7:0]   = 8'(QbsArchitectureVersion);
          result[15:8]  = 8'(QbsDescriptorVersion);
          result[23:16] = 8'(QbsDescriptorBytes);
          result[25:24] = 2'(QbsMaxM - 1);
          result[30:26] = 5'(max_n - 1);
          result[38:31] = 8'(QbsMaxKBlocks - 1);
          result[42:39] = 4'(QbsNumericalContractVersion);
          result[47:43] = 5'b1_1111;
        end
      end
      64'h01: begin
        result[QBS_WEIGHT_LAYOUT_ROW_MAJOR] = 1'b1;
        result[QBS_WEIGHT_LAYOUT_R4_BLOCK_MAJOR] = 1'b1;
        result[16 + QBS_ACTIVATION_LAYOUT_ROW_MAJOR] = 1'b1;
        result[16 + QBS_ACTIVATION_LAYOUT_M4_INTERLEAVED] = 1'b1;
        result[39:32] = 8'(QbsDescriptorAlignmentLog2);
        result[47:40] = 8'(QbsWeightBaseAlignmentLog2);
        result[55:48] = 8'(QbsActivationBaseAlignmentLog2);
        result[63:56] = 8'd32;
      end
      64'h{0x10 + q4['id']:02x},
      64'h{0x10 + q6['id']:02x}:
        result[QBS_ACTIVATION_PROFILE_Q8_K] = 1'b1;
      64'h{0x20 + q4['id']:02x}: begin
        result[15:0]  = 16'(QbsQ4KBlockBytes);
        result[31:16] = 16'(QbsBlockElements);
        result[39:32] = 8'(QbsQ4KSubgroupCount);
        result[47:40] = 8'(QbsQ4KSubgroupElements);
      end
      64'h{0x20 + q6['id']:02x}: begin
        result[15:0]  = 16'(QbsQ6KBlockBytes);
        result[31:16] = 16'(QbsBlockElements);
        result[39:32] = 8'(QbsQ6KSubgroupCount);
        result[47:40] = 8'(QbsQ6KSubgroupElements);
      end
      64'h{0x30 + q8['id']:02x}: begin
        result[15:0]  = 16'(QbsQ8KBlockBytes);
        result[31:16] = 16'(QbsBlockElements);
        result[39:32] = 8'(QbsQ8KBsumsCount);
      end
      default: ;
    endcase
    return result;
  endfunction : qbs_capability_word

endpackage : qbs_pkg
"""


def update(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = load_spec()
    ok = update(C_PATH, c_header(spec), args.check)
    ok &= update(SV_PATH, sv_package(spec), args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
