#!/usr/bin/env python3
"""Generate C and SystemVerilog AKV ABI definitions from one JSON source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "config/akv_abi.json"
C_PATHS = [
    ROOT / "apps/common/akv_abi.h",
    ROOT / "software/akv/include/akv/akv_abi.h",
]
SV_PATH = ROOT / "hardware/include/akv_pkg.sv"


def load_spec() -> dict:
    return json.loads(SPEC_PATH.read_text(encoding="utf-8"))


def validate_spec(spec: dict) -> None:
    descriptor = spec["descriptor"]
    instruction = spec["instruction"]
    limits = spec["limits"]
    if spec["architecture_version"] != 1:
        raise ValueError("AKV architecture version must be one")
    if descriptor != {"version": 1, "bytes": 64, "alignment_log2": 6}:
        raise ValueError("AKV descriptor v1 is fixed at 64-byte size/alignment")
    opcode = int(instruction["opcode"], 0)
    if opcode != 0x5B:
        raise ValueError("AKV v1 shares the custom-2 opcode with QBS")
    funct3 = [instruction[name] for name in (
        "fill_funct3", "load_funct3", "info_funct3", "release_funct3"
    )]
    if len(set(funct3)) != 4 or any(not 0 <= value < 8 for value in funct3):
        raise ValueError("AKV funct3 values must be distinct 3-bit values")
    if any(value in (0, 1) for value in funct3):
        raise ValueError("AKV funct3 values 0 and 1 are reserved by QBS")
    if limits["context_count"] != 1:
        raise ValueError("AKV v1 defines exactly one non-architectural context")
    if not 1 <= limits["max_q_rows"] <= 8:
        raise ValueError("AKV q-row selector has a 3-bit index")
    if limits["tile_tokens"] != 8:
        raise ValueError("AKV v1 fixes the KV tile at eight tokens")
    if limits["head_dims"] != [64, 128]:
        raise ValueError("AKV v1 supports only D=64 and D=128")
    if spec["element_formats"] != {"F16": 1}:
        raise ValueError("AKV v1 supports only F16 resident vectors")
    if spec["streams"] != {"Q": 0, "K": 1, "V": 2}:
        raise ValueError("AKV v1 stream encoding changed")
    if spec["fill_modes"] != {"FULL": 0, "REFILL": 1}:
        raise ValueError("AKV v1 fill-mode encoding changed")


def c_header(spec: dict) -> str:
    desc = spec["descriptor"]
    insn = spec["instruction"]
    limits = spec["limits"]
    opcode = int(insn["opcode"], 0)
    return f"""/* Generated by scripts/gen_akv_abi.py. Do not edit. */
#ifndef AKV_ABI_H
#define AKV_ABI_H

#include <stddef.h>
#include <stdint.h>

#define AKV_ARCHITECTURE_VERSION {spec['architecture_version']}u
#define AKV_DESCRIPTOR_VERSION {desc['version']}u
#define AKV_DESCRIPTOR_BYTES {desc['bytes']}u
#define AKV_DESCRIPTOR_ALIGNMENT_LOG2 {desc['alignment_log2']}u
#define AKV_OPCODE_CUSTOM2 0x{opcode:02x}u
#define AKV_FILL_FUNCT3 {insn['fill_funct3']}u
#define AKV_LOAD_FUNCT3 {insn['load_funct3']}u
#define AKV_INFO_FUNCT3 {insn['info_funct3']}u
#define AKV_RELEASE_FUNCT3 {insn['release_funct3']}u
#define AKV_CONTEXT_COUNT {limits['context_count']}u
#define AKV_MAX_Q_ROWS {limits['max_q_rows']}u
#define AKV_TILE_TOKENS {limits['tile_tokens']}u
#define AKV_HEAD_DIM_64 64u
#define AKV_HEAD_DIM_128 128u
#define AKV_HEAD_DIM_CODE_64 0u
#define AKV_HEAD_DIM_CODE_128 1u
#define AKV_HEAD_DIM_CODE_INVALID 0xffu

typedef enum {{
  AKV_ELEMENT_FORMAT_INVALID = 0,
  AKV_ELEMENT_FORMAT_F16 = {spec['element_formats']['F16']},
}} akv_element_format_t;

typedef enum {{
  AKV_STREAM_Q = {spec['streams']['Q']},
  AKV_STREAM_K = {spec['streams']['K']},
  AKV_STREAM_V = {spec['streams']['V']},
}} akv_stream_t;

typedef enum {{
  AKV_FILL_FULL = {spec['fill_modes']['FULL']},
  AKV_FILL_REFILL = {spec['fill_modes']['REFILL']},
}} akv_fill_mode_t;

typedef struct __attribute__((aligned(AKV_DESCRIPTOR_BYTES))) {{
  uint8_t version;
  uint8_t element_format;
  uint8_t q_rows;
  uint8_t flags;
  uint16_t head_dim;
  uint16_t kv_length;
  uint32_t q_row_stride_bytes;
  uint32_t k_token_stride_bytes;
  uint32_t v_token_stride_bytes;
  uint32_t reserved0;
  uint64_t q_base;
  uint64_t k_base;
  uint64_t v_base;
  uint64_t reserved1;
  uint64_t reserved2;
}} akv_descriptor_t;

#if defined(__cplusplus)
static_assert(sizeof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
              "AKV descriptor size mismatch");
static_assert(alignof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
              "AKV descriptor alignment mismatch");
#else
_Static_assert(sizeof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
               "AKV descriptor size mismatch");
_Static_assert(_Alignof(akv_descriptor_t) == AKV_DESCRIPTOR_BYTES,
               "AKV descriptor alignment mismatch");
#endif

static inline uint32_t akv_head_dim_code(uint32_t head_dim) {{
  if (head_dim == AKV_HEAD_DIM_64) return AKV_HEAD_DIM_CODE_64;
  if (head_dim == AKV_HEAD_DIM_128) return AKV_HEAD_DIM_CODE_128;
  return AKV_HEAD_DIM_CODE_INVALID;
}}

static inline uint32_t akv_destination_registers(uint32_t head_dim) {{
  if (head_dim == AKV_HEAD_DIM_64) return 1u;
  if (head_dim == AKV_HEAD_DIM_128) return 2u;
  return 0u;
}}

static inline uint32_t akv_tile_length(uint32_t kv_length,
                                       uint32_t tile_start) {{
  if (tile_start >= kv_length) return 0u;
  const uint32_t remaining = kv_length - tile_start;
  return remaining < AKV_TILE_TOKENS ? remaining : AKV_TILE_TOKENS;
}}

static inline uint32_t akv_selector(akv_stream_t stream, uint32_t index) {{
  if ((uint32_t)stream > (uint32_t)AKV_STREAM_V || index >= 8u)
    return UINT32_MAX;
  return (uint32_t)stream | (index << 2);
}}

static inline uint32_t akv_selector_stream(uint32_t selector) {{
  return selector & 0x3u;
}}

static inline uint32_t akv_selector_index(uint32_t selector) {{
  return (selector >> 2) & 0x7u;
}}

static inline int akv_range_fits(uint64_t base, uint32_t stride,
                                 uint32_t count, uint32_t row_bytes) {{
  if (count == 0u || row_bytes == 0u) return 0;
  const uint64_t last = (uint64_t)(count - 1u) * stride;
  return last <= UINT64_MAX - base &&
         (uint64_t)(row_bytes - 1u) <= UINT64_MAX - (base + last);
}}

static inline int akv_descriptor_is_valid(const void *descriptor_address) {{
  if (descriptor_address == NULL ||
      ((uintptr_t)descriptor_address & (AKV_DESCRIPTOR_BYTES - 1u)) != 0u)
    return 0;
  const akv_descriptor_t *descriptor =
      (const akv_descriptor_t *)descriptor_address;
  if (descriptor->version != AKV_DESCRIPTOR_VERSION ||
      descriptor->element_format != AKV_ELEMENT_FORMAT_F16 ||
      descriptor->q_rows == 0u || descriptor->q_rows > AKV_MAX_Q_ROWS ||
      akv_head_dim_code(descriptor->head_dim) == AKV_HEAD_DIM_CODE_INVALID ||
      descriptor->kv_length == 0u || descriptor->flags != 0u ||
      descriptor->reserved0 != 0u || descriptor->reserved1 != 0u ||
      descriptor->reserved2 != 0u)
    return 0;
  const uint32_t row_bytes = (uint32_t)descriptor->head_dim * 2u;
  if (descriptor->q_row_stride_bytes < row_bytes ||
      descriptor->k_token_stride_bytes < row_bytes ||
      descriptor->v_token_stride_bytes < row_bytes ||
      ((descriptor->q_base | descriptor->k_base | descriptor->v_base |
        descriptor->q_row_stride_bytes | descriptor->k_token_stride_bytes |
        descriptor->v_token_stride_bytes) & UINT64_C(1)) != 0u)
    return 0;
  return akv_range_fits(descriptor->q_base,
                        descriptor->q_row_stride_bytes,
                        descriptor->q_rows, row_bytes) &&
         akv_range_fits(descriptor->k_base,
                        descriptor->k_token_stride_bytes,
                        descriptor->kv_length, row_bytes) &&
         akv_range_fits(descriptor->v_base,
                        descriptor->v_token_stride_bytes,
                        descriptor->kv_length, row_bytes);
}}

static inline int akv_load_selector_is_valid(const akv_descriptor_t *descriptor,
                                              uint32_t tile_length,
                                              uint32_t selector) {{
  if (!akv_descriptor_is_valid(descriptor) || (selector >> 5) != 0u)
    return 0;
  const uint32_t stream = akv_selector_stream(selector);
  const uint32_t index = akv_selector_index(selector);
  if (stream == AKV_STREAM_Q) return index < descriptor->q_rows;
  if (stream == AKV_STREAM_K || stream == AKV_STREAM_V)
    return index < tile_length && tile_length <= AKV_TILE_TOKENS;
  return 0;
}}

static inline uint64_t akv_capability_word(uint64_t index, int enabled) {{
  if (index == 0u)
    return (uint64_t)AKV_ARCHITECTURE_VERSION |
           ((uint64_t)AKV_DESCRIPTOR_VERSION << 8) |
           ((uint64_t)AKV_DESCRIPTOR_BYTES << 16) |
           ((uint64_t)AKV_MAX_Q_ROWS << 24) |
           ((uint64_t)AKV_TILE_TOKENS << 32) |
           ((uint64_t)AKV_CONTEXT_COUNT << 40) |
           ((uint64_t)(enabled != 0) << 48) |
           (UINT64_C(1) << 49) | (UINT64_C(1) << 50) |
           (UINT64_C(1) << 51);
  if (index == 1u)
    return (uint64_t)AKV_OPCODE_CUSTOM2 |
           ((uint64_t)AKV_FILL_FUNCT3 << 8) |
           ((uint64_t)AKV_LOAD_FUNCT3 << 11) |
           ((uint64_t)AKV_INFO_FUNCT3 << 14) |
           ((uint64_t)AKV_RELEASE_FUNCT3 << 17) |
           ((uint64_t)AKV_DESCRIPTOR_ALIGNMENT_LOG2 << 20);
  return UINT64_C(0);
}}

static inline uint32_t akv_encode_r(uint32_t funct3, uint32_t funct7,
                                    uint32_t rd, uint32_t rs1,
                                    uint32_t rs2) {{
  return ((funct7 & 0x7fu) << 25) | ((rs2 & 0x1fu) << 20) |
         ((rs1 & 0x1fu) << 15) | ((funct3 & 0x7u) << 12) |
         ((rd & 0x1fu) << 7) | AKV_OPCODE_CUSTOM2;
}}

static inline uint32_t akv_encode_fill(uint32_t descriptor_rs1,
                                       uint32_t tile_start_rs2,
                                       akv_fill_mode_t mode) {{
  return akv_encode_r(AKV_FILL_FUNCT3, (uint32_t)mode, 0u,
                      descriptor_rs1, tile_start_rs2);
}}

static inline uint32_t akv_encode_load(uint32_t vd, uint32_t selector_rs1,
                                       uint32_t head_dim) {{
  return akv_encode_r(AKV_LOAD_FUNCT3, akv_head_dim_code(head_dim), vd,
                      selector_rs1, 0u);
}}

static inline uint32_t akv_encode_info(uint32_t rd, uint32_t index_rs1) {{
  return akv_encode_r(AKV_INFO_FUNCT3, 0u, rd, index_rs1, 0u);
}}

static inline uint32_t akv_encode_release(void) {{
  return akv_encode_r(AKV_RELEASE_FUNCT3, 0u, 0u, 0u, 0u);
}}

#endif
"""


def sv_package(spec: dict) -> str:
    desc = spec["descriptor"]
    insn = spec["instruction"]
    limits = spec["limits"]
    opcode = int(insn["opcode"], 0)
    return f"""// Generated by scripts/gen_akv_abi.py. Do not edit.
package akv_pkg;

`ifdef ARA_AKV_ENABLE
  localparam bit AkvEnable = 1'b1;
`else
  localparam bit AkvEnable = 1'b0;
`endif

  localparam int unsigned AkvArchitectureVersion = {spec['architecture_version']};
  localparam int unsigned AkvDescriptorVersion = {desc['version']};
  localparam int unsigned AkvDescriptorBytes = {desc['bytes']};
  localparam int unsigned AkvDescriptorAlignmentLog2 = {desc['alignment_log2']};
  localparam logic [6:0] AkvOpcodeCustom2 = 7'h{opcode:02x};
  localparam logic [2:0] AkvFillFunct3 = 3'd{insn['fill_funct3']};
  localparam logic [2:0] AkvLoadFunct3 = 3'd{insn['load_funct3']};
  localparam logic [2:0] AkvInfoFunct3 = 3'd{insn['info_funct3']};
  localparam logic [2:0] AkvReleaseFunct3 = 3'd{insn['release_funct3']};
  localparam int unsigned AkvContextCount = {limits['context_count']};
  localparam int unsigned AkvMaxQRows = {limits['max_q_rows']};
  localparam int unsigned AkvTileTokens = {limits['tile_tokens']};
  localparam int unsigned AkvMaxHeadDim = 128;
  localparam int unsigned AkvContextBytes =
      (AkvMaxQRows + 2 * AkvTileTokens) * AkvMaxHeadDim * 2;

  typedef enum logic [7:0] {{
    AKV_ELEMENT_FORMAT_INVALID = 8'd0,
    AKV_ELEMENT_FORMAT_F16 = 8'd{spec['element_formats']['F16']}
  }} akv_element_format_e;

  typedef enum logic [1:0] {{
    AKV_STREAM_Q = 2'd{spec['streams']['Q']},
    AKV_STREAM_K = 2'd{spec['streams']['K']},
    AKV_STREAM_V = 2'd{spec['streams']['V']}
  }} akv_stream_e;

  typedef enum logic {{
    AKV_FILL_FULL = 1'b{spec['fill_modes']['FULL']},
    AKV_FILL_REFILL = 1'b{spec['fill_modes']['REFILL']}
  }} akv_fill_mode_e;

  typedef enum logic [1:0] {{
    AKV_COMMAND_FULL,
    AKV_COMMAND_REFILL,
    AKV_COMMAND_LOAD,
    AKV_COMMAND_RELEASE
  }} akv_command_e;

  typedef enum logic [4:0] {{
    AKV_VALIDATION_OK,
    AKV_VALIDATION_COMMAND,
    AKV_VALIDATION_DESCRIPTOR_ALIGNMENT,
    AKV_VALIDATION_DESCRIPTOR_VERSION,
    AKV_VALIDATION_DESCRIPTOR_FORMAT,
    AKV_VALIDATION_Q_ROWS,
    AKV_VALIDATION_HEAD_DIM,
    AKV_VALIDATION_KV_LENGTH,
    AKV_VALIDATION_RESERVED,
    AKV_VALIDATION_STRIDE,
    AKV_VALIDATION_RANGE_OVERFLOW,
    AKV_VALIDATION_TILE_RANGE,
    AKV_VALIDATION_CONTEXT,
    AKV_VALIDATION_SELECTOR,
    AKV_VALIDATION_DESTINATION
  }} akv_validation_error_e;

  typedef struct packed {{
    logic [63:0] reserved2;
    logic [63:0] reserved1;
    logic [63:0] v_base;
    logic [63:0] k_base;
    logic [63:0] q_base;
    logic [31:0] reserved0;
    logic [31:0] v_token_stride_bytes;
    logic [31:0] k_token_stride_bytes;
    logic [31:0] q_row_stride_bytes;
    logic [15:0] kv_length;
    logic [15:0] head_dim;
    logic [7:0] flags;
    logic [7:0] q_rows;
    akv_element_format_e element_format;
    logic [7:0] version;
  }} akv_descriptor_v1_t;

  function automatic logic [7:0] akv_head_dim_code(input int unsigned head_dim);
    unique case (head_dim)
      64: akv_head_dim_code = 8'd0;
      128: akv_head_dim_code = 8'd1;
      default: akv_head_dim_code = 8'hff;
    endcase
  endfunction : akv_head_dim_code

  function automatic logic [63:0] akv_capability_word(
      input logic [63:0] index, input bit enabled
  );
    akv_capability_word = '0;
    unique case (index)
      64'd0: akv_capability_word =
          64'({spec['architecture_version']}) |
          (64'({desc['version']}) << 8) |
          (64'({desc['bytes']}) << 16) |
          (64'({limits['max_q_rows']}) << 24) |
          (64'({limits['tile_tokens']}) << 32) |
          (64'({limits['context_count']}) << 40) |
          (64'(enabled) << 48) |
          (64'd1 << 49) | (64'd1 << 50) | (64'd1 << 51);
      64'd1: akv_capability_word =
          64'(AkvOpcodeCustom2) |
          (64'(AkvFillFunct3) << 8) |
          (64'(AkvLoadFunct3) << 11) |
          (64'(AkvInfoFunct3) << 14) |
          (64'(AkvReleaseFunct3) << 17) |
          (64'(AkvDescriptorAlignmentLog2) << 20);
      default: ;
    endcase
  endfunction : akv_capability_word

endpackage : akv_pkg
"""


def generated_outputs(spec: dict) -> dict[Path, str]:
    header = c_header(spec)
    return {**{path: header for path in C_PATHS}, SV_PATH: sv_package(spec)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = load_spec()
    validate_spec(spec)
    outputs = generated_outputs(spec)
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
