// Randomized differential regression against vectors generated by the
// independent Python integer oracle.  This exercises the segmented lane
// accumulator and the central one-shot finalizer together.

module fp_exact_reduction_oracle_tb;
  localparam int unsigned VectorCount = 900;
  localparam int unsigned VectorWidth = 141;

  logic clk;
  logic rst_n;
  logic start;
  logic [2:0] rnd_mode;
  logic format_fp16;
  logic [31:0] seed;
  logic [63:0] data;
  logic [3:0] active;
  logic in_valid;
  logic in_ready;
  logic out_valid;
  logic out_ready;
  logic busy;

  logic [287:0] exact_value;
  logic [3:0] special;
  logic source_seen;
  logic finite_nonzero_seen;
  logic pos_zero_seen;
  logic neg_zero_seen;
  logic state_seed_valid;
  logic [31:0] state_seed;
  logic [2:0] state_rnd_mode;
  logic state_format_fp16;
  logic [31:0] final_result;
  logic [4:0] final_status;
  logic late_in_ready;
  logic late_out_valid;
  logic late_busy;
  logic [287:0] late_exact_value;
  logic [3:0] late_special;
  logic late_source_seen;
  logic late_finite_nonzero_seen;
  logic late_pos_zero_seen;
  logic late_neg_zero_seen;
  logic [2:0] late_rnd_mode;
  logic late_format_fp16;
  logic [31:0] late_final_result;
  logic [4:0] late_final_status;

  logic [VectorWidth-1:0] vectors [0:VectorCount-1];

  fp32_exact_reduction_accum #(
    .ExponentSegmented (1'b1),
    .EmitRoundedResult (1'b0)
  ) i_accum (
    .clk_i                  (clk),
    .rst_ni                 (rst_n),
    .start_i                (start),
    .rnd_mode_i             (rnd_mode),
    .format_fp16_i          (format_fp16),
    .seed_valid_i           (1'b1),
    .seed_i                 (seed),
    .data_i                 (data),
    .active_i               (active),
    .last_i                 (1'b1),
    .in_valid_i             (in_valid),
    .in_ready_o             (in_ready),
    .result_o               (),
    .status_o               (),
    .out_valid_o            (out_valid),
    .out_ready_i            (out_ready),
    .busy_o                 (busy),
    .exact_value_o          (exact_value),
    .special_o              (special),
    .source_seen_o          (source_seen),
    .finite_nonzero_seen_o  (finite_nonzero_seen),
    .pos_zero_seen_o        (pos_zero_seen),
    .neg_zero_seen_o        (neg_zero_seen),
    .seed_valid_o           (state_seed_valid),
    .seed_o                 (state_seed),
    .rnd_mode_o             (state_rnd_mode),
    .format_fp16_o          (state_format_fp16)
  );

  fp32_exact_reduction_finalize i_finalize (
    .exact_value_i          (exact_value),
    .special_i              (special),
    .source_seen_i          (source_seen),
    .finite_nonzero_seen_i  (finite_nonzero_seen),
    .pos_zero_seen_i        (pos_zero_seen),
    .neg_zero_seen_i        (neg_zero_seen),
    .seed_valid_i           (state_seed_valid),
    .seed_i                 (state_seed),
    .seed_in_exact_i        (1'b1),
    .rnd_mode_i             (state_rnd_mode),
    .format_fp16_i          (state_format_fp16),
    .result_o               (final_result),
    .status_o               (final_status)
  );

  // The same source subtree without a seed models the versioned chain path.
  // Its finalizer receives the preceding instruction's rounded result only at
  // the global merge boundary.
  fp32_exact_reduction_accum #(
    .ExponentSegmented (1'b1),
    .EmitRoundedResult (1'b0)
  ) i_late_accum (
    .clk_i                  (clk),
    .rst_ni                 (rst_n),
    .start_i                (start),
    .rnd_mode_i             (rnd_mode),
    .format_fp16_i          (format_fp16),
    .seed_valid_i           (1'b0),
    .seed_i                 ('0),
    .data_i                 (data),
    .active_i               (active),
    .last_i                 (1'b1),
    .in_valid_i             (in_valid),
    .in_ready_o             (late_in_ready),
    .result_o               (),
    .status_o               (),
    .out_valid_o            (late_out_valid),
    .out_ready_i            (out_ready),
    .busy_o                 (late_busy),
    .exact_value_o          (late_exact_value),
    .special_o              (late_special),
    .source_seen_o          (late_source_seen),
    .finite_nonzero_seen_o  (late_finite_nonzero_seen),
    .pos_zero_seen_o        (late_pos_zero_seen),
    .neg_zero_seen_o        (late_neg_zero_seen),
    .seed_valid_o           (),
    .seed_o                 (),
    .rnd_mode_o             (late_rnd_mode),
    .format_fp16_o          (late_format_fp16)
  );

  fp32_exact_reduction_finalize i_late_finalize (
    .exact_value_i          (late_exact_value),
    .special_i              (late_special),
    .source_seen_i          (late_source_seen),
    .finite_nonzero_seen_i  (late_finite_nonzero_seen),
    .pos_zero_seen_i        (late_pos_zero_seen),
    .neg_zero_seen_i        (late_neg_zero_seen),
    .seed_valid_i           (1'b1),
    .seed_i                 (seed),
    .seed_in_exact_i        (1'b0),
    .rnd_mode_i             (late_rnd_mode),
    .format_fp16_i          (late_format_fp16),
    .result_o               (late_final_result),
    .status_o               (late_final_status)
  );

  always #5 clk = ~clk;

  initial begin
    logic [31:0] expected_result;
    logic [4:0] expected_status;

    $readmemh("hardware/tb/fp_exact_reduction_oracle_vectors.mem", vectors);
    clk = 1'b0;
    rst_n = 1'b0;
    start = 1'b0;
    rnd_mode = '0;
    format_fp16 = 1'b0;
    seed = '0;
    data = '0;
    active = '0;
    in_valid = 1'b0;
    out_ready = 1'b1;

    repeat (3) @(posedge clk);
    rst_n = 1'b1;

    for (int unsigned test = 0; test < VectorCount; test++) begin
      wait (!busy && !late_busy);
      @(negedge clk);
      {format_fp16, rnd_mode, seed, data, active,
       expected_result, expected_status} = vectors[test];
      start = 1'b1;
      in_valid = 1'b1;
      @(negedge clk);
      start = 1'b0;
      in_valid = 1'b0;

      wait (out_valid && late_out_valid);
      #1;
      if ({final_status, final_result} !==
          {expected_status, expected_result}) begin
        $error(
          "oracle mismatch test=%0d fp16=%0b rm=%0d seed=%08x data=%016x active=%x got=%02x/%08x expected=%02x/%08x exact=%072x",
          test, format_fp16, rnd_mode, seed, data, active,
          final_status, final_result, expected_status, expected_result,
          exact_value);
        $fatal(1);
      end
      if ({late_final_status, late_final_result} !==
          {expected_status, expected_result}) begin
        $error(
          "late-seed mismatch test=%0d fp16=%0b rm=%0d seed=%08x data=%016x active=%x got=%02x/%08x expected=%02x/%08x exact=%072x",
          test, format_fp16, rnd_mode, seed, data, active,
          late_final_status, late_final_result,
          expected_status, expected_result, late_exact_value);
        $fatal(1);
      end
      @(posedge clk);
    end

    $display("PASS: exact integer oracle (%0d FP32/FP16/widening reductions, conventional and late seed)",
             VectorCount);
    $finish;
  end

endmodule
